// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/course_type/course_type.proto

package coursetypev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CourseType categorizes courses (e.g. "Piano Grade 3", "Violin Beginners").
type CourseType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this course type.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseType) Reset() {
	*x = CourseType{}
	mi := &file_v1_course_scheduling_course_type_course_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseType) ProtoMessage() {}

func (x *CourseType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_type_course_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseType.ProtoReflect.Descriptor instead.
func (*CourseType) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_type_course_type_proto_rawDescGZIP(), []int{0}
}

func (x *CourseType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourseType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CourseType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CourseTypeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTypes   []*CourseType          `protobuf:"bytes,1,rep,name=course_types,json=courseTypes,proto3" json:"course_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseTypeSet) Reset() {
	*x = CourseTypeSet{}
	mi := &file_v1_course_scheduling_course_type_course_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseTypeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseTypeSet) ProtoMessage() {}

func (x *CourseTypeSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_type_course_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseTypeSet.ProtoReflect.Descriptor instead.
func (*CourseTypeSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_type_course_type_proto_rawDescGZIP(), []int{1}
}

func (x *CourseTypeSet) GetCourseTypes() []*CourseType {
	if x != nil {
		return x.CourseTypes
	}
	return nil
}

var File_v1_course_scheduling_course_type_course_type_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_course_type_course_type_proto_rawDesc = "" +
	"\n" +
	"2v1/course_scheduling/course_type/course_type.proto\x12\x14v1.course_scheduling\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n" +
	"\n" +
	"CourseType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"T\n" +
	"\rCourseTypeSet\x12C\n" +
	"\fcourse_types\x18\x01 \x03(\v2 .v1.course_scheduling.CourseTypeR\vcourseTypesBr\n" +
	"%io.grpc.examples.course_scheduling.v1B\x0fCourseTypeProtoP\x01Z6cqrs/api/v1/course_scheduling/course_type;coursetypev1b\x06proto3"

var (
	file_v1_course_scheduling_course_type_course_type_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_course_type_course_type_proto_rawDescData []byte
)

func file_v1_course_scheduling_course_type_course_type_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_course_type_course_type_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_course_type_course_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_type_course_type_proto_rawDesc), len(file_v1_course_scheduling_course_type_course_type_proto_rawDesc)))
	})
	return file_v1_course_scheduling_course_type_course_type_proto_rawDescData
}

var file_v1_course_scheduling_course_type_course_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_course_scheduling_course_type_course_type_proto_goTypes = []any{
	(*CourseType)(nil),            // 0: v1.course_scheduling.CourseType
	(*CourseTypeSet)(nil),         // 1: v1.course_scheduling.CourseTypeSet
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_course_scheduling_course_type_course_type_proto_depIdxs = []int32{
	2, // 0: v1.course_scheduling.CourseType.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: v1.course_scheduling.CourseType.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: v1.course_scheduling.CourseTypeSet.course_types:type_name -> v1.course_scheduling.CourseType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_course_type_course_type_proto_init() }
func file_v1_course_scheduling_course_type_course_type_proto_init() {
	if File_v1_course_scheduling_course_type_course_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_type_course_type_proto_rawDesc), len(file_v1_course_scheduling_course_type_course_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_course_scheduling_course_type_course_type_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_course_type_course_type_proto_depIdxs,
		MessageInfos:      file_v1_course_scheduling_course_type_course_type_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_course_type_course_type_proto = out.File
	file_v1_course_scheduling_course_type_course_type_proto_goTypes = nil
	file_v1_course_scheduling_course_type_course_type_proto_depIdxs = nil
}
