// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/classroom/classroom.proto

package classroomv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationClassroomServiceDeleteClassroom = "/v1.course_scheduling.ClassroomService/DeleteClassroom"
const OperationClassroomServiceGetClassroom = "/v1.course_scheduling.ClassroomService/GetClassroom"
const OperationClassroomServiceListClassrooms = "/v1.course_scheduling.ClassroomService/ListClassrooms"
const OperationClassroomServiceSaveClassroom = "/v1.course_scheduling.ClassroomService/SaveClassroom"

type ClassroomServiceHTTPServer interface {
	// DeleteClassroom DeleteClassroom hard-deletes a classroom by ID.
	DeleteClassroom(context.Context, *DeleteClassroomRequest) (*emptypb.Empty, error)
	// GetClassroom GetClassroom returns a single classroom by ID.
	GetClassroom(context.Context, *GetClassroomRequest) (*Classroom, error)
	// ListClassrooms ListClassrooms returns a page of classrooms.
	ListClassrooms(context.Context, *ListClassroomsRequest) (*ClassroomSet, error)
	// SaveClassroom SaveClassroom creates or updates a classroom.
	SaveClassroom(context.Context, *SaveClassroomRequest) (*Classroom, error)
}

func RegisterClassroomServiceHTTPServer(s *http.Server, srv ClassroomServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/classrooms", _ClassroomService_SaveClassroom0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/classrooms/{id}", _ClassroomService_DeleteClassroom0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/classrooms/{id}", _ClassroomService_GetClassroom0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/classrooms", _ClassroomService_ListClassrooms0_HTTP_Handler(srv))
}

func _ClassroomService_SaveClassroom0_HTTP_Handler(srv ClassroomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveClassroomRequest
		if err := ctx.Bind(&in.Classroom); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassroomServiceSaveClassroom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveClassroom(ctx, req.(*SaveClassroomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Classroom)
		return ctx.Result(200, reply)
	}
}

func _ClassroomService_DeleteClassroom0_HTTP_Handler(srv ClassroomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteClassroomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassroomServiceDeleteClassroom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteClassroom(ctx, req.(*DeleteClassroomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ClassroomService_GetClassroom0_HTTP_Handler(srv ClassroomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetClassroomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassroomServiceGetClassroom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetClassroom(ctx, req.(*GetClassroomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Classroom)
		return ctx.Result(200, reply)
	}
}

func _ClassroomService_ListClassrooms0_HTTP_Handler(srv ClassroomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListClassroomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassroomServiceListClassrooms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListClassrooms(ctx, req.(*ListClassroomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClassroomSet)
		return ctx.Result(200, reply)
	}
}

type ClassroomServiceHTTPClient interface {
	// DeleteClassroom DeleteClassroom hard-deletes a classroom by ID.
	DeleteClassroom(ctx context.Context, req *DeleteClassroomRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetClassroom GetClassroom returns a single classroom by ID.
	GetClassroom(ctx context.Context, req *GetClassroomRequest, opts ...http.CallOption) (rsp *Classroom, err error)
	// ListClassrooms ListClassrooms returns a page of classrooms.
	ListClassrooms(ctx context.Context, req *ListClassroomsRequest, opts ...http.CallOption) (rsp *ClassroomSet, err error)
	// SaveClassroom SaveClassroom creates or updates a classroom.
	SaveClassroom(ctx context.Context, req *SaveClassroomRequest, opts ...http.CallOption) (rsp *Classroom, err error)
}

type ClassroomServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewClassroomServiceHTTPClient(client *http.Client) ClassroomServiceHTTPClient {
	return &ClassroomServiceHTTPClientImpl{client}
}

// DeleteClassroom DeleteClassroom hard-deletes a classroom by ID.
func (c *ClassroomServiceHTTPClientImpl) DeleteClassroom(ctx context.Context, in *DeleteClassroomRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/classrooms/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClassroomServiceDeleteClassroom),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetClassroom GetClassroom returns a single classroom by ID.
func (c *ClassroomServiceHTTPClientImpl) GetClassroom(ctx context.Context, in *GetClassroomRequest, opts ...http.CallOption) (*Classroom, error) {
	var out Classroom
	pattern := "/v1/classrooms/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClassroomServiceGetClassroom),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListClassrooms ListClassrooms returns a page of classrooms.
func (c *ClassroomServiceHTTPClientImpl) ListClassrooms(ctx context.Context, in *ListClassroomsRequest, opts ...http.CallOption) (*ClassroomSet, error) {
	var out ClassroomSet
	pattern := "/v1/classrooms"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationClassroomServiceListClassrooms),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveClassroom SaveClassroom creates or updates a classroom.
func (c *ClassroomServiceHTTPClientImpl) SaveClassroom(ctx context.Context, in *SaveClassroomRequest, opts ...http.CallOption) (*Classroom, error) {
	var out Classroom
	pattern := "/v1/classrooms"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("classroom"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationClassroomServiceSaveClassroom),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Classroom, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
