// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/course_scheduling/classroom/classroom.proto

package classroomv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassroomService_SaveClassroom_FullMethodName   = "/v1.course_scheduling.ClassroomService/SaveClassroom"
	ClassroomService_DeleteClassroom_FullMethodName = "/v1.course_scheduling.ClassroomService/DeleteClassroom"
	ClassroomService_GetClassroom_FullMethodName    = "/v1.course_scheduling.ClassroomService/GetClassroom"
	ClassroomService_ListClassrooms_FullMethodName  = "/v1.course_scheduling.ClassroomService/ListClassrooms"
)

// ClassroomServiceClient is the client API for ClassroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClassroomService owns the classroom aggregate.
type ClassroomServiceClient interface {
	// SaveClassroom creates or updates a classroom.
	SaveClassroom(ctx context.Context, in *SaveClassroomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteClassroom hard-deletes a classroom by ID.
	DeleteClassroom(ctx context.Context, in *DeleteClassroomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClassroom returns a single classroom by ID.
	GetClassroom(ctx context.Context, in *GetClassroomRequest, opts ...grpc.CallOption) (*Classroom, error)
	// ListClassrooms returns a page of classrooms.
	ListClassrooms(ctx context.Context, in *ListClassroomsRequest, opts ...grpc.CallOption) (*ClassroomSet, error)
}

type classroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassroomServiceClient(cc grpc.ClientConnInterface) ClassroomServiceClient {
	return &classroomServiceClient{cc}
}

func (c *classroomServiceClient) SaveClassroom(ctx context.Context, in *SaveClassroomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClassroomService_SaveClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteClassroom(ctx context.Context, in *DeleteClassroomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClassroomService_DeleteClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) GetClassroom(ctx context.Context, in *GetClassroomRequest, opts ...grpc.CallOption) (*Classroom, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Classroom)
	err := c.cc.Invoke(ctx, ClassroomService_GetClassroom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) ListClassrooms(ctx context.Context, in *ListClassroomsRequest, opts ...grpc.CallOption) (*ClassroomSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassroomSet)
	err := c.cc.Invoke(ctx, ClassroomService_ListClassrooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassroomServiceServer is the server API for ClassroomService service.
// All implementations must embed UnimplementedClassroomServiceServer
// for forward compatibility.
//
// ClassroomService owns the classroom aggregate.
type ClassroomServiceServer interface {
	// SaveClassroom creates or updates a classroom.
	SaveClassroom(context.Context, *SaveClassroomRequest) (*emptypb.Empty, error)
	// DeleteClassroom hard-deletes a classroom by ID.
	DeleteClassroom(context.Context, *DeleteClassroomRequest) (*emptypb.Empty, error)
	// GetClassroom returns a single classroom by ID.
	GetClassroom(context.Context, *GetClassroomRequest) (*Classroom, error)
	// ListClassrooms returns a page of classrooms.
	ListClassrooms(context.Context, *ListClassroomsRequest) (*ClassroomSet, error)
	mustEmbedUnimplementedClassroomServiceServer()
}

// UnimplementedClassroomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassroomServiceServer struct{}

func (UnimplementedClassroomServiceServer) SaveClassroom(context.Context, *SaveClassroomRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteClassroom(context.Context, *DeleteClassroomRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) GetClassroom(context.Context, *GetClassroomRequest) (*Classroom, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) ListClassrooms(context.Context, *ListClassroomsRequest) (*ClassroomSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClassrooms not implemented")
}
func (UnimplementedClassroomServiceServer) mustEmbedUnimplementedClassroomServiceServer() {}
func (UnimplementedClassroomServiceServer) testEmbeddedByValue()                          {}

// UnsafeClassroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassroomServiceServer will
// result in compilation errors.
type UnsafeClassroomServiceServer interface {
	mustEmbedUnimplementedClassroomServiceServer()
}

func RegisterClassroomServiceServer(s grpc.ServiceRegistrar, srv ClassroomServiceServer) {
	// If the following call panics, it indicates UnimplementedClassroomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassroomService_ServiceDesc, srv)
}

func _ClassroomService_SaveClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).SaveClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_SaveClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).SaveClassroom(ctx, req.(*SaveClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_DeleteClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, req.(*DeleteClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_GetClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_GetClassroom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetClassroom(ctx, req.(*GetClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_ListClassrooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClassroomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).ListClassrooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassroomService_ListClassrooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).ListClassrooms(ctx, req.(*ListClassroomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassroomService_ServiceDesc is the grpc.ServiceDesc for ClassroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.course_scheduling.ClassroomService",
	HandlerType: (*ClassroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveClassroom",
			Handler:    _ClassroomService_SaveClassroom_Handler,
		},
		{
			MethodName: "DeleteClassroom",
			Handler:    _ClassroomService_DeleteClassroom_Handler,
		},
		{
			MethodName: "GetClassroom",
			Handler:    _ClassroomService_GetClassroom_Handler,
		},
		{
			MethodName: "ListClassrooms",
			Handler:    _ClassroomService_ListClassrooms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/course_scheduling/classroom/classroom.proto",
}
