// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/classroom/classroom.proto

package classroomv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClassroomStatus represents the operational state of a classroom.
type ClassroomStatus int32

const (
	ClassroomStatus_CLASSROOM_STATUS_UNSPECIFIED       ClassroomStatus = 0
	ClassroomStatus_CLASSROOM_STATUS_AVAILABLE         ClassroomStatus = 1
	ClassroomStatus_CLASSROOM_STATUS_UNDER_MAINTENANCE ClassroomStatus = 2
	ClassroomStatus_CLASSROOM_STATUS_DECOMMISSIONED    ClassroomStatus = 3
)

// Enum value maps for ClassroomStatus.
var (
	ClassroomStatus_name = map[int32]string{
		0: "CLASSROOM_STATUS_UNSPECIFIED",
		1: "CLASSROOM_STATUS_AVAILABLE",
		2: "CLASSROOM_STATUS_UNDER_MAINTENANCE",
		3: "CLASSROOM_STATUS_DECOMMISSIONED",
	}
	ClassroomStatus_value = map[string]int32{
		"CLASSROOM_STATUS_UNSPECIFIED":       0,
		"CLASSROOM_STATUS_AVAILABLE":         1,
		"CLASSROOM_STATUS_UNDER_MAINTENANCE": 2,
		"CLASSROOM_STATUS_DECOMMISSIONED":    3,
	}
)

func (x ClassroomStatus) Enum() *ClassroomStatus {
	p := new(ClassroomStatus)
	*p = x
	return p
}

func (x ClassroomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClassroomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_classroom_classroom_proto_enumTypes[0].Descriptor()
}

func (ClassroomStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_classroom_classroom_proto_enumTypes[0]
}

func (x ClassroomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClassroomStatus.Descriptor instead.
func (ClassroomStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{0}
}

// Location identifies the physical position of a classroom.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Building name or identifier.
	Building string `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	// Floor number.
	Floor int32 `protobuf:"varint,2,opt,name=floor,proto3" json:"floor,omitempty"`
	// Room number or name.
	Room          string `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *Location) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Location) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

// Classroom represents a physical teaching room.
//
// The aggregate carries no timestamps, so neither does this message.
type Classroom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Physical location.
	Location *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// Total seat capacity.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Currently allocated seats.
	Allocated int32 `protobuf:"varint,4,opt,name=allocated,proto3" json:"allocated,omitempty"`
	// Operational status.
	Status        ClassroomStatus `protobuf:"varint,5,opt,name=status,proto3,enum=v1.course_scheduling.ClassroomStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Classroom) Reset() {
	*x = Classroom{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Classroom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classroom) ProtoMessage() {}

func (x *Classroom) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classroom.ProtoReflect.Descriptor instead.
func (*Classroom) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{1}
}

func (x *Classroom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Classroom) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Classroom) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Classroom) GetAllocated() int32 {
	if x != nil {
		return x.Allocated
	}
	return 0
}

func (x *Classroom) GetStatus() ClassroomStatus {
	if x != nil {
		return x.Status
	}
	return ClassroomStatus_CLASSROOM_STATUS_UNSPECIFIED
}

type ClassroomSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classrooms    []*Classroom           `protobuf:"bytes,1,rep,name=classrooms,proto3" json:"classrooms,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassroomSet) Reset() {
	*x = ClassroomSet{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassroomSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassroomSet) ProtoMessage() {}

func (x *ClassroomSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassroomSet.ProtoReflect.Descriptor instead.
func (*ClassroomSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{2}
}

func (x *ClassroomSet) GetClassrooms() []*Classroom {
	if x != nil {
		return x.Classrooms
	}
	return nil
}

func (x *ClassroomSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SaveClassroomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classroom     *Classroom             `protobuf:"bytes,1,opt,name=classroom,proto3" json:"classroom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveClassroomRequest) Reset() {
	*x = SaveClassroomRequest{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveClassroomRequest) ProtoMessage() {}

func (x *SaveClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveClassroomRequest.ProtoReflect.Descriptor instead.
func (*SaveClassroomRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{3}
}

func (x *SaveClassroomRequest) GetClassroom() *Classroom {
	if x != nil {
		return x.Classroom
	}
	return nil
}

type GetClassroomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassroomRequest) Reset() {
	*x = GetClassroomRequest{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassroomRequest) ProtoMessage() {}

func (x *GetClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassroomRequest.ProtoReflect.Descriptor instead.
func (*GetClassroomRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{4}
}

func (x *GetClassroomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListClassroomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassroomsRequest) Reset() {
	*x = ListClassroomsRequest{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassroomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassroomsRequest) ProtoMessage() {}

func (x *ListClassroomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassroomsRequest.ProtoReflect.Descriptor instead.
func (*ListClassroomsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{5}
}

func (x *ListClassroomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClassroomsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListClassroomsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListClassroomsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type DeleteClassroomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassroomRequest) Reset() {
	*x = DeleteClassroomRequest{}
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassroomRequest) ProtoMessage() {}

func (x *DeleteClassroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_classroom_classroom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassroomRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassroomRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClassroomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_course_scheduling_classroom_classroom_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_classroom_classroom_proto_rawDesc = "" +
	"\n" +
	".v1/course_scheduling/classroom/classroom.proto\x12\x14v1.course_scheduling\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n" +
	"\bLocation\x12\x1a\n" +
	"\bbuilding\x18\x01 \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\x05R\x05floor\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\"\xd0\x01\n" +
	"\tClassroom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\blocation\x18\x02 \x01(\v2\x1e.v1.course_scheduling.LocationR\blocation\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1c\n" +
	"\tallocated\x18\x04 \x01(\x05R\tallocated\x12=\n" +
	"\x06status\x18\x05 \x01(\x0e2%.v1.course_scheduling.ClassroomStatusR\x06status\"w\n" +
	"\fClassroomSet\x12?\n" +
	"\n" +
	"classrooms\x18\x01 \x03(\v2\x1f.v1.course_scheduling.ClassroomR\n" +
	"classrooms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Z\n" +
	"\x14SaveClassroomRequest\x12B\n" +
	"\tclassroom\x18\x01 \x01(\v2\x1f.v1.course_scheduling.ClassroomB\x03\xe0A\x02R\tclassroom\"*\n" +
	"\x13GetClassroomRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x86\x01\n" +
	"\x15ListClassroomsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"-\n" +
	"\x16DeleteClassroomRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id*\xa0\x01\n" +
	"\x0fClassroomStatus\x12 \n" +
	"\x1cCLASSROOM_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCLASSROOM_STATUS_AVAILABLE\x10\x01\x12&\n" +
	"\"CLASSROOM_STATUS_UNDER_MAINTENANCE\x10\x02\x12#\n" +
	"\x1fCLASSROOM_STATUS_DECOMMISSIONED\x10\x032\xfd\x03\n" +
	"\x10ClassroomService\x12\x7f\n" +
	"\rSaveClassroom\x12*.v1.course_scheduling.SaveClassroomRequest\x1a\x1f.v1.course_scheduling.Classroom\"!\x82\xd3\xe4\x93\x02\x1b:\tclassroom\"\x0e/v1/classrooms\x12t\n" +
	"\x0fDeleteClassroom\x12,.v1.course_scheduling.DeleteClassroomRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/classrooms/{id}\x12w\n" +
	"\fGetClassroom\x12).v1.course_scheduling.GetClassroomRequest\x1a\x1f.v1.course_scheduling.Classroom\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/classrooms/{id}\x12y\n" +
	"\x0eListClassrooms\x12+.v1.course_scheduling.ListClassroomsRequest\x1a\".v1.course_scheduling.ClassroomSet\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/classroomsBn\n" +
	"%io.grpc.examples.course_scheduling.v1B\x0eClassroomProtoP\x01Z3cqrs/api/v1/course_scheduling/classroom;classroomv1b\x06proto3"

var (
	file_v1_course_scheduling_classroom_classroom_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_classroom_classroom_proto_rawDescData []byte
)

func file_v1_course_scheduling_classroom_classroom_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_classroom_classroom_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_classroom_classroom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_classroom_classroom_proto_rawDesc), len(file_v1_course_scheduling_classroom_classroom_proto_rawDesc)))
	})
	return file_v1_course_scheduling_classroom_classroom_proto_rawDescData
}

var file_v1_course_scheduling_classroom_classroom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_classroom_classroom_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_course_scheduling_classroom_classroom_proto_goTypes = []any{
	(ClassroomStatus)(0),           // 0: v1.course_scheduling.ClassroomStatus
	(*Location)(nil),               // 1: v1.course_scheduling.Location
	(*Classroom)(nil),              // 2: v1.course_scheduling.Classroom
	(*ClassroomSet)(nil),           // 3: v1.course_scheduling.ClassroomSet
	(*SaveClassroomRequest)(nil),   // 4: v1.course_scheduling.SaveClassroomRequest
	(*GetClassroomRequest)(nil),    // 5: v1.course_scheduling.GetClassroomRequest
	(*ListClassroomsRequest)(nil),  // 6: v1.course_scheduling.ListClassroomsRequest
	(*DeleteClassroomRequest)(nil), // 7: v1.course_scheduling.DeleteClassroomRequest
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_v1_course_scheduling_classroom_classroom_proto_depIdxs = []int32{
	1, // 0: v1.course_scheduling.Classroom.location:type_name -> v1.course_scheduling.Location
	0, // 1: v1.course_scheduling.Classroom.status:type_name -> v1.course_scheduling.ClassroomStatus
	2, // 2: v1.course_scheduling.ClassroomSet.classrooms:type_name -> v1.course_scheduling.Classroom
	2, // 3: v1.course_scheduling.SaveClassroomRequest.classroom:type_name -> v1.course_scheduling.Classroom
	4, // 4: v1.course_scheduling.ClassroomService.SaveClassroom:input_type -> v1.course_scheduling.SaveClassroomRequest
	7, // 5: v1.course_scheduling.ClassroomService.DeleteClassroom:input_type -> v1.course_scheduling.DeleteClassroomRequest
	5, // 6: v1.course_scheduling.ClassroomService.GetClassroom:input_type -> v1.course_scheduling.GetClassroomRequest
	6, // 7: v1.course_scheduling.ClassroomService.ListClassrooms:input_type -> v1.course_scheduling.ListClassroomsRequest
	2, // 8: v1.course_scheduling.ClassroomService.SaveClassroom:output_type -> v1.course_scheduling.Classroom
	8, // 9: v1.course_scheduling.ClassroomService.DeleteClassroom:output_type -> google.protobuf.Empty
	2, // 10: v1.course_scheduling.ClassroomService.GetClassroom:output_type -> v1.course_scheduling.Classroom
	3, // 11: v1.course_scheduling.ClassroomService.ListClassrooms:output_type -> v1.course_scheduling.ClassroomSet
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_classroom_classroom_proto_init() }
func file_v1_course_scheduling_classroom_classroom_proto_init() {
	if File_v1_course_scheduling_classroom_classroom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_classroom_classroom_proto_rawDesc), len(file_v1_course_scheduling_classroom_classroom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_classroom_classroom_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_classroom_classroom_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_classroom_classroom_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_classroom_classroom_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_classroom_classroom_proto = out.File
	file_v1_course_scheduling_classroom_classroom_proto_goTypes = nil
	file_v1_course_scheduling_classroom_classroom_proto_depIdxs = nil
}
