// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/course/course.proto

package coursev1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCourseServiceDeleteCourse = "/v1.course_scheduling.CourseService/DeleteCourse"
const OperationCourseServiceGetCourse = "/v1.course_scheduling.CourseService/GetCourse"
const OperationCourseServiceListCourses = "/v1.course_scheduling.CourseService/ListCourses"
const OperationCourseServiceListCoursesAvailableForClassroom = "/v1.course_scheduling.CourseService/ListCoursesAvailableForClassroom"
const OperationCourseServiceListCoursesAvailableForStudent = "/v1.course_scheduling.CourseService/ListCoursesAvailableForStudent"
const OperationCourseServiceListCoursesAvailableForTeacher = "/v1.course_scheduling.CourseService/ListCoursesAvailableForTeacher"
const OperationCourseServiceSaveCourse = "/v1.course_scheduling.CourseService/SaveCourse"

type CourseServiceHTTPServer interface {
	// DeleteCourse DeleteCourse hard-deletes a course by ID.
	DeleteCourse(context.Context, *DeleteCourseRequest) (*emptypb.Empty, error)
	// GetCourse GetCourse returns a single course by ID.
	GetCourse(context.Context, *GetCourseRequest) (*Course, error)
	// ListCourses ListCourses returns a page of courses.
	ListCourses(context.Context, *ListCoursesRequest) (*CourseSet, error)
	// ListCoursesAvailableForClassroom ListCoursesAvailableForClassroom returns courses that can fit in the given
	// classroom based on capacity and schedule.
	ListCoursesAvailableForClassroom(context.Context, *ListCoursesAvailableForClassroomRequest) (*CourseSet, error)
	// ListCoursesAvailableForStudent ListCoursesAvailableForStudent returns courses the student can enroll in.
	ListCoursesAvailableForStudent(context.Context, *ListCoursesAvailableForStudentRequest) (*CourseSet, error)
	// ListCoursesAvailableForTeacher ListCoursesAvailableForTeacher returns courses the teacher is qualified
	// and available to teach.
	ListCoursesAvailableForTeacher(context.Context, *ListCoursesAvailableForTeacherRequest) (*CourseSet, error)
	// SaveCourse SaveCourse creates or updates a course.
	SaveCourse(context.Context, *SaveCourseRequest) (*emptypb.Empty, error)
}

func RegisterCourseServiceHTTPServer(s *http.Server, srv CourseServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/courses", _CourseService_SaveCourse0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/courses/{id}", _CourseService_DeleteCourse0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/{id}", _CourseService_GetCourse0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses", _CourseService_ListCourses0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/available-for-classroom", _CourseService_ListCoursesAvailableForClassroom0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/available-for-student", _CourseService_ListCoursesAvailableForStudent0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/available-for-teacher", _CourseService_ListCoursesAvailableForTeacher0_HTTP_Handler(srv))
}

func _CourseService_SaveCourse0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveCourseRequest
		if err := ctx.Bind(&in.Course); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceSaveCourse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveCourse(ctx, req.(*SaveCourseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseService_DeleteCourse0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCourseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceDeleteCourse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCourse(ctx, req.(*DeleteCourseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseService_GetCourse0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceGetCourse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourse(ctx, req.(*GetCourseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Course)
		return ctx.Result(200, reply)
	}
}

func _CourseService_ListCourses0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCoursesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceListCourses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourses(ctx, req.(*ListCoursesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSet)
		return ctx.Result(200, reply)
	}
}

func _CourseService_ListCoursesAvailableForClassroom0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCoursesAvailableForClassroomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceListCoursesAvailableForClassroom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCoursesAvailableForClassroom(ctx, req.(*ListCoursesAvailableForClassroomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSet)
		return ctx.Result(200, reply)
	}
}

func _CourseService_ListCoursesAvailableForStudent0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCoursesAvailableForStudentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceListCoursesAvailableForStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCoursesAvailableForStudent(ctx, req.(*ListCoursesAvailableForStudentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSet)
		return ctx.Result(200, reply)
	}
}

func _CourseService_ListCoursesAvailableForTeacher0_HTTP_Handler(srv CourseServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCoursesAvailableForTeacherRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseServiceListCoursesAvailableForTeacher)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCoursesAvailableForTeacher(ctx, req.(*ListCoursesAvailableForTeacherRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSet)
		return ctx.Result(200, reply)
	}
}

type CourseServiceHTTPClient interface {
	// DeleteCourse DeleteCourse hard-deletes a course by ID.
	DeleteCourse(ctx context.Context, req *DeleteCourseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetCourse GetCourse returns a single course by ID.
	GetCourse(ctx context.Context, req *GetCourseRequest, opts ...http.CallOption) (rsp *Course, err error)
	// ListCourses ListCourses returns a page of courses.
	ListCourses(ctx context.Context, req *ListCoursesRequest, opts ...http.CallOption) (rsp *CourseSet, err error)
	// ListCoursesAvailableForClassroom ListCoursesAvailableForClassroom returns courses that can fit in the given
	// classroom based on capacity and schedule.
	ListCoursesAvailableForClassroom(ctx context.Context, req *ListCoursesAvailableForClassroomRequest, opts ...http.CallOption) (rsp *CourseSet, err error)
	// ListCoursesAvailableForStudent ListCoursesAvailableForStudent returns courses the student can enroll in.
	ListCoursesAvailableForStudent(ctx context.Context, req *ListCoursesAvailableForStudentRequest, opts ...http.CallOption) (rsp *CourseSet, err error)
	// ListCoursesAvailableForTeacher ListCoursesAvailableForTeacher returns courses the teacher is qualified
	// and available to teach.
	ListCoursesAvailableForTeacher(ctx context.Context, req *ListCoursesAvailableForTeacherRequest, opts ...http.CallOption) (rsp *CourseSet, err error)
	// SaveCourse SaveCourse creates or updates a course.
	SaveCourse(ctx context.Context, req *SaveCourseRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type CourseServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCourseServiceHTTPClient(client *http.Client) CourseServiceHTTPClient {
	return &CourseServiceHTTPClientImpl{client}
}

// DeleteCourse DeleteCourse hard-deletes a course by ID.
func (c *CourseServiceHTTPClientImpl) DeleteCourse(ctx context.Context, in *DeleteCourseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/courses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceDeleteCourse),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourse GetCourse returns a single course by ID.
func (c *CourseServiceHTTPClientImpl) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...http.CallOption) (*Course, error) {
	var out Course
	pattern := "/v1/courses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceGetCourse),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCourses ListCourses returns a page of courses.
func (c *CourseServiceHTTPClientImpl) ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...http.CallOption) (*CourseSet, error) {
	var out CourseSet
	pattern := "/v1/courses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceListCourses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCoursesAvailableForClassroom ListCoursesAvailableForClassroom returns courses that can fit in the given
// classroom based on capacity and schedule.
func (c *CourseServiceHTTPClientImpl) ListCoursesAvailableForClassroom(ctx context.Context, in *ListCoursesAvailableForClassroomRequest, opts ...http.CallOption) (*CourseSet, error) {
	var out CourseSet
	pattern := "/v1/courses/available-for-classroom"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceListCoursesAvailableForClassroom),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCoursesAvailableForStudent ListCoursesAvailableForStudent returns courses the student can enroll in.
func (c *CourseServiceHTTPClientImpl) ListCoursesAvailableForStudent(ctx context.Context, in *ListCoursesAvailableForStudentRequest, opts ...http.CallOption) (*CourseSet, error) {
	var out CourseSet
	pattern := "/v1/courses/available-for-student"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceListCoursesAvailableForStudent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCoursesAvailableForTeacher ListCoursesAvailableForTeacher returns courses the teacher is qualified
// and available to teach.
func (c *CourseServiceHTTPClientImpl) ListCoursesAvailableForTeacher(ctx context.Context, in *ListCoursesAvailableForTeacherRequest, opts ...http.CallOption) (*CourseSet, error) {
	var out CourseSet
	pattern := "/v1/courses/available-for-teacher"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseServiceListCoursesAvailableForTeacher),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveCourse SaveCourse creates or updates a course.
func (c *CourseServiceHTTPClientImpl) SaveCourse(ctx context.Context, in *SaveCourseRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/courses"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("course"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCourseServiceSaveCourse),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Course, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
