// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/course_slot_change/course_slot_change.proto

package courseslotchangev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeType describes the kind of course slot change.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_RESCHEDULE  ChangeType = 1
	ChangeType_CHANGE_TYPE_SUBSTITUTE  ChangeType = 2
	ChangeType_CHANGE_TYPE_RELOCATE    ChangeType = 3
	ChangeType_CHANGE_TYPE_COMPOSITE   ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_RESCHEDULE",
		2: "CHANGE_TYPE_SUBSTITUTE",
		3: "CHANGE_TYPE_RELOCATE",
		4: "CHANGE_TYPE_COMPOSITE",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_RESCHEDULE":  1,
		"CHANGE_TYPE_SUBSTITUTE":  2,
		"CHANGE_TYPE_RELOCATE":    3,
		"CHANGE_TYPE_COMPOSITE":   4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{0}
}

// OriginalPlan captures the original schedule before a slot change.
type OriginalPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original course slot ID.
	SlotId string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	// The scheduled date.
	Date *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	// The originally assigned teacher ID.
	TeacherId int64 `protobuf:"varint,3,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	// The originally assigned classroom ID.
	ClassroomId string `protobuf:"bytes,4,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	// Start time string (e.g. "16:00").
	StartTime string `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time string (e.g. "18:00").
	EndTime       string `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginalPlan) Reset() {
	*x = OriginalPlan{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalPlan) ProtoMessage() {}

func (x *OriginalPlan) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalPlan.ProtoReflect.Descriptor instead.
func (*OriginalPlan) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{0}
}

func (x *OriginalPlan) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *OriginalPlan) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *OriginalPlan) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *OriginalPlan) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

func (x *OriginalPlan) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *OriginalPlan) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// TargetPlan captures the new schedule after a slot change.
type TargetPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New start datetime.
	TargetStartAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=target_start_at,json=targetStartAt,proto3" json:"target_start_at,omitempty"`
	// New end datetime.
	TargetEndAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=target_end_at,json=targetEndAt,proto3" json:"target_end_at,omitempty"`
	// New teacher ID.
	TeacherId int64 `protobuf:"varint,3,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	// New classroom ID.
	ClassroomId   string `protobuf:"bytes,4,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetPlan) Reset() {
	*x = TargetPlan{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPlan) ProtoMessage() {}

func (x *TargetPlan) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPlan.ProtoReflect.Descriptor instead.
func (*TargetPlan) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{1}
}

func (x *TargetPlan) GetTargetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetStartAt
	}
	return nil
}

func (x *TargetPlan) GetTargetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetEndAt
	}
	return nil
}

func (x *TargetPlan) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *TargetPlan) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

// CourseSlotChange represents a temporary schedule modification.
type CourseSlotChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The course affected.
	CourseId string `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	// The teacher who requested the change.
	ApplicantId int64 `protobuf:"varint,3,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	// Type of change.
	ChangeType ChangeType `protobuf:"varint,4,opt,name=change_type,json=changeType,proto3,enum=v1.course_scheduling.ChangeType" json:"change_type,omitempty"`
	// The original schedule plan.
	OriginalPlan *OriginalPlan `protobuf:"bytes,5,opt,name=original_plan,json=originalPlan,proto3" json:"original_plan,omitempty"`
	// The target schedule plan.
	TargetPlan *TargetPlan `protobuf:"bytes,6,opt,name=target_plan,json=targetPlan,proto3" json:"target_plan,omitempty"`
	// Reason for the change.
	Reason string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSlotChange) Reset() {
	*x = CourseSlotChange{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSlotChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSlotChange) ProtoMessage() {}

func (x *CourseSlotChange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSlotChange.ProtoReflect.Descriptor instead.
func (*CourseSlotChange) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{2}
}

func (x *CourseSlotChange) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseSlotChange) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseSlotChange) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *CourseSlotChange) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *CourseSlotChange) GetOriginalPlan() *OriginalPlan {
	if x != nil {
		return x.OriginalPlan
	}
	return nil
}

func (x *CourseSlotChange) GetTargetPlan() *TargetPlan {
	if x != nil {
		return x.TargetPlan
	}
	return nil
}

func (x *CourseSlotChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CourseSlotChange) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CourseSlotChange) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CourseSlotChangeSet struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CourseSlotChanges []*CourseSlotChange    `protobuf:"bytes,1,rep,name=course_slot_changes,json=courseSlotChanges,proto3" json:"course_slot_changes,omitempty"`
	NextPageToken     string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CourseSlotChangeSet) Reset() {
	*x = CourseSlotChangeSet{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSlotChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSlotChangeSet) ProtoMessage() {}

func (x *CourseSlotChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSlotChangeSet.ProtoReflect.Descriptor instead.
func (*CourseSlotChangeSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{3}
}

func (x *CourseSlotChangeSet) GetCourseSlotChanges() []*CourseSlotChange {
	if x != nil {
		return x.CourseSlotChanges
	}
	return nil
}

func (x *CourseSlotChangeSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ChangeCourseSlotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CourseSlotChange *CourseSlotChange      `protobuf:"bytes,1,opt,name=course_slot_change,json=courseSlotChange,proto3" json:"course_slot_change,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeCourseSlotRequest) Reset() {
	*x = ChangeCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCourseSlotRequest) ProtoMessage() {}

func (x *ChangeCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*ChangeCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeCourseSlotRequest) GetCourseSlotChange() *CourseSlotChange {
	if x != nil {
		return x.CourseSlotChange
	}
	return nil
}

type GetCourseSlotChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseSlotChangeRequest) Reset() {
	*x = GetCourseSlotChangeRequest{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseSlotChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseSlotChangeRequest) ProtoMessage() {}

func (x *GetCourseSlotChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseSlotChangeRequest.ProtoReflect.Descriptor instead.
func (*GetCourseSlotChangeRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{5}
}

func (x *GetCourseSlotChangeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCourseSlotChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSlotChangesRequest) Reset() {
	*x = ListCourseSlotChangesRequest{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSlotChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSlotChangesRequest) ProtoMessage() {}

func (x *ListCourseSlotChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSlotChangesRequest.ProtoReflect.Descriptor instead.
func (*ListCourseSlotChangesRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{6}
}

func (x *ListCourseSlotChangesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCourseSlotChangesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCourseSlotChangesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCourseSlotChangesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListCourseSlotChangesByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSlotChangesByCourseIDRequest) Reset() {
	*x = ListCourseSlotChangesByCourseIDRequest{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSlotChangesByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSlotChangesByCourseIDRequest) ProtoMessage() {}

func (x *ListCourseSlotChangesByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSlotChangesByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*ListCourseSlotChangesByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{7}
}

func (x *ListCourseSlotChangesByCourseIDRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DeleteCourseSlotChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseSlotChangeRequest) Reset() {
	*x = DeleteCourseSlotChangeRequest{}
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseSlotChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseSlotChangeRequest) ProtoMessage() {}

func (x *DeleteCourseSlotChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseSlotChangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseSlotChangeRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCourseSlotChangeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_course_slot_change_course_slot_change_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDesc = "" +
	"\n" +
	"@v1/course_scheduling/course_slot_change/course_slot_change.proto\x12\x14v1.course_scheduling\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\fOriginalPlan\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x03 \x01(\x03R\tteacherId\x12!\n" +
	"\fclassroom_id\x18\x04 \x01(\tR\vclassroomId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\"\xd2\x01\n" +
	"\n" +
	"TargetPlan\x12B\n" +
	"\x0ftarget_start_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rtargetStartAt\x12>\n" +
	"\rtarget_end_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vtargetEndAt\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x03 \x01(\x03R\tteacherId\x12!\n" +
	"\fclassroom_id\x18\x04 \x01(\tR\vclassroomId\"\xbf\x03\n" +
	"\x10CourseSlotChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12!\n" +
	"\fapplicant_id\x18\x03 \x01(\x03R\vapplicantId\x12A\n" +
	"\vchange_type\x18\x04 \x01(\x0e2 .v1.course_scheduling.ChangeTypeR\n" +
	"changeType\x12G\n" +
	"\roriginal_plan\x18\x05 \x01(\v2\".v1.course_scheduling.OriginalPlanR\foriginalPlan\x12A\n" +
	"\vtarget_plan\x18\x06 \x01(\v2 .v1.course_scheduling.TargetPlanR\n" +
	"targetPlan\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x01\n" +
	"\x13CourseSlotChangeSet\x12V\n" +
	"\x13course_slot_changes\x18\x01 \x03(\v2&.v1.course_scheduling.CourseSlotChangeR\x11courseSlotChanges\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"t\n" +
	"\x17ChangeCourseSlotRequest\x12Y\n" +
	"\x12course_slot_change\x18\x01 \x01(\v2&.v1.course_scheduling.CourseSlotChangeB\x03\xe0A\x02R\x10courseSlotChange\"1\n" +
	"\x1aGetCourseSlotChangeRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x8d\x01\n" +
	"\x1cListCourseSlotChangesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"J\n" +
	"&ListCourseSlotChangesByCourseIDRequest\x12 \n" +
	"\tcourse_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bcourseId\"4\n" +
	"\x1dDeleteCourseSlotChangeRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\x96\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CHANGE_TYPE_RESCHEDULE\x10\x01\x12\x1a\n" +
	"\x16CHANGE_TYPE_SUBSTITUTE\x10\x02\x12\x18\n" +
	"\x14CHANGE_TYPE_RELOCATE\x10\x03\x12\x19\n" +
	"\x15CHANGE_TYPE_COMPOSITE\x10\x042\xb5\x06\n" +
	"\x17CourseSlotChangeService\x12\x9e\x01\n" +
	"\x10ChangeCourseSlot\x12-.v1.course_scheduling.ChangeCourseSlotRequest\x1a&.v1.course_scheduling.CourseSlotChange\"3\x82\xd3\xe4\x93\x02-:\x12course_slot_change\"\x17/v1/course-slot-changes\x12\x8b\x01\n" +
	"\x16DeleteCourseSlotChange\x123.v1.course_scheduling.DeleteCourseSlotChangeRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/course-slot-changes/{id}\x12\x95\x01\n" +
	"\x13GetCourseSlotChange\x120.v1.course_scheduling.GetCourseSlotChangeRequest\x1a&.v1.course_scheduling.CourseSlotChange\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/course-slot-changes/{id}\x12\x97\x01\n" +
	"\x15ListCourseSlotChanges\x122.v1.course_scheduling.ListCourseSlotChangesRequest\x1a).v1.course_scheduling.CourseSlotChangeSet\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/course-slot-changes\x12\xb8\x01\n" +
	"\x1fListCourseSlotChangesByCourseID\x12<.v1.course_scheduling.ListCourseSlotChangesByCourseIDRequest\x1a).v1.course_scheduling.CourseSlotChangeSet\",\x82\xd3\xe4\x93\x02&\x12$/v1/courses/{course_id}/slot-changesB\x85\x01\n" +
	"%io.grpc.examples.course_scheduling.v1B\x15CourseSlotChangeProtoP\x01ZCcqrs/api/v1/course_scheduling/course_slot_change;courseslotchangev1b\x06proto3"

var (
	file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescData []byte
)

func file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDesc), len(file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDesc)))
	})
	return file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDescData
}

var file_v1_course_scheduling_course_slot_change_course_slot_change_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_course_scheduling_course_slot_change_course_slot_change_proto_goTypes = []any{
	(ChangeType)(0),                                // 0: v1.course_scheduling.ChangeType
	(*OriginalPlan)(nil),                           // 1: v1.course_scheduling.OriginalPlan
	(*TargetPlan)(nil),                             // 2: v1.course_scheduling.TargetPlan
	(*CourseSlotChange)(nil),                       // 3: v1.course_scheduling.CourseSlotChange
	(*CourseSlotChangeSet)(nil),                    // 4: v1.course_scheduling.CourseSlotChangeSet
	(*ChangeCourseSlotRequest)(nil),                // 5: v1.course_scheduling.ChangeCourseSlotRequest
	(*GetCourseSlotChangeRequest)(nil),             // 6: v1.course_scheduling.GetCourseSlotChangeRequest
	(*ListCourseSlotChangesRequest)(nil),           // 7: v1.course_scheduling.ListCourseSlotChangesRequest
	(*ListCourseSlotChangesByCourseIDRequest)(nil), // 8: v1.course_scheduling.ListCourseSlotChangesByCourseIDRequest
	(*DeleteCourseSlotChangeRequest)(nil),          // 9: v1.course_scheduling.DeleteCourseSlotChangeRequest
	(*timestamppb.Timestamp)(nil),                  // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 11: google.protobuf.Empty
}
var file_v1_course_scheduling_course_slot_change_course_slot_change_proto_depIdxs = []int32{
	10, // 0: v1.course_scheduling.OriginalPlan.date:type_name -> google.protobuf.Timestamp
	10, // 1: v1.course_scheduling.TargetPlan.target_start_at:type_name -> google.protobuf.Timestamp
	10, // 2: v1.course_scheduling.TargetPlan.target_end_at:type_name -> google.protobuf.Timestamp
	0,  // 3: v1.course_scheduling.CourseSlotChange.change_type:type_name -> v1.course_scheduling.ChangeType
	1,  // 4: v1.course_scheduling.CourseSlotChange.original_plan:type_name -> v1.course_scheduling.OriginalPlan
	2,  // 5: v1.course_scheduling.CourseSlotChange.target_plan:type_name -> v1.course_scheduling.TargetPlan
	10, // 6: v1.course_scheduling.CourseSlotChange.created_at:type_name -> google.protobuf.Timestamp
	10, // 7: v1.course_scheduling.CourseSlotChange.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 8: v1.course_scheduling.CourseSlotChangeSet.course_slot_changes:type_name -> v1.course_scheduling.CourseSlotChange
	3,  // 9: v1.course_scheduling.ChangeCourseSlotRequest.course_slot_change:type_name -> v1.course_scheduling.CourseSlotChange
	5,  // 10: v1.course_scheduling.CourseSlotChangeService.ChangeCourseSlot:input_type -> v1.course_scheduling.ChangeCourseSlotRequest
	9,  // 11: v1.course_scheduling.CourseSlotChangeService.DeleteCourseSlotChange:input_type -> v1.course_scheduling.DeleteCourseSlotChangeRequest
	6,  // 12: v1.course_scheduling.CourseSlotChangeService.GetCourseSlotChange:input_type -> v1.course_scheduling.GetCourseSlotChangeRequest
	7,  // 13: v1.course_scheduling.CourseSlotChangeService.ListCourseSlotChanges:input_type -> v1.course_scheduling.ListCourseSlotChangesRequest
	8,  // 14: v1.course_scheduling.CourseSlotChangeService.ListCourseSlotChangesByCourseID:input_type -> v1.course_scheduling.ListCourseSlotChangesByCourseIDRequest
	3,  // 15: v1.course_scheduling.CourseSlotChangeService.ChangeCourseSlot:output_type -> v1.course_scheduling.CourseSlotChange
	11, // 16: v1.course_scheduling.CourseSlotChangeService.DeleteCourseSlotChange:output_type -> google.protobuf.Empty
	3,  // 17: v1.course_scheduling.CourseSlotChangeService.GetCourseSlotChange:output_type -> v1.course_scheduling.CourseSlotChange
	4,  // 18: v1.course_scheduling.CourseSlotChangeService.ListCourseSlotChanges:output_type -> v1.course_scheduling.CourseSlotChangeSet
	4,  // 19: v1.course_scheduling.CourseSlotChangeService.ListCourseSlotChangesByCourseID:output_type -> v1.course_scheduling.CourseSlotChangeSet
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_course_slot_change_course_slot_change_proto_init() }
func file_v1_course_scheduling_course_slot_change_course_slot_change_proto_init() {
	if File_v1_course_scheduling_course_slot_change_course_slot_change_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDesc), len(file_v1_course_scheduling_course_slot_change_course_slot_change_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_course_slot_change_course_slot_change_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_course_slot_change_course_slot_change_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_course_slot_change_course_slot_change_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_course_slot_change_course_slot_change_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_course_slot_change_course_slot_change_proto = out.File
	file_v1_course_scheduling_course_slot_change_course_slot_change_proto_goTypes = nil
	file_v1_course_scheduling_course_slot_change_course_slot_change_proto_depIdxs = nil
}
