// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/course_slot_change/course_slot_change.proto

package courseslotchangev1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCourseSlotChangeServiceChangeCourseSlot = "/v1.course_scheduling.CourseSlotChangeService/ChangeCourseSlot"
const OperationCourseSlotChangeServiceDeleteCourseSlotChange = "/v1.course_scheduling.CourseSlotChangeService/DeleteCourseSlotChange"
const OperationCourseSlotChangeServiceGetCourseSlotChange = "/v1.course_scheduling.CourseSlotChangeService/GetCourseSlotChange"
const OperationCourseSlotChangeServiceListCourseSlotChanges = "/v1.course_scheduling.CourseSlotChangeService/ListCourseSlotChanges"
const OperationCourseSlotChangeServiceListCourseSlotChangesByCourseID = "/v1.course_scheduling.CourseSlotChangeService/ListCourseSlotChangesByCourseID"

type CourseSlotChangeServiceHTTPServer interface {
	// ChangeCourseSlot ChangeCourseSlot creates a temporary schedule modification (reschedule,
	// substitute teacher, relocate room, or composite).
	ChangeCourseSlot(context.Context, *ChangeCourseSlotRequest) (*CourseSlotChange, error)
	// DeleteCourseSlotChange DeleteCourseSlotChange hard-deletes a slot change record by ID.
	DeleteCourseSlotChange(context.Context, *DeleteCourseSlotChangeRequest) (*emptypb.Empty, error)
	// GetCourseSlotChange GetCourseSlotChange returns a single slot change record by ID.
	GetCourseSlotChange(context.Context, *GetCourseSlotChangeRequest) (*CourseSlotChange, error)
	// ListCourseSlotChanges ListCourseSlotChanges returns a page of slot change records.
	ListCourseSlotChanges(context.Context, *ListCourseSlotChangesRequest) (*CourseSlotChangeSet, error)
	// ListCourseSlotChangesByCourseID ListCourseSlotChangesByCourseID returns all slot changes for a course.
	ListCourseSlotChangesByCourseID(context.Context, *ListCourseSlotChangesByCourseIDRequest) (*CourseSlotChangeSet, error)
}

func RegisterCourseSlotChangeServiceHTTPServer(s *http.Server, srv CourseSlotChangeServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/course-slot-changes", _CourseSlotChangeService_ChangeCourseSlot0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/course-slot-changes/{id}", _CourseSlotChangeService_DeleteCourseSlotChange0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/course-slot-changes/{id}", _CourseSlotChangeService_GetCourseSlotChange0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/course-slot-changes", _CourseSlotChangeService_ListCourseSlotChanges0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/{course_id}/slot-changes", _CourseSlotChangeService_ListCourseSlotChangesByCourseID0_HTTP_Handler(srv))
}

func _CourseSlotChangeService_ChangeCourseSlot0_HTTP_Handler(srv CourseSlotChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeCourseSlotRequest
		if err := ctx.Bind(&in.CourseSlotChange); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotChangeServiceChangeCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangeCourseSlot(ctx, req.(*ChangeCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotChange)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotChangeService_DeleteCourseSlotChange0_HTTP_Handler(srv CourseSlotChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCourseSlotChangeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotChangeServiceDeleteCourseSlotChange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCourseSlotChange(ctx, req.(*DeleteCourseSlotChangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotChangeService_GetCourseSlotChange0_HTTP_Handler(srv CourseSlotChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseSlotChangeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotChangeServiceGetCourseSlotChange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourseSlotChange(ctx, req.(*GetCourseSlotChangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotChange)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotChangeService_ListCourseSlotChanges0_HTTP_Handler(srv CourseSlotChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCourseSlotChangesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotChangeServiceListCourseSlotChanges)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourseSlotChanges(ctx, req.(*ListCourseSlotChangesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotChangeSet)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotChangeService_ListCourseSlotChangesByCourseID0_HTTP_Handler(srv CourseSlotChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCourseSlotChangesByCourseIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotChangeServiceListCourseSlotChangesByCourseID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourseSlotChangesByCourseID(ctx, req.(*ListCourseSlotChangesByCourseIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotChangeSet)
		return ctx.Result(200, reply)
	}
}

type CourseSlotChangeServiceHTTPClient interface {
	// ChangeCourseSlot ChangeCourseSlot creates a temporary schedule modification (reschedule,
	// substitute teacher, relocate room, or composite).
	ChangeCourseSlot(ctx context.Context, req *ChangeCourseSlotRequest, opts ...http.CallOption) (rsp *CourseSlotChange, err error)
	// DeleteCourseSlotChange DeleteCourseSlotChange hard-deletes a slot change record by ID.
	DeleteCourseSlotChange(ctx context.Context, req *DeleteCourseSlotChangeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetCourseSlotChange GetCourseSlotChange returns a single slot change record by ID.
	GetCourseSlotChange(ctx context.Context, req *GetCourseSlotChangeRequest, opts ...http.CallOption) (rsp *CourseSlotChange, err error)
	// ListCourseSlotChanges ListCourseSlotChanges returns a page of slot change records.
	ListCourseSlotChanges(ctx context.Context, req *ListCourseSlotChangesRequest, opts ...http.CallOption) (rsp *CourseSlotChangeSet, err error)
	// ListCourseSlotChangesByCourseID ListCourseSlotChangesByCourseID returns all slot changes for a course.
	ListCourseSlotChangesByCourseID(ctx context.Context, req *ListCourseSlotChangesByCourseIDRequest, opts ...http.CallOption) (rsp *CourseSlotChangeSet, err error)
}

type CourseSlotChangeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCourseSlotChangeServiceHTTPClient(client *http.Client) CourseSlotChangeServiceHTTPClient {
	return &CourseSlotChangeServiceHTTPClientImpl{client}
}

// ChangeCourseSlot ChangeCourseSlot creates a temporary schedule modification (reschedule,
// substitute teacher, relocate room, or composite).
func (c *CourseSlotChangeServiceHTTPClientImpl) ChangeCourseSlot(ctx context.Context, in *ChangeCourseSlotRequest, opts ...http.CallOption) (*CourseSlotChange, error) {
	var out CourseSlotChange
	pattern := "/v1/course-slot-changes"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("courseSlotChange"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCourseSlotChangeServiceChangeCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.CourseSlotChange, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCourseSlotChange DeleteCourseSlotChange hard-deletes a slot change record by ID.
func (c *CourseSlotChangeServiceHTTPClientImpl) DeleteCourseSlotChange(ctx context.Context, in *DeleteCourseSlotChangeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/course-slot-changes/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotChangeServiceDeleteCourseSlotChange),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourseSlotChange GetCourseSlotChange returns a single slot change record by ID.
func (c *CourseSlotChangeServiceHTTPClientImpl) GetCourseSlotChange(ctx context.Context, in *GetCourseSlotChangeRequest, opts ...http.CallOption) (*CourseSlotChange, error) {
	var out CourseSlotChange
	pattern := "/v1/course-slot-changes/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotChangeServiceGetCourseSlotChange),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCourseSlotChanges ListCourseSlotChanges returns a page of slot change records.
func (c *CourseSlotChangeServiceHTTPClientImpl) ListCourseSlotChanges(ctx context.Context, in *ListCourseSlotChangesRequest, opts ...http.CallOption) (*CourseSlotChangeSet, error) {
	var out CourseSlotChangeSet
	pattern := "/v1/course-slot-changes"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotChangeServiceListCourseSlotChanges),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCourseSlotChangesByCourseID ListCourseSlotChangesByCourseID returns all slot changes for a course.
func (c *CourseSlotChangeServiceHTTPClientImpl) ListCourseSlotChangesByCourseID(ctx context.Context, in *ListCourseSlotChangesByCourseIDRequest, opts ...http.CallOption) (*CourseSlotChangeSet, error) {
	var out CourseSlotChangeSet
	pattern := "/v1/courses/{course_id}/slot-changes"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotChangeServiceListCourseSlotChangesByCourseID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
