// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/course_scheduling/makeup/makeup.proto

package makeupv1

import (
	context "context"
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MakeupService_RecordMakeup_FullMethodName           = "/v1.course_scheduling.MakeupService/RecordMakeup"
	MakeupService_DeleteMakeup_FullMethodName           = "/v1.course_scheduling.MakeupService/DeleteMakeup"
	MakeupService_GetMakeup_FullMethodName              = "/v1.course_scheduling.MakeupService/GetMakeup"
	MakeupService_ListMakeups_FullMethodName            = "/v1.course_scheduling.MakeupService/ListMakeups"
	MakeupService_ListMakeupsByStudentID_FullMethodName = "/v1.course_scheduling.MakeupService/ListMakeupsByStudentID"
	MakeupService_ListMakeupsByCourseID_FullMethodName  = "/v1.course_scheduling.MakeupService/ListMakeupsByCourseID"
)

// MakeupServiceClient is the client API for MakeupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MakeupService owns the makeup booking aggregate.
type MakeupServiceClient interface {
	// RecordMakeup books a makeup class for a student.
	RecordMakeup(ctx context.Context, in *RecordMakeupRequest, opts ...grpc.CallOption) (*StudentMakeup, error)
	// DeleteMakeup hard-deletes a makeup booking by ID.
	DeleteMakeup(ctx context.Context, in *DeleteMakeupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetMakeup returns a single makeup booking by ID.
	GetMakeup(ctx context.Context, in *GetMakeupRequest, opts ...grpc.CallOption) (*StudentMakeup, error)
	// ListMakeups returns a page of makeup bookings.
	ListMakeups(ctx context.Context, in *ListMakeupsRequest, opts ...grpc.CallOption) (*StudentMakeupSet, error)
	// ListMakeupsByStudentID returns courses the student has makeup classes for.
	ListMakeupsByStudentID(ctx context.Context, in *ListMakeupsByStudentIDRequest, opts ...grpc.CallOption) (*course.CourseSet, error)
	// ListMakeupsByCourseID returns students who have makeup classes for a course.
	ListMakeupsByCourseID(ctx context.Context, in *ListMakeupsByCourseIDRequest, opts ...grpc.CallOption) (*student.StudentSet, error)
}

type makeupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMakeupServiceClient(cc grpc.ClientConnInterface) MakeupServiceClient {
	return &makeupServiceClient{cc}
}

func (c *makeupServiceClient) RecordMakeup(ctx context.Context, in *RecordMakeupRequest, opts ...grpc.CallOption) (*StudentMakeup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMakeup)
	err := c.cc.Invoke(ctx, MakeupService_RecordMakeup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makeupServiceClient) DeleteMakeup(ctx context.Context, in *DeleteMakeupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MakeupService_DeleteMakeup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makeupServiceClient) GetMakeup(ctx context.Context, in *GetMakeupRequest, opts ...grpc.CallOption) (*StudentMakeup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMakeup)
	err := c.cc.Invoke(ctx, MakeupService_GetMakeup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makeupServiceClient) ListMakeups(ctx context.Context, in *ListMakeupsRequest, opts ...grpc.CallOption) (*StudentMakeupSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentMakeupSet)
	err := c.cc.Invoke(ctx, MakeupService_ListMakeups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makeupServiceClient) ListMakeupsByStudentID(ctx context.Context, in *ListMakeupsByStudentIDRequest, opts ...grpc.CallOption) (*course.CourseSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(course.CourseSet)
	err := c.cc.Invoke(ctx, MakeupService_ListMakeupsByStudentID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makeupServiceClient) ListMakeupsByCourseID(ctx context.Context, in *ListMakeupsByCourseIDRequest, opts ...grpc.CallOption) (*student.StudentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(student.StudentSet)
	err := c.cc.Invoke(ctx, MakeupService_ListMakeupsByCourseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakeupServiceServer is the server API for MakeupService service.
// All implementations must embed UnimplementedMakeupServiceServer
// for forward compatibility.
//
// MakeupService owns the makeup booking aggregate.
type MakeupServiceServer interface {
	// RecordMakeup books a makeup class for a student.
	RecordMakeup(context.Context, *RecordMakeupRequest) (*StudentMakeup, error)
	// DeleteMakeup hard-deletes a makeup booking by ID.
	DeleteMakeup(context.Context, *DeleteMakeupRequest) (*emptypb.Empty, error)
	// GetMakeup returns a single makeup booking by ID.
	GetMakeup(context.Context, *GetMakeupRequest) (*StudentMakeup, error)
	// ListMakeups returns a page of makeup bookings.
	ListMakeups(context.Context, *ListMakeupsRequest) (*StudentMakeupSet, error)
	// ListMakeupsByStudentID returns courses the student has makeup classes for.
	ListMakeupsByStudentID(context.Context, *ListMakeupsByStudentIDRequest) (*course.CourseSet, error)
	// ListMakeupsByCourseID returns students who have makeup classes for a course.
	ListMakeupsByCourseID(context.Context, *ListMakeupsByCourseIDRequest) (*student.StudentSet, error)
	mustEmbedUnimplementedMakeupServiceServer()
}

// UnimplementedMakeupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMakeupServiceServer struct{}

func (UnimplementedMakeupServiceServer) RecordMakeup(context.Context, *RecordMakeupRequest) (*StudentMakeup, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMakeup not implemented")
}
func (UnimplementedMakeupServiceServer) DeleteMakeup(context.Context, *DeleteMakeupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMakeup not implemented")
}
func (UnimplementedMakeupServiceServer) GetMakeup(context.Context, *GetMakeupRequest) (*StudentMakeup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMakeup not implemented")
}
func (UnimplementedMakeupServiceServer) ListMakeups(context.Context, *ListMakeupsRequest) (*StudentMakeupSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMakeups not implemented")
}
func (UnimplementedMakeupServiceServer) ListMakeupsByStudentID(context.Context, *ListMakeupsByStudentIDRequest) (*course.CourseSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMakeupsByStudentID not implemented")
}
func (UnimplementedMakeupServiceServer) ListMakeupsByCourseID(context.Context, *ListMakeupsByCourseIDRequest) (*student.StudentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMakeupsByCourseID not implemented")
}
func (UnimplementedMakeupServiceServer) mustEmbedUnimplementedMakeupServiceServer() {}
func (UnimplementedMakeupServiceServer) testEmbeddedByValue()                       {}

// UnsafeMakeupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MakeupServiceServer will
// result in compilation errors.
type UnsafeMakeupServiceServer interface {
	mustEmbedUnimplementedMakeupServiceServer()
}

func RegisterMakeupServiceServer(s grpc.ServiceRegistrar, srv MakeupServiceServer) {
	// If the following call panics, it indicates UnimplementedMakeupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MakeupService_ServiceDesc, srv)
}

func _MakeupService_RecordMakeup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMakeupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).RecordMakeup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_RecordMakeup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).RecordMakeup(ctx, req.(*RecordMakeupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakeupService_DeleteMakeup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMakeupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).DeleteMakeup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_DeleteMakeup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).DeleteMakeup(ctx, req.(*DeleteMakeupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakeupService_GetMakeup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMakeupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).GetMakeup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_GetMakeup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).GetMakeup(ctx, req.(*GetMakeupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakeupService_ListMakeups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMakeupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).ListMakeups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_ListMakeups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).ListMakeups(ctx, req.(*ListMakeupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakeupService_ListMakeupsByStudentID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMakeupsByStudentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).ListMakeupsByStudentID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_ListMakeupsByStudentID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).ListMakeupsByStudentID(ctx, req.(*ListMakeupsByStudentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakeupService_ListMakeupsByCourseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMakeupsByCourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeupServiceServer).ListMakeupsByCourseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MakeupService_ListMakeupsByCourseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeupServiceServer).ListMakeupsByCourseID(ctx, req.(*ListMakeupsByCourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MakeupService_ServiceDesc is the grpc.ServiceDesc for MakeupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MakeupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.course_scheduling.MakeupService",
	HandlerType: (*MakeupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMakeup",
			Handler:    _MakeupService_RecordMakeup_Handler,
		},
		{
			MethodName: "DeleteMakeup",
			Handler:    _MakeupService_DeleteMakeup_Handler,
		},
		{
			MethodName: "GetMakeup",
			Handler:    _MakeupService_GetMakeup_Handler,
		},
		{
			MethodName: "ListMakeups",
			Handler:    _MakeupService_ListMakeups_Handler,
		},
		{
			MethodName: "ListMakeupsByStudentID",
			Handler:    _MakeupService_ListMakeupsByStudentID_Handler,
		},
		{
			MethodName: "ListMakeupsByCourseID",
			Handler:    _MakeupService_ListMakeupsByCourseID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/course_scheduling/makeup/makeup.proto",
}
