// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/makeup/makeup.proto

package makeupv1

import (
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MakeupStatus represents the state of a makeup class booking.
type MakeupStatus int32

const (
	MakeupStatus_MAKEUP_STATUS_UNSPECIFIED MakeupStatus = 0
	MakeupStatus_MAKEUP_STATUS_BOOKED      MakeupStatus = 1
	MakeupStatus_MAKEUP_STATUS_COMPLETED   MakeupStatus = 2
	MakeupStatus_MAKEUP_STATUS_CANCELLED   MakeupStatus = 3
)

// Enum value maps for MakeupStatus.
var (
	MakeupStatus_name = map[int32]string{
		0: "MAKEUP_STATUS_UNSPECIFIED",
		1: "MAKEUP_STATUS_BOOKED",
		2: "MAKEUP_STATUS_COMPLETED",
		3: "MAKEUP_STATUS_CANCELLED",
	}
	MakeupStatus_value = map[string]int32{
		"MAKEUP_STATUS_UNSPECIFIED": 0,
		"MAKEUP_STATUS_BOOKED":      1,
		"MAKEUP_STATUS_COMPLETED":   2,
		"MAKEUP_STATUS_CANCELLED":   3,
	}
)

func (x MakeupStatus) Enum() *MakeupStatus {
	p := new(MakeupStatus)
	*p = x
	return p
}

func (x MakeupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MakeupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_makeup_makeup_proto_enumTypes[0].Descriptor()
}

func (MakeupStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_makeup_makeup_proto_enumTypes[0]
}

func (x MakeupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MakeupStatus.Descriptor instead.
func (MakeupStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{0}
}

// StudentMakeup represents a booked makeup class for a student.
type StudentMakeup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The student taking the makeup.
	StudentId int64 `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// The course.
	CourseId string `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	// The slot that was missed.
	OriginalSlotId string `protobuf:"bytes,4,opt,name=original_slot_id,json=originalSlotId,proto3" json:"original_slot_id,omitempty"`
	// The date that was missed.
	OriginalDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=original_date,json=originalDate,proto3" json:"original_date,omitempty"`
	// The slot for the makeup session.
	TargetSlotId string `protobuf:"bytes,6,opt,name=target_slot_id,json=targetSlotId,proto3" json:"target_slot_id,omitempty"`
	// The date of the makeup session.
	TargetDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	// Hours of makeup instruction.
	MakeupHours int32 `protobuf:"varint,8,opt,name=makeup_hours,json=makeupHours,proto3" json:"makeup_hours,omitempty"`
	// Booking status.
	Status MakeupStatus `protobuf:"varint,9,opt,name=status,proto3,enum=v1.course_scheduling.MakeupStatus" json:"status,omitempty"`
	// Completion time (if completed).
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentMakeup) Reset() {
	*x = StudentMakeup{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMakeup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMakeup) ProtoMessage() {}

func (x *StudentMakeup) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMakeup.ProtoReflect.Descriptor instead.
func (*StudentMakeup) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{0}
}

func (x *StudentMakeup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentMakeup) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *StudentMakeup) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *StudentMakeup) GetOriginalSlotId() string {
	if x != nil {
		return x.OriginalSlotId
	}
	return ""
}

func (x *StudentMakeup) GetOriginalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginalDate
	}
	return nil
}

func (x *StudentMakeup) GetTargetSlotId() string {
	if x != nil {
		return x.TargetSlotId
	}
	return ""
}

func (x *StudentMakeup) GetTargetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetDate
	}
	return nil
}

func (x *StudentMakeup) GetMakeupHours() int32 {
	if x != nil {
		return x.MakeupHours
	}
	return 0
}

func (x *StudentMakeup) GetStatus() MakeupStatus {
	if x != nil {
		return x.Status
	}
	return MakeupStatus_MAKEUP_STATUS_UNSPECIFIED
}

func (x *StudentMakeup) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *StudentMakeup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StudentMakeup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StudentMakeupSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Makeups       []*StudentMakeup       `protobuf:"bytes,1,rep,name=makeups,proto3" json:"makeups,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentMakeupSet) Reset() {
	*x = StudentMakeupSet{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentMakeupSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentMakeupSet) ProtoMessage() {}

func (x *StudentMakeupSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentMakeupSet.ProtoReflect.Descriptor instead.
func (*StudentMakeupSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{1}
}

func (x *StudentMakeupSet) GetMakeups() []*StudentMakeup {
	if x != nil {
		return x.Makeups
	}
	return nil
}

func (x *StudentMakeupSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RecordMakeupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Makeup        *StudentMakeup         `protobuf:"bytes,1,opt,name=makeup,proto3" json:"makeup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMakeupRequest) Reset() {
	*x = RecordMakeupRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMakeupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMakeupRequest) ProtoMessage() {}

func (x *RecordMakeupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMakeupRequest.ProtoReflect.Descriptor instead.
func (*RecordMakeupRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{2}
}

func (x *RecordMakeupRequest) GetMakeup() *StudentMakeup {
	if x != nil {
		return x.Makeup
	}
	return nil
}

type GetMakeupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMakeupRequest) Reset() {
	*x = GetMakeupRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMakeupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakeupRequest) ProtoMessage() {}

func (x *GetMakeupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakeupRequest.ProtoReflect.Descriptor instead.
func (*GetMakeupRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{3}
}

func (x *GetMakeupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMakeupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMakeupsRequest) Reset() {
	*x = ListMakeupsRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMakeupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMakeupsRequest) ProtoMessage() {}

func (x *ListMakeupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMakeupsRequest.ProtoReflect.Descriptor instead.
func (*ListMakeupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{4}
}

func (x *ListMakeupsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMakeupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMakeupsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListMakeupsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListMakeupsByStudentIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMakeupsByStudentIDRequest) Reset() {
	*x = ListMakeupsByStudentIDRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMakeupsByStudentIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMakeupsByStudentIDRequest) ProtoMessage() {}

func (x *ListMakeupsByStudentIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMakeupsByStudentIDRequest.ProtoReflect.Descriptor instead.
func (*ListMakeupsByStudentIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{5}
}

func (x *ListMakeupsByStudentIDRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type ListMakeupsByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMakeupsByCourseIDRequest) Reset() {
	*x = ListMakeupsByCourseIDRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMakeupsByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMakeupsByCourseIDRequest) ProtoMessage() {}

func (x *ListMakeupsByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMakeupsByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*ListMakeupsByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{6}
}

func (x *ListMakeupsByCourseIDRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DeleteMakeupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMakeupRequest) Reset() {
	*x = DeleteMakeupRequest{}
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMakeupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMakeupRequest) ProtoMessage() {}

func (x *DeleteMakeupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_makeup_makeup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMakeupRequest.ProtoReflect.Descriptor instead.
func (*DeleteMakeupRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMakeupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_makeup_makeup_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_makeup_makeup_proto_rawDesc = "" +
	"\n" +
	"(v1/course_scheduling/makeup/makeup.proto\x12\x14v1.course_scheduling\x1a(v1/course_scheduling/course/course.proto\x1a*v1/course_scheduling/student/student.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x04\n" +
	"\rStudentMakeup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12(\n" +
	"\x10original_slot_id\x18\x04 \x01(\tR\x0eoriginalSlotId\x12?\n" +
	"\roriginal_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\foriginalDate\x12$\n" +
	"\x0etarget_slot_id\x18\x06 \x01(\tR\ftargetSlotId\x12;\n" +
	"\vtarget_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"targetDate\x12!\n" +
	"\fmakeup_hours\x18\b \x01(\x05R\vmakeupHours\x12:\n" +
	"\x06status\x18\t \x01(\x0e2\".v1.course_scheduling.MakeupStatusR\x06status\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"y\n" +
	"\x10StudentMakeupSet\x12=\n" +
	"\amakeups\x18\x01 \x03(\v2#.v1.course_scheduling.StudentMakeupR\amakeups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"W\n" +
	"\x13RecordMakeupRequest\x12@\n" +
	"\x06makeup\x18\x01 \x01(\v2#.v1.course_scheduling.StudentMakeupB\x03\xe0A\x02R\x06makeup\"'\n" +
	"\x10GetMakeupRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x83\x01\n" +
	"\x12ListMakeupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"C\n" +
	"\x1dListMakeupsByStudentIDRequest\x12\"\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\tstudentId\"@\n" +
	"\x1cListMakeupsByCourseIDRequest\x12 \n" +
	"\tcourse_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bcourseId\"*\n" +
	"\x13DeleteMakeupRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\x81\x01\n" +
	"\fMakeupStatus\x12\x1d\n" +
	"\x19MAKEUP_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MAKEUP_STATUS_BOOKED\x10\x01\x12\x1b\n" +
	"\x17MAKEUP_STATUS_COMPLETED\x10\x02\x12\x1b\n" +
	"\x17MAKEUP_STATUS_CANCELLED\x10\x032\x98\x06\n" +
	"\rMakeupService\x12{\n" +
	"\fRecordMakeup\x12).v1.course_scheduling.RecordMakeupRequest\x1a#.v1.course_scheduling.StudentMakeup\"\x1b\x82\xd3\xe4\x93\x02\x15:\x06makeup\"\v/v1/makeups\x12k\n" +
	"\fDeleteMakeup\x12).v1.course_scheduling.DeleteMakeupRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/makeups/{id}\x12r\n" +
	"\tGetMakeup\x12&.v1.course_scheduling.GetMakeupRequest\x1a#.v1.course_scheduling.StudentMakeup\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/makeups/{id}\x12t\n" +
	"\vListMakeups\x12(.v1.course_scheduling.ListMakeupsRequest\x1a&.v1.course_scheduling.StudentMakeupSet\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/makeups\x12\x99\x01\n" +
	"\x16ListMakeupsByStudentID\x123.v1.course_scheduling.ListMakeupsByStudentIDRequest\x1a\x1f.v1.course_scheduling.CourseSet\")\x82\xd3\xe4\x93\x02#\x12!/v1/students/{student_id}/makeups\x12\x96\x01\n" +
	"\x15ListMakeupsByCourseID\x122.v1.course_scheduling.ListMakeupsByCourseIDRequest\x1a .v1.course_scheduling.StudentSet\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/courses/{course_id}/makeupsBe\n" +
	"%io.grpc.examples.course_scheduling.v1B\vMakeupProtoP\x01Z-cqrs/api/v1/course_scheduling/makeup;makeupv1b\x06proto3"

var (
	file_v1_course_scheduling_makeup_makeup_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_makeup_makeup_proto_rawDescData []byte
)

func file_v1_course_scheduling_makeup_makeup_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_makeup_makeup_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_makeup_makeup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_makeup_makeup_proto_rawDesc), len(file_v1_course_scheduling_makeup_makeup_proto_rawDesc)))
	})
	return file_v1_course_scheduling_makeup_makeup_proto_rawDescData
}

var file_v1_course_scheduling_makeup_makeup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_makeup_makeup_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_course_scheduling_makeup_makeup_proto_goTypes = []any{
	(MakeupStatus)(0),                     // 0: v1.course_scheduling.MakeupStatus
	(*StudentMakeup)(nil),                 // 1: v1.course_scheduling.StudentMakeup
	(*StudentMakeupSet)(nil),              // 2: v1.course_scheduling.StudentMakeupSet
	(*RecordMakeupRequest)(nil),           // 3: v1.course_scheduling.RecordMakeupRequest
	(*GetMakeupRequest)(nil),              // 4: v1.course_scheduling.GetMakeupRequest
	(*ListMakeupsRequest)(nil),            // 5: v1.course_scheduling.ListMakeupsRequest
	(*ListMakeupsByStudentIDRequest)(nil), // 6: v1.course_scheduling.ListMakeupsByStudentIDRequest
	(*ListMakeupsByCourseIDRequest)(nil),  // 7: v1.course_scheduling.ListMakeupsByCourseIDRequest
	(*DeleteMakeupRequest)(nil),           // 8: v1.course_scheduling.DeleteMakeupRequest
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
	(*course.CourseSet)(nil),              // 11: v1.course_scheduling.CourseSet
	(*student.StudentSet)(nil),            // 12: v1.course_scheduling.StudentSet
}
var file_v1_course_scheduling_makeup_makeup_proto_depIdxs = []int32{
	9,  // 0: v1.course_scheduling.StudentMakeup.original_date:type_name -> google.protobuf.Timestamp
	9,  // 1: v1.course_scheduling.StudentMakeup.target_date:type_name -> google.protobuf.Timestamp
	0,  // 2: v1.course_scheduling.StudentMakeup.status:type_name -> v1.course_scheduling.MakeupStatus
	9,  // 3: v1.course_scheduling.StudentMakeup.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 4: v1.course_scheduling.StudentMakeup.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: v1.course_scheduling.StudentMakeup.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: v1.course_scheduling.StudentMakeupSet.makeups:type_name -> v1.course_scheduling.StudentMakeup
	1,  // 7: v1.course_scheduling.RecordMakeupRequest.makeup:type_name -> v1.course_scheduling.StudentMakeup
	3,  // 8: v1.course_scheduling.MakeupService.RecordMakeup:input_type -> v1.course_scheduling.RecordMakeupRequest
	8,  // 9: v1.course_scheduling.MakeupService.DeleteMakeup:input_type -> v1.course_scheduling.DeleteMakeupRequest
	4,  // 10: v1.course_scheduling.MakeupService.GetMakeup:input_type -> v1.course_scheduling.GetMakeupRequest
	5,  // 11: v1.course_scheduling.MakeupService.ListMakeups:input_type -> v1.course_scheduling.ListMakeupsRequest
	6,  // 12: v1.course_scheduling.MakeupService.ListMakeupsByStudentID:input_type -> v1.course_scheduling.ListMakeupsByStudentIDRequest
	7,  // 13: v1.course_scheduling.MakeupService.ListMakeupsByCourseID:input_type -> v1.course_scheduling.ListMakeupsByCourseIDRequest
	1,  // 14: v1.course_scheduling.MakeupService.RecordMakeup:output_type -> v1.course_scheduling.StudentMakeup
	10, // 15: v1.course_scheduling.MakeupService.DeleteMakeup:output_type -> google.protobuf.Empty
	1,  // 16: v1.course_scheduling.MakeupService.GetMakeup:output_type -> v1.course_scheduling.StudentMakeup
	2,  // 17: v1.course_scheduling.MakeupService.ListMakeups:output_type -> v1.course_scheduling.StudentMakeupSet
	11, // 18: v1.course_scheduling.MakeupService.ListMakeupsByStudentID:output_type -> v1.course_scheduling.CourseSet
	12, // 19: v1.course_scheduling.MakeupService.ListMakeupsByCourseID:output_type -> v1.course_scheduling.StudentSet
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_makeup_makeup_proto_init() }
func file_v1_course_scheduling_makeup_makeup_proto_init() {
	if File_v1_course_scheduling_makeup_makeup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_makeup_makeup_proto_rawDesc), len(file_v1_course_scheduling_makeup_makeup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_makeup_makeup_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_makeup_makeup_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_makeup_makeup_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_makeup_makeup_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_makeup_makeup_proto = out.File
	file_v1_course_scheduling_makeup_makeup_proto_goTypes = nil
	file_v1_course_scheduling_makeup_makeup_proto_depIdxs = nil
}
