// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/makeup/makeup.proto

package makeupv1

import (
	context "context"
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationMakeupServiceDeleteMakeup = "/v1.course_scheduling.MakeupService/DeleteMakeup"
const OperationMakeupServiceGetMakeup = "/v1.course_scheduling.MakeupService/GetMakeup"
const OperationMakeupServiceListMakeups = "/v1.course_scheduling.MakeupService/ListMakeups"
const OperationMakeupServiceListMakeupsByCourseID = "/v1.course_scheduling.MakeupService/ListMakeupsByCourseID"
const OperationMakeupServiceListMakeupsByStudentID = "/v1.course_scheduling.MakeupService/ListMakeupsByStudentID"
const OperationMakeupServiceRecordMakeup = "/v1.course_scheduling.MakeupService/RecordMakeup"

type MakeupServiceHTTPServer interface {
	// DeleteMakeup DeleteMakeup hard-deletes a makeup booking by ID.
	DeleteMakeup(context.Context, *DeleteMakeupRequest) (*emptypb.Empty, error)
	// GetMakeup GetMakeup returns a single makeup booking by ID.
	GetMakeup(context.Context, *GetMakeupRequest) (*StudentMakeup, error)
	// ListMakeups ListMakeups returns a page of makeup bookings.
	ListMakeups(context.Context, *ListMakeupsRequest) (*StudentMakeupSet, error)
	// ListMakeupsByCourseID ListMakeupsByCourseID returns students who have makeup classes for a course.
	ListMakeupsByCourseID(context.Context, *ListMakeupsByCourseIDRequest) (*student.StudentSet, error)
	// ListMakeupsByStudentID ListMakeupsByStudentID returns courses the student has makeup classes for.
	ListMakeupsByStudentID(context.Context, *ListMakeupsByStudentIDRequest) (*course.CourseSet, error)
	// RecordMakeup RecordMakeup books a makeup class for a student.
	RecordMakeup(context.Context, *RecordMakeupRequest) (*StudentMakeup, error)
}

func RegisterMakeupServiceHTTPServer(s *http.Server, srv MakeupServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/makeups", _MakeupService_RecordMakeup0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/makeups/{id}", _MakeupService_DeleteMakeup0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/makeups/{id}", _MakeupService_GetMakeup0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/makeups", _MakeupService_ListMakeups0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/students/{student_id}/makeups", _MakeupService_ListMakeupsByStudentID0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/{course_id}/makeups", _MakeupService_ListMakeupsByCourseID0_HTTP_Handler(srv))
}

func _MakeupService_RecordMakeup0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecordMakeupRequest
		if err := ctx.Bind(&in.Makeup); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceRecordMakeup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordMakeup(ctx, req.(*RecordMakeupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentMakeup)
		return ctx.Result(200, reply)
	}
}

func _MakeupService_DeleteMakeup0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMakeupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceDeleteMakeup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMakeup(ctx, req.(*DeleteMakeupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _MakeupService_GetMakeup0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMakeupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceGetMakeup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMakeup(ctx, req.(*GetMakeupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentMakeup)
		return ctx.Result(200, reply)
	}
}

func _MakeupService_ListMakeups0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMakeupsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceListMakeups)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMakeups(ctx, req.(*ListMakeupsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentMakeupSet)
		return ctx.Result(200, reply)
	}
}

func _MakeupService_ListMakeupsByStudentID0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMakeupsByStudentIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceListMakeupsByStudentID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMakeupsByStudentID(ctx, req.(*ListMakeupsByStudentIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*course.CourseSet)
		return ctx.Result(200, reply)
	}
}

func _MakeupService_ListMakeupsByCourseID0_HTTP_Handler(srv MakeupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMakeupsByCourseIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMakeupServiceListMakeupsByCourseID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMakeupsByCourseID(ctx, req.(*ListMakeupsByCourseIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*student.StudentSet)
		return ctx.Result(200, reply)
	}
}

type MakeupServiceHTTPClient interface {
	// DeleteMakeup DeleteMakeup hard-deletes a makeup booking by ID.
	DeleteMakeup(ctx context.Context, req *DeleteMakeupRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetMakeup GetMakeup returns a single makeup booking by ID.
	GetMakeup(ctx context.Context, req *GetMakeupRequest, opts ...http.CallOption) (rsp *StudentMakeup, err error)
	// ListMakeups ListMakeups returns a page of makeup bookings.
	ListMakeups(ctx context.Context, req *ListMakeupsRequest, opts ...http.CallOption) (rsp *StudentMakeupSet, err error)
	// ListMakeupsByCourseID ListMakeupsByCourseID returns students who have makeup classes for a course.
	ListMakeupsByCourseID(ctx context.Context, req *ListMakeupsByCourseIDRequest, opts ...http.CallOption) (rsp *student.StudentSet, err error)
	// ListMakeupsByStudentID ListMakeupsByStudentID returns courses the student has makeup classes for.
	ListMakeupsByStudentID(ctx context.Context, req *ListMakeupsByStudentIDRequest, opts ...http.CallOption) (rsp *course.CourseSet, err error)
	// RecordMakeup RecordMakeup books a makeup class for a student.
	RecordMakeup(ctx context.Context, req *RecordMakeupRequest, opts ...http.CallOption) (rsp *StudentMakeup, err error)
}

type MakeupServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMakeupServiceHTTPClient(client *http.Client) MakeupServiceHTTPClient {
	return &MakeupServiceHTTPClientImpl{client}
}

// DeleteMakeup DeleteMakeup hard-deletes a makeup booking by ID.
func (c *MakeupServiceHTTPClientImpl) DeleteMakeup(ctx context.Context, in *DeleteMakeupRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/makeups/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMakeupServiceDeleteMakeup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMakeup GetMakeup returns a single makeup booking by ID.
func (c *MakeupServiceHTTPClientImpl) GetMakeup(ctx context.Context, in *GetMakeupRequest, opts ...http.CallOption) (*StudentMakeup, error) {
	var out StudentMakeup
	pattern := "/v1/makeups/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMakeupServiceGetMakeup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMakeups ListMakeups returns a page of makeup bookings.
func (c *MakeupServiceHTTPClientImpl) ListMakeups(ctx context.Context, in *ListMakeupsRequest, opts ...http.CallOption) (*StudentMakeupSet, error) {
	var out StudentMakeupSet
	pattern := "/v1/makeups"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMakeupServiceListMakeups),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMakeupsByCourseID ListMakeupsByCourseID returns students who have makeup classes for a course.
func (c *MakeupServiceHTTPClientImpl) ListMakeupsByCourseID(ctx context.Context, in *ListMakeupsByCourseIDRequest, opts ...http.CallOption) (*student.StudentSet, error) {
	var out student.StudentSet
	pattern := "/v1/courses/{course_id}/makeups"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMakeupServiceListMakeupsByCourseID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMakeupsByStudentID ListMakeupsByStudentID returns courses the student has makeup classes for.
func (c *MakeupServiceHTTPClientImpl) ListMakeupsByStudentID(ctx context.Context, in *ListMakeupsByStudentIDRequest, opts ...http.CallOption) (*course.CourseSet, error) {
	var out course.CourseSet
	pattern := "/v1/students/{student_id}/makeups"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMakeupServiceListMakeupsByStudentID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RecordMakeup RecordMakeup books a makeup class for a student.
func (c *MakeupServiceHTTPClientImpl) RecordMakeup(ctx context.Context, in *RecordMakeupRequest, opts ...http.CallOption) (*StudentMakeup, error) {
	var out StudentMakeup
	pattern := "/v1/makeups"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("makeup"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMakeupServiceRecordMakeup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Makeup, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
