// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/qualification/qualification.proto

package qualificationv1

import (
	context "context"
	course_type "cqrs/api/v1/course_scheduling/course_type"
	teacher "cqrs/api/v1/course_scheduling/teacher"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationQualificationServiceCheckTeacherQualifiedForCourse = "/v1.course_scheduling.QualificationService/CheckTeacherQualifiedForCourse"
const OperationQualificationServiceDeleteQualification = "/v1.course_scheduling.QualificationService/DeleteQualification"
const OperationQualificationServiceGetQualification = "/v1.course_scheduling.QualificationService/GetQualification"
const OperationQualificationServiceListQualifications = "/v1.course_scheduling.QualificationService/ListQualifications"
const OperationQualificationServiceListQualificationsByTeacherID = "/v1.course_scheduling.QualificationService/ListQualificationsByTeacherID"
const OperationQualificationServiceListTeachersQualifiedForCourseType = "/v1.course_scheduling.QualificationService/ListTeachersQualifiedForCourseType"
const OperationQualificationServiceQualify = "/v1.course_scheduling.QualificationService/Qualify"

type QualificationServiceHTTPServer interface {
	// CheckTeacherQualifiedForCourse CheckTeacherQualifiedForCourse checks whether a specific teacher holds a
	// qualification for the course type of a given course.
	CheckTeacherQualifiedForCourse(context.Context, *CheckTeacherQualifiedForCourseRequest) (*CheckTeacherQualifiedForCourseResponse, error)
	// DeleteQualification DeleteQualification hard-deletes a qualification record by ID.
	DeleteQualification(context.Context, *DeleteQualificationRequest) (*emptypb.Empty, error)
	// GetQualification GetQualification returns a single qualification record by ID.
	GetQualification(context.Context, *GetQualificationRequest) (*Qualification, error)
	// ListQualifications ListQualifications returns a page of qualification records.
	ListQualifications(context.Context, *ListQualificationsRequest) (*QualificationSet, error)
	// ListQualificationsByTeacherID ListQualificationsByTeacherID returns course types the teacher is qualified
	// to teach.
	ListQualificationsByTeacherID(context.Context, *ListQualificationsByTeacherIDRequest) (*course_type.CourseTypeSet, error)
	// ListTeachersQualifiedForCourseType ListTeachersQualifiedForCourseType returns teachers qualified for a
	// specific course type.
	ListTeachersQualifiedForCourseType(context.Context, *ListTeachersQualifiedForCourseTypeRequest) (*teacher.TeacherSet, error)
	// Qualify Qualify grants a teaching qualification to a teacher for a course type.
	Qualify(context.Context, *QualifyRequest) (*emptypb.Empty, error)
}

func RegisterQualificationServiceHTTPServer(s *http.Server, srv QualificationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/qualifications", _QualificationService_Qualify0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/qualifications/{id}", _QualificationService_DeleteQualification0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/qualifications/{id}", _QualificationService_GetQualification0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/qualifications", _QualificationService_ListQualifications0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/teachers/{teacher_id}/qualifications", _QualificationService_ListQualificationsByTeacherID0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/course-types/{course_type_id}/teachers", _QualificationService_ListTeachersQualifiedForCourseType0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/qualifications/check", _QualificationService_CheckTeacherQualifiedForCourse0_HTTP_Handler(srv))
}

func _QualificationService_Qualify0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QualifyRequest
		if err := ctx.Bind(&in.Qualification); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceQualify)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Qualify(ctx, req.(*QualifyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_DeleteQualification0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteQualificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceDeleteQualification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteQualification(ctx, req.(*DeleteQualificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_GetQualification0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetQualificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceGetQualification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetQualification(ctx, req.(*GetQualificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Qualification)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_ListQualifications0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListQualificationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceListQualifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListQualifications(ctx, req.(*ListQualificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QualificationSet)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_ListQualificationsByTeacherID0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListQualificationsByTeacherIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceListQualificationsByTeacherID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListQualificationsByTeacherID(ctx, req.(*ListQualificationsByTeacherIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*course_type.CourseTypeSet)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_ListTeachersQualifiedForCourseType0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTeachersQualifiedForCourseTypeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceListTeachersQualifiedForCourseType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTeachersQualifiedForCourseType(ctx, req.(*ListTeachersQualifiedForCourseTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*teacher.TeacherSet)
		return ctx.Result(200, reply)
	}
}

func _QualificationService_CheckTeacherQualifiedForCourse0_HTTP_Handler(srv QualificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckTeacherQualifiedForCourseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationServiceCheckTeacherQualifiedForCourse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckTeacherQualifiedForCourse(ctx, req.(*CheckTeacherQualifiedForCourseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckTeacherQualifiedForCourseResponse)
		return ctx.Result(200, reply)
	}
}

type QualificationServiceHTTPClient interface {
	// CheckTeacherQualifiedForCourse CheckTeacherQualifiedForCourse checks whether a specific teacher holds a
	// qualification for the course type of a given course.
	CheckTeacherQualifiedForCourse(ctx context.Context, req *CheckTeacherQualifiedForCourseRequest, opts ...http.CallOption) (rsp *CheckTeacherQualifiedForCourseResponse, err error)
	// DeleteQualification DeleteQualification hard-deletes a qualification record by ID.
	DeleteQualification(ctx context.Context, req *DeleteQualificationRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetQualification GetQualification returns a single qualification record by ID.
	GetQualification(ctx context.Context, req *GetQualificationRequest, opts ...http.CallOption) (rsp *Qualification, err error)
	// ListQualifications ListQualifications returns a page of qualification records.
	ListQualifications(ctx context.Context, req *ListQualificationsRequest, opts ...http.CallOption) (rsp *QualificationSet, err error)
	// ListQualificationsByTeacherID ListQualificationsByTeacherID returns course types the teacher is qualified
	// to teach.
	ListQualificationsByTeacherID(ctx context.Context, req *ListQualificationsByTeacherIDRequest, opts ...http.CallOption) (rsp *course_type.CourseTypeSet, err error)
	// ListTeachersQualifiedForCourseType ListTeachersQualifiedForCourseType returns teachers qualified for a
	// specific course type.
	ListTeachersQualifiedForCourseType(ctx context.Context, req *ListTeachersQualifiedForCourseTypeRequest, opts ...http.CallOption) (rsp *teacher.TeacherSet, err error)
	// Qualify Qualify grants a teaching qualification to a teacher for a course type.
	Qualify(ctx context.Context, req *QualifyRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type QualificationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewQualificationServiceHTTPClient(client *http.Client) QualificationServiceHTTPClient {
	return &QualificationServiceHTTPClientImpl{client}
}

// CheckTeacherQualifiedForCourse CheckTeacherQualifiedForCourse checks whether a specific teacher holds a
// qualification for the course type of a given course.
func (c *QualificationServiceHTTPClientImpl) CheckTeacherQualifiedForCourse(ctx context.Context, in *CheckTeacherQualifiedForCourseRequest, opts ...http.CallOption) (*CheckTeacherQualifiedForCourseResponse, error) {
	var out CheckTeacherQualifiedForCourseResponse
	pattern := "/v1/qualifications/check"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceCheckTeacherQualifiedForCourse),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteQualification DeleteQualification hard-deletes a qualification record by ID.
func (c *QualificationServiceHTTPClientImpl) DeleteQualification(ctx context.Context, in *DeleteQualificationRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/qualifications/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceDeleteQualification),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetQualification GetQualification returns a single qualification record by ID.
func (c *QualificationServiceHTTPClientImpl) GetQualification(ctx context.Context, in *GetQualificationRequest, opts ...http.CallOption) (*Qualification, error) {
	var out Qualification
	pattern := "/v1/qualifications/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceGetQualification),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListQualifications ListQualifications returns a page of qualification records.
func (c *QualificationServiceHTTPClientImpl) ListQualifications(ctx context.Context, in *ListQualificationsRequest, opts ...http.CallOption) (*QualificationSet, error) {
	var out QualificationSet
	pattern := "/v1/qualifications"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceListQualifications),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListQualificationsByTeacherID ListQualificationsByTeacherID returns course types the teacher is qualified
// to teach.
func (c *QualificationServiceHTTPClientImpl) ListQualificationsByTeacherID(ctx context.Context, in *ListQualificationsByTeacherIDRequest, opts ...http.CallOption) (*course_type.CourseTypeSet, error) {
	var out course_type.CourseTypeSet
	pattern := "/v1/teachers/{teacher_id}/qualifications"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceListQualificationsByTeacherID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTeachersQualifiedForCourseType ListTeachersQualifiedForCourseType returns teachers qualified for a
// specific course type.
func (c *QualificationServiceHTTPClientImpl) ListTeachersQualifiedForCourseType(ctx context.Context, in *ListTeachersQualifiedForCourseTypeRequest, opts ...http.CallOption) (*teacher.TeacherSet, error) {
	var out teacher.TeacherSet
	pattern := "/v1/course-types/{course_type_id}/teachers"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationQualificationServiceListTeachersQualifiedForCourseType),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Qualify Qualify grants a teaching qualification to a teacher for a course type.
func (c *QualificationServiceHTTPClientImpl) Qualify(ctx context.Context, in *QualifyRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/qualifications"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("qualification"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationQualificationServiceQualify),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Qualification, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
