// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/course_scheduling/qualification/qualification.proto

package qualificationv1

import (
	context "context"
	course_type "cqrs/api/v1/course_scheduling/course_type"
	teacher "cqrs/api/v1/course_scheduling/teacher"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QualificationService_Qualify_FullMethodName                            = "/v1.course_scheduling.QualificationService/Qualify"
	QualificationService_DeleteQualification_FullMethodName                = "/v1.course_scheduling.QualificationService/DeleteQualification"
	QualificationService_GetQualification_FullMethodName                   = "/v1.course_scheduling.QualificationService/GetQualification"
	QualificationService_ListQualifications_FullMethodName                 = "/v1.course_scheduling.QualificationService/ListQualifications"
	QualificationService_ListQualificationsByTeacherID_FullMethodName      = "/v1.course_scheduling.QualificationService/ListQualificationsByTeacherID"
	QualificationService_ListTeachersQualifiedForCourseType_FullMethodName = "/v1.course_scheduling.QualificationService/ListTeachersQualifiedForCourseType"
	QualificationService_CheckTeacherQualifiedForCourse_FullMethodName     = "/v1.course_scheduling.QualificationService/CheckTeacherQualifiedForCourse"
)

// QualificationServiceClient is the client API for QualificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QualificationService owns the qualification aggregate.
type QualificationServiceClient interface {
	// Qualify grants a teaching qualification to a teacher for a course type.
	Qualify(ctx context.Context, in *QualifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteQualification hard-deletes a qualification record by ID.
	DeleteQualification(ctx context.Context, in *DeleteQualificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetQualification returns a single qualification record by ID.
	GetQualification(ctx context.Context, in *GetQualificationRequest, opts ...grpc.CallOption) (*Qualification, error)
	// ListQualifications returns a page of qualification records.
	ListQualifications(ctx context.Context, in *ListQualificationsRequest, opts ...grpc.CallOption) (*QualificationSet, error)
	// ListQualificationsByTeacherID returns course types the teacher is qualified
	// to teach.
	ListQualificationsByTeacherID(ctx context.Context, in *ListQualificationsByTeacherIDRequest, opts ...grpc.CallOption) (*course_type.CourseTypeSet, error)
	// ListTeachersQualifiedForCourseType returns teachers qualified for a
	// specific course type.
	ListTeachersQualifiedForCourseType(ctx context.Context, in *ListTeachersQualifiedForCourseTypeRequest, opts ...grpc.CallOption) (*teacher.TeacherSet, error)
	// CheckTeacherQualifiedForCourse checks whether a specific teacher holds a
	// qualification for the course type of a given course.
	CheckTeacherQualifiedForCourse(ctx context.Context, in *CheckTeacherQualifiedForCourseRequest, opts ...grpc.CallOption) (*CheckTeacherQualifiedForCourseResponse, error)
}

type qualificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQualificationServiceClient(cc grpc.ClientConnInterface) QualificationServiceClient {
	return &qualificationServiceClient{cc}
}

func (c *qualificationServiceClient) Qualify(ctx context.Context, in *QualifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QualificationService_Qualify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) DeleteQualification(ctx context.Context, in *DeleteQualificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QualificationService_DeleteQualification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) GetQualification(ctx context.Context, in *GetQualificationRequest, opts ...grpc.CallOption) (*Qualification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Qualification)
	err := c.cc.Invoke(ctx, QualificationService_GetQualification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) ListQualifications(ctx context.Context, in *ListQualificationsRequest, opts ...grpc.CallOption) (*QualificationSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QualificationSet)
	err := c.cc.Invoke(ctx, QualificationService_ListQualifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) ListQualificationsByTeacherID(ctx context.Context, in *ListQualificationsByTeacherIDRequest, opts ...grpc.CallOption) (*course_type.CourseTypeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(course_type.CourseTypeSet)
	err := c.cc.Invoke(ctx, QualificationService_ListQualificationsByTeacherID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) ListTeachersQualifiedForCourseType(ctx context.Context, in *ListTeachersQualifiedForCourseTypeRequest, opts ...grpc.CallOption) (*teacher.TeacherSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(teacher.TeacherSet)
	err := c.cc.Invoke(ctx, QualificationService_ListTeachersQualifiedForCourseType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationServiceClient) CheckTeacherQualifiedForCourse(ctx context.Context, in *CheckTeacherQualifiedForCourseRequest, opts ...grpc.CallOption) (*CheckTeacherQualifiedForCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTeacherQualifiedForCourseResponse)
	err := c.cc.Invoke(ctx, QualificationService_CheckTeacherQualifiedForCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualificationServiceServer is the server API for QualificationService service.
// All implementations must embed UnimplementedQualificationServiceServer
// for forward compatibility.
//
// QualificationService owns the qualification aggregate.
type QualificationServiceServer interface {
	// Qualify grants a teaching qualification to a teacher for a course type.
	Qualify(context.Context, *QualifyRequest) (*emptypb.Empty, error)
	// DeleteQualification hard-deletes a qualification record by ID.
	DeleteQualification(context.Context, *DeleteQualificationRequest) (*emptypb.Empty, error)
	// GetQualification returns a single qualification record by ID.
	GetQualification(context.Context, *GetQualificationRequest) (*Qualification, error)
	// ListQualifications returns a page of qualification records.
	ListQualifications(context.Context, *ListQualificationsRequest) (*QualificationSet, error)
	// ListQualificationsByTeacherID returns course types the teacher is qualified
	// to teach.
	ListQualificationsByTeacherID(context.Context, *ListQualificationsByTeacherIDRequest) (*course_type.CourseTypeSet, error)
	// ListTeachersQualifiedForCourseType returns teachers qualified for a
	// specific course type.
	ListTeachersQualifiedForCourseType(context.Context, *ListTeachersQualifiedForCourseTypeRequest) (*teacher.TeacherSet, error)
	// CheckTeacherQualifiedForCourse checks whether a specific teacher holds a
	// qualification for the course type of a given course.
	CheckTeacherQualifiedForCourse(context.Context, *CheckTeacherQualifiedForCourseRequest) (*CheckTeacherQualifiedForCourseResponse, error)
	mustEmbedUnimplementedQualificationServiceServer()
}

// UnimplementedQualificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQualificationServiceServer struct{}

func (UnimplementedQualificationServiceServer) Qualify(context.Context, *QualifyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Qualify not implemented")
}
func (UnimplementedQualificationServiceServer) DeleteQualification(context.Context, *DeleteQualificationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQualification not implemented")
}
func (UnimplementedQualificationServiceServer) GetQualification(context.Context, *GetQualificationRequest) (*Qualification, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQualification not implemented")
}
func (UnimplementedQualificationServiceServer) ListQualifications(context.Context, *ListQualificationsRequest) (*QualificationSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQualifications not implemented")
}
func (UnimplementedQualificationServiceServer) ListQualificationsByTeacherID(context.Context, *ListQualificationsByTeacherIDRequest) (*course_type.CourseTypeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQualificationsByTeacherID not implemented")
}
func (UnimplementedQualificationServiceServer) ListTeachersQualifiedForCourseType(context.Context, *ListTeachersQualifiedForCourseTypeRequest) (*teacher.TeacherSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeachersQualifiedForCourseType not implemented")
}
func (UnimplementedQualificationServiceServer) CheckTeacherQualifiedForCourse(context.Context, *CheckTeacherQualifiedForCourseRequest) (*CheckTeacherQualifiedForCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTeacherQualifiedForCourse not implemented")
}
func (UnimplementedQualificationServiceServer) mustEmbedUnimplementedQualificationServiceServer() {}
func (UnimplementedQualificationServiceServer) testEmbeddedByValue()                              {}

// UnsafeQualificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualificationServiceServer will
// result in compilation errors.
type UnsafeQualificationServiceServer interface {
	mustEmbedUnimplementedQualificationServiceServer()
}

func RegisterQualificationServiceServer(s grpc.ServiceRegistrar, srv QualificationServiceServer) {
	// If the following call panics, it indicates UnimplementedQualificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QualificationService_ServiceDesc, srv)
}

func _QualificationService_Qualify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QualifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).Qualify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_Qualify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).Qualify(ctx, req.(*QualifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_DeleteQualification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQualificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).DeleteQualification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_DeleteQualification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).DeleteQualification(ctx, req.(*DeleteQualificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_GetQualification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQualificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).GetQualification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_GetQualification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).GetQualification(ctx, req.(*GetQualificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_ListQualifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQualificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).ListQualifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_ListQualifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).ListQualifications(ctx, req.(*ListQualificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_ListQualificationsByTeacherID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQualificationsByTeacherIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).ListQualificationsByTeacherID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_ListQualificationsByTeacherID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).ListQualificationsByTeacherID(ctx, req.(*ListQualificationsByTeacherIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_ListTeachersQualifiedForCourseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeachersQualifiedForCourseTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).ListTeachersQualifiedForCourseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_ListTeachersQualifiedForCourseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).ListTeachersQualifiedForCourseType(ctx, req.(*ListTeachersQualifiedForCourseTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualificationService_CheckTeacherQualifiedForCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTeacherQualifiedForCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServiceServer).CheckTeacherQualifiedForCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualificationService_CheckTeacherQualifiedForCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServiceServer).CheckTeacherQualifiedForCourse(ctx, req.(*CheckTeacherQualifiedForCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QualificationService_ServiceDesc is the grpc.ServiceDesc for QualificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QualificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.course_scheduling.QualificationService",
	HandlerType: (*QualificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Qualify",
			Handler:    _QualificationService_Qualify_Handler,
		},
		{
			MethodName: "DeleteQualification",
			Handler:    _QualificationService_DeleteQualification_Handler,
		},
		{
			MethodName: "GetQualification",
			Handler:    _QualificationService_GetQualification_Handler,
		},
		{
			MethodName: "ListQualifications",
			Handler:    _QualificationService_ListQualifications_Handler,
		},
		{
			MethodName: "ListQualificationsByTeacherID",
			Handler:    _QualificationService_ListQualificationsByTeacherID_Handler,
		},
		{
			MethodName: "ListTeachersQualifiedForCourseType",
			Handler:    _QualificationService_ListTeachersQualifiedForCourseType_Handler,
		},
		{
			MethodName: "CheckTeacherQualifiedForCourse",
			Handler:    _QualificationService_CheckTeacherQualifiedForCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/course_scheduling/qualification/qualification.proto",
}
