// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/qualification/qualification.proto

package qualificationv1

import (
	course_type "cqrs/api/v1/course_scheduling/course_type"
	teacher "cqrs/api/v1/course_scheduling/teacher"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QualificationStatus represents the state of a teaching qualification.
type QualificationStatus int32

const (
	QualificationStatus_QUALIFICATION_STATUS_UNSPECIFIED QualificationStatus = 0
	QualificationStatus_QUALIFICATION_STATUS_ACTIVE      QualificationStatus = 1
	QualificationStatus_QUALIFICATION_STATUS_REVOKED     QualificationStatus = 2
	QualificationStatus_QUALIFICATION_STATUS_EXPIRED     QualificationStatus = 3
)

// Enum value maps for QualificationStatus.
var (
	QualificationStatus_name = map[int32]string{
		0: "QUALIFICATION_STATUS_UNSPECIFIED",
		1: "QUALIFICATION_STATUS_ACTIVE",
		2: "QUALIFICATION_STATUS_REVOKED",
		3: "QUALIFICATION_STATUS_EXPIRED",
	}
	QualificationStatus_value = map[string]int32{
		"QUALIFICATION_STATUS_UNSPECIFIED": 0,
		"QUALIFICATION_STATUS_ACTIVE":      1,
		"QUALIFICATION_STATUS_REVOKED":     2,
		"QUALIFICATION_STATUS_EXPIRED":     3,
	}
)

func (x QualificationStatus) Enum() *QualificationStatus {
	p := new(QualificationStatus)
	*p = x
	return p
}

func (x QualificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_qualification_qualification_proto_enumTypes[0].Descriptor()
}

func (QualificationStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_qualification_qualification_proto_enumTypes[0]
}

func (x QualificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualificationStatus.Descriptor instead.
func (QualificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{0}
}

// Qualification records that a teacher is certified to teach a course type.
type Qualification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The qualified teacher ID.
	TeacherId int64 `protobuf:"varint,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	// The course type the teacher is qualified for.
	CourseTypeId string `protobuf:"bytes,3,opt,name=course_type_id,json=courseTypeId,proto3" json:"course_type_id,omitempty"`
	// Time the qualification was granted.
	CertifiedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=certified_at,json=certifiedAt,proto3" json:"certified_at,omitempty"`
	// Qualification status.
	Status QualificationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=v1.course_scheduling.QualificationStatus" json:"status,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Qualification) Reset() {
	*x = Qualification{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Qualification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Qualification) ProtoMessage() {}

func (x *Qualification) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Qualification.ProtoReflect.Descriptor instead.
func (*Qualification) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{0}
}

func (x *Qualification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Qualification) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *Qualification) GetCourseTypeId() string {
	if x != nil {
		return x.CourseTypeId
	}
	return ""
}

func (x *Qualification) GetCertifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertifiedAt
	}
	return nil
}

func (x *Qualification) GetStatus() QualificationStatus {
	if x != nil {
		return x.Status
	}
	return QualificationStatus_QUALIFICATION_STATUS_UNSPECIFIED
}

func (x *Qualification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QualificationSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Qualifications []*Qualification       `protobuf:"bytes,1,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	NextPageToken  string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QualificationSet) Reset() {
	*x = QualificationSet{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualificationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualificationSet) ProtoMessage() {}

func (x *QualificationSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualificationSet.ProtoReflect.Descriptor instead.
func (*QualificationSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{1}
}

func (x *QualificationSet) GetQualifications() []*Qualification {
	if x != nil {
		return x.Qualifications
	}
	return nil
}

func (x *QualificationSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type QualifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualification *Qualification         `protobuf:"bytes,1,opt,name=qualification,proto3" json:"qualification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifyRequest) Reset() {
	*x = QualifyRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifyRequest) ProtoMessage() {}

func (x *QualifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifyRequest.ProtoReflect.Descriptor instead.
func (*QualifyRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{2}
}

func (x *QualifyRequest) GetQualification() *Qualification {
	if x != nil {
		return x.Qualification
	}
	return nil
}

type GetQualificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualificationRequest) Reset() {
	*x = GetQualificationRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualificationRequest) ProtoMessage() {}

func (x *GetQualificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualificationRequest.ProtoReflect.Descriptor instead.
func (*GetQualificationRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{3}
}

func (x *GetQualificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListQualificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQualificationsRequest) Reset() {
	*x = ListQualificationsRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQualificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQualificationsRequest) ProtoMessage() {}

func (x *ListQualificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQualificationsRequest.ProtoReflect.Descriptor instead.
func (*ListQualificationsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{4}
}

func (x *ListQualificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListQualificationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListQualificationsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListQualificationsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListQualificationsByTeacherIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     int64                  `protobuf:"varint,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQualificationsByTeacherIDRequest) Reset() {
	*x = ListQualificationsByTeacherIDRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQualificationsByTeacherIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQualificationsByTeacherIDRequest) ProtoMessage() {}

func (x *ListQualificationsByTeacherIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQualificationsByTeacherIDRequest.ProtoReflect.Descriptor instead.
func (*ListQualificationsByTeacherIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{5}
}

func (x *ListQualificationsByTeacherIDRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

type ListTeachersQualifiedForCourseTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTypeId  string                 `protobuf:"bytes,1,opt,name=course_type_id,json=courseTypeId,proto3" json:"course_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersQualifiedForCourseTypeRequest) Reset() {
	*x = ListTeachersQualifiedForCourseTypeRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersQualifiedForCourseTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersQualifiedForCourseTypeRequest) ProtoMessage() {}

func (x *ListTeachersQualifiedForCourseTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersQualifiedForCourseTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersQualifiedForCourseTypeRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{6}
}

func (x *ListTeachersQualifiedForCourseTypeRequest) GetCourseTypeId() string {
	if x != nil {
		return x.CourseTypeId
	}
	return ""
}

type CheckTeacherQualifiedForCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     int64                  `protobuf:"varint,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeacherQualifiedForCourseRequest) Reset() {
	*x = CheckTeacherQualifiedForCourseRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeacherQualifiedForCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeacherQualifiedForCourseRequest) ProtoMessage() {}

func (x *CheckTeacherQualifiedForCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeacherQualifiedForCourseRequest.ProtoReflect.Descriptor instead.
func (*CheckTeacherQualifiedForCourseRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{7}
}

func (x *CheckTeacherQualifiedForCourseRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CheckTeacherQualifiedForCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CheckTeacherQualifiedForCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualified     bool                   `protobuf:"varint,1,opt,name=qualified,proto3" json:"qualified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTeacherQualifiedForCourseResponse) Reset() {
	*x = CheckTeacherQualifiedForCourseResponse{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTeacherQualifiedForCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeacherQualifiedForCourseResponse) ProtoMessage() {}

func (x *CheckTeacherQualifiedForCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeacherQualifiedForCourseResponse.ProtoReflect.Descriptor instead.
func (*CheckTeacherQualifiedForCourseResponse) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{8}
}

func (x *CheckTeacherQualifiedForCourseResponse) GetQualified() bool {
	if x != nil {
		return x.Qualified
	}
	return false
}

type DeleteQualificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQualificationRequest) Reset() {
	*x = DeleteQualificationRequest{}
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQualificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQualificationRequest) ProtoMessage() {}

func (x *DeleteQualificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_qualification_qualification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQualificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteQualificationRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteQualificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_qualification_qualification_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_qualification_qualification_proto_rawDesc = "" +
	"\n" +
	"6v1/course_scheduling/qualification/qualification.proto\x12\x14v1.course_scheduling\x1a2v1/course_scheduling/course_type/course_type.proto\x1a*v1/course_scheduling/teacher/teacher.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\rQualification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\x03R\tteacherId\x12$\n" +
	"\x0ecourse_type_id\x18\x03 \x01(\tR\fcourseTypeId\x12=\n" +
	"\fcertified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcertifiedAt\x12A\n" +
	"\x06status\x18\x05 \x01(\x0e2).v1.course_scheduling.QualificationStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x87\x01\n" +
	"\x10QualificationSet\x12K\n" +
	"\x0equalifications\x18\x01 \x03(\v2#.v1.course_scheduling.QualificationR\x0equalifications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"`\n" +
	"\x0eQualifyRequest\x12N\n" +
	"\rqualification\x18\x01 \x01(\v2#.v1.course_scheduling.QualificationB\x03\xe0A\x02R\rqualification\".\n" +
	"\x17GetQualificationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x8a\x01\n" +
	"\x19ListQualificationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"J\n" +
	"$ListQualificationsByTeacherIDRequest\x12\"\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\tteacherId\"V\n" +
	")ListTeachersQualifiedForCourseTypeRequest\x12)\n" +
	"\x0ecourse_type_id\x18\x01 \x01(\tB\x03\xe0A\x02R\fcourseTypeId\"m\n" +
	"%CheckTeacherQualifiedForCourseRequest\x12\"\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\tteacherId\x12 \n" +
	"\tcourse_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bcourseId\"F\n" +
	"&CheckTeacherQualifiedForCourseResponse\x12\x1c\n" +
	"\tqualified\x18\x01 \x01(\bR\tqualified\"1\n" +
	"\x1aDeleteQualificationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\xa0\x01\n" +
	"\x13QualificationStatus\x12$\n" +
	" QUALIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bQUALIFICATION_STATUS_ACTIVE\x10\x01\x12 \n" +
	"\x1cQUALIFICATION_STATUS_REVOKED\x10\x02\x12 \n" +
	"\x1cQUALIFICATION_STATUS_EXPIRED\x10\x032\xd6\b\n" +
	"\x14QualificationService\x12r\n" +
	"\aQualify\x12$.v1.course_scheduling.QualifyRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\rqualification\"\x12/v1/qualifications\x12\x80\x01\n" +
	"\x13DeleteQualification\x120.v1.course_scheduling.DeleteQualificationRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/qualifications/{id}\x12\x87\x01\n" +
	"\x10GetQualification\x12-.v1.course_scheduling.GetQualificationRequest\x1a#.v1.course_scheduling.Qualification\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/qualifications/{id}\x12\x89\x01\n" +
	"\x12ListQualifications\x12/.v1.course_scheduling.ListQualificationsRequest\x1a&.v1.course_scheduling.QualificationSet\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/qualifications\x12\xb2\x01\n" +
	"\x1dListQualificationsByTeacherID\x12:.v1.course_scheduling.ListQualificationsByTeacherIDRequest\x1a#.v1.course_scheduling.CourseTypeSet\"0\x82\xd3\xe4\x93\x02*\x12(/v1/teachers/{teacher_id}/qualifications\x12\xbb\x01\n" +
	"\"ListTeachersQualifiedForCourseType\x12?.v1.course_scheduling.ListTeachersQualifiedForCourseTypeRequest\x1a .v1.course_scheduling.TeacherSet\"2\x82\xd3\xe4\x93\x02,\x12*/v1/course-types/{course_type_id}/teachers\x12\xbd\x01\n" +
	"\x1eCheckTeacherQualifiedForCourse\x12;.v1.course_scheduling.CheckTeacherQualifiedForCourseRequest\x1a<.v1.course_scheduling.CheckTeacherQualifiedForCourseResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/qualifications/checkBz\n" +
	"%io.grpc.examples.course_scheduling.v1B\x12QualificationProtoP\x01Z;cqrs/api/v1/course_scheduling/qualification;qualificationv1b\x06proto3"

var (
	file_v1_course_scheduling_qualification_qualification_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_qualification_qualification_proto_rawDescData []byte
)

func file_v1_course_scheduling_qualification_qualification_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_qualification_qualification_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_qualification_qualification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_qualification_qualification_proto_rawDesc), len(file_v1_course_scheduling_qualification_qualification_proto_rawDesc)))
	})
	return file_v1_course_scheduling_qualification_qualification_proto_rawDescData
}

var file_v1_course_scheduling_qualification_qualification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_qualification_qualification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_course_scheduling_qualification_qualification_proto_goTypes = []any{
	(QualificationStatus)(0),                          // 0: v1.course_scheduling.QualificationStatus
	(*Qualification)(nil),                             // 1: v1.course_scheduling.Qualification
	(*QualificationSet)(nil),                          // 2: v1.course_scheduling.QualificationSet
	(*QualifyRequest)(nil),                            // 3: v1.course_scheduling.QualifyRequest
	(*GetQualificationRequest)(nil),                   // 4: v1.course_scheduling.GetQualificationRequest
	(*ListQualificationsRequest)(nil),                 // 5: v1.course_scheduling.ListQualificationsRequest
	(*ListQualificationsByTeacherIDRequest)(nil),      // 6: v1.course_scheduling.ListQualificationsByTeacherIDRequest
	(*ListTeachersQualifiedForCourseTypeRequest)(nil), // 7: v1.course_scheduling.ListTeachersQualifiedForCourseTypeRequest
	(*CheckTeacherQualifiedForCourseRequest)(nil),     // 8: v1.course_scheduling.CheckTeacherQualifiedForCourseRequest
	(*CheckTeacherQualifiedForCourseResponse)(nil),    // 9: v1.course_scheduling.CheckTeacherQualifiedForCourseResponse
	(*DeleteQualificationRequest)(nil),                // 10: v1.course_scheduling.DeleteQualificationRequest
	(*timestamppb.Timestamp)(nil),                     // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                             // 12: google.protobuf.Empty
	(*course_type.CourseTypeSet)(nil),                 // 13: v1.course_scheduling.CourseTypeSet
	(*teacher.TeacherSet)(nil),                        // 14: v1.course_scheduling.TeacherSet
}
var file_v1_course_scheduling_qualification_qualification_proto_depIdxs = []int32{
	11, // 0: v1.course_scheduling.Qualification.certified_at:type_name -> google.protobuf.Timestamp
	0,  // 1: v1.course_scheduling.Qualification.status:type_name -> v1.course_scheduling.QualificationStatus
	11, // 2: v1.course_scheduling.Qualification.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: v1.course_scheduling.QualificationSet.qualifications:type_name -> v1.course_scheduling.Qualification
	1,  // 4: v1.course_scheduling.QualifyRequest.qualification:type_name -> v1.course_scheduling.Qualification
	3,  // 5: v1.course_scheduling.QualificationService.Qualify:input_type -> v1.course_scheduling.QualifyRequest
	10, // 6: v1.course_scheduling.QualificationService.DeleteQualification:input_type -> v1.course_scheduling.DeleteQualificationRequest
	4,  // 7: v1.course_scheduling.QualificationService.GetQualification:input_type -> v1.course_scheduling.GetQualificationRequest
	5,  // 8: v1.course_scheduling.QualificationService.ListQualifications:input_type -> v1.course_scheduling.ListQualificationsRequest
	6,  // 9: v1.course_scheduling.QualificationService.ListQualificationsByTeacherID:input_type -> v1.course_scheduling.ListQualificationsByTeacherIDRequest
	7,  // 10: v1.course_scheduling.QualificationService.ListTeachersQualifiedForCourseType:input_type -> v1.course_scheduling.ListTeachersQualifiedForCourseTypeRequest
	8,  // 11: v1.course_scheduling.QualificationService.CheckTeacherQualifiedForCourse:input_type -> v1.course_scheduling.CheckTeacherQualifiedForCourseRequest
	12, // 12: v1.course_scheduling.QualificationService.Qualify:output_type -> google.protobuf.Empty
	12, // 13: v1.course_scheduling.QualificationService.DeleteQualification:output_type -> google.protobuf.Empty
	1,  // 14: v1.course_scheduling.QualificationService.GetQualification:output_type -> v1.course_scheduling.Qualification
	2,  // 15: v1.course_scheduling.QualificationService.ListQualifications:output_type -> v1.course_scheduling.QualificationSet
	13, // 16: v1.course_scheduling.QualificationService.ListQualificationsByTeacherID:output_type -> v1.course_scheduling.CourseTypeSet
	14, // 17: v1.course_scheduling.QualificationService.ListTeachersQualifiedForCourseType:output_type -> v1.course_scheduling.TeacherSet
	9,  // 18: v1.course_scheduling.QualificationService.CheckTeacherQualifiedForCourse:output_type -> v1.course_scheduling.CheckTeacherQualifiedForCourseResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_qualification_qualification_proto_init() }
func file_v1_course_scheduling_qualification_qualification_proto_init() {
	if File_v1_course_scheduling_qualification_qualification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_qualification_qualification_proto_rawDesc), len(file_v1_course_scheduling_qualification_qualification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_qualification_qualification_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_qualification_qualification_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_qualification_qualification_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_qualification_qualification_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_qualification_qualification_proto = out.File
	file_v1_course_scheduling_qualification_qualification_proto_goTypes = nil
	file_v1_course_scheduling_qualification_qualification_proto_depIdxs = nil
}
