// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/student/student.proto

package studentv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationStudentServiceDeleteStudent = "/v1.course_scheduling.StudentService/DeleteStudent"
const OperationStudentServiceGetStudent = "/v1.course_scheduling.StudentService/GetStudent"
const OperationStudentServiceListStudents = "/v1.course_scheduling.StudentService/ListStudents"
const OperationStudentServiceSaveStudent = "/v1.course_scheduling.StudentService/SaveStudent"

type StudentServiceHTTPServer interface {
	// DeleteStudent DeleteStudent hard-deletes a student by ID.
	DeleteStudent(context.Context, *DeleteStudentRequest) (*emptypb.Empty, error)
	// GetStudent GetStudent returns a single student by ID.
	GetStudent(context.Context, *GetStudentRequest) (*Student, error)
	// ListStudents ListStudents returns a page of students.
	ListStudents(context.Context, *ListStudentsRequest) (*StudentSet, error)
	// SaveStudent SaveStudent creates a new student (id absent) or updates an existing one.
	SaveStudent(context.Context, *SaveStudentRequest) (*Student, error)
}

func RegisterStudentServiceHTTPServer(s *http.Server, srv StudentServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/students", _StudentService_SaveStudent0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/students/{id}", _StudentService_DeleteStudent0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/students/{id}", _StudentService_GetStudent0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/students", _StudentService_ListStudents0_HTTP_Handler(srv))
}

func _StudentService_SaveStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveStudentRequest
		if err := ctx.Bind(&in.Student); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceSaveStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveStudent(ctx, req.(*SaveStudentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Student)
		return ctx.Result(200, reply)
	}
}

func _StudentService_DeleteStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteStudentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceDeleteStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteStudent(ctx, req.(*DeleteStudentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _StudentService_GetStudent0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStudentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceGetStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStudent(ctx, req.(*GetStudentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Student)
		return ctx.Result(200, reply)
	}
}

func _StudentService_ListStudents0_HTTP_Handler(srv StudentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStudentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudentServiceListStudents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStudents(ctx, req.(*ListStudentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StudentSet)
		return ctx.Result(200, reply)
	}
}

type StudentServiceHTTPClient interface {
	// DeleteStudent DeleteStudent hard-deletes a student by ID.
	DeleteStudent(ctx context.Context, req *DeleteStudentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetStudent GetStudent returns a single student by ID.
	GetStudent(ctx context.Context, req *GetStudentRequest, opts ...http.CallOption) (rsp *Student, err error)
	// ListStudents ListStudents returns a page of students.
	ListStudents(ctx context.Context, req *ListStudentsRequest, opts ...http.CallOption) (rsp *StudentSet, err error)
	// SaveStudent SaveStudent creates a new student (id absent) or updates an existing one.
	SaveStudent(ctx context.Context, req *SaveStudentRequest, opts ...http.CallOption) (rsp *Student, err error)
}

type StudentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStudentServiceHTTPClient(client *http.Client) StudentServiceHTTPClient {
	return &StudentServiceHTTPClientImpl{client}
}

// DeleteStudent DeleteStudent hard-deletes a student by ID.
func (c *StudentServiceHTTPClientImpl) DeleteStudent(ctx context.Context, in *DeleteStudentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/students/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationStudentServiceDeleteStudent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStudent GetStudent returns a single student by ID.
func (c *StudentServiceHTTPClientImpl) GetStudent(ctx context.Context, in *GetStudentRequest, opts ...http.CallOption) (*Student, error) {
	var out Student
	pattern := "/v1/students/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationStudentServiceGetStudent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListStudents ListStudents returns a page of students.
func (c *StudentServiceHTTPClientImpl) ListStudents(ctx context.Context, in *ListStudentsRequest, opts ...http.CallOption) (*StudentSet, error) {
	var out StudentSet
	pattern := "/v1/students"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationStudentServiceListStudents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveStudent SaveStudent creates a new student (id absent) or updates an existing one.
func (c *StudentServiceHTTPClientImpl) SaveStudent(ctx context.Context, in *SaveStudentRequest, opts ...http.CallOption) (*Student, error) {
	var out Student
	pattern := "/v1/students"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("student"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationStudentServiceSaveStudent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Student, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
