// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/student/student.proto

package studentv1

import (
	course_scheduling "cqrs/api/v1/course_scheduling"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StudentStatus represents the lifecycle state of a student.
type StudentStatus int32

const (
	StudentStatus_STUDENT_STATUS_UNSPECIFIED StudentStatus = 0
	StudentStatus_STUDENT_STATUS_ACTIVE      StudentStatus = 1
	StudentStatus_STUDENT_STATUS_BLOCKED     StudentStatus = 2
	StudentStatus_STUDENT_STATUS_CANCELLED   StudentStatus = 3
)

// Enum value maps for StudentStatus.
var (
	StudentStatus_name = map[int32]string{
		0: "STUDENT_STATUS_UNSPECIFIED",
		1: "STUDENT_STATUS_ACTIVE",
		2: "STUDENT_STATUS_BLOCKED",
		3: "STUDENT_STATUS_CANCELLED",
	}
	StudentStatus_value = map[string]int32{
		"STUDENT_STATUS_UNSPECIFIED": 0,
		"STUDENT_STATUS_ACTIVE":      1,
		"STUDENT_STATUS_BLOCKED":     2,
		"STUDENT_STATUS_CANCELLED":   3,
	}
)

func (x StudentStatus) Enum() *StudentStatus {
	p := new(StudentStatus)
	*p = x
	return p
}

func (x StudentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_student_student_proto_enumTypes[0].Descriptor()
}

func (StudentStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_student_student_proto_enumTypes[0]
}

func (x StudentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudentStatus.Descriptor instead.
func (StudentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{0}
}

// StudentType distinguishes internal employees from external clients.
type StudentType int32

const (
	StudentType_STUDENT_TYPE_UNSPECIFIED StudentType = 0
	StudentType_STUDENT_TYPE_EXTERNAL    StudentType = 1
	StudentType_STUDENT_TYPE_INTERNAL    StudentType = 2
)

// Enum value maps for StudentType.
var (
	StudentType_name = map[int32]string{
		0: "STUDENT_TYPE_UNSPECIFIED",
		1: "STUDENT_TYPE_EXTERNAL",
		2: "STUDENT_TYPE_INTERNAL",
	}
	StudentType_value = map[string]int32{
		"STUDENT_TYPE_UNSPECIFIED": 0,
		"STUDENT_TYPE_EXTERNAL":    1,
		"STUDENT_TYPE_INTERNAL":    2,
	}
)

func (x StudentType) Enum() *StudentType {
	p := new(StudentType)
	*p = x
	return p
}

func (x StudentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudentType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_student_student_proto_enumTypes[1].Descriptor()
}

func (StudentType) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_student_student_proto_enumTypes[1]
}

func (x StudentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudentType.Descriptor instead.
func (StudentType) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{1}
}

// Student represents a student enrolled in the scheduling system.
type Student struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Student's full name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Student type (external or internal).
	StudentType StudentType `protobuf:"varint,3,opt,name=student_type,json=studentType,proto3,enum=v1.course_scheduling.StudentType" json:"student_type,omitempty"`
	// Contact information.
	Contact *course_scheduling.ContactInfo `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	// Lifecycle status.
	Status StudentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=v1.course_scheduling.StudentStatus" json:"status,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetStudentType() StudentType {
	if x != nil {
		return x.StudentType
	}
	return StudentType_STUDENT_TYPE_UNSPECIFIED
}

func (x *Student) GetContact() *course_scheduling.ContactInfo {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Student) GetStatus() StudentStatus {
	if x != nil {
		return x.Status
	}
	return StudentStatus_STUDENT_STATUS_UNSPECIFIED
}

func (x *Student) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Student) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StudentSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentSet) Reset() {
	*x = StudentSet{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentSet) ProtoMessage() {}

func (x *StudentSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentSet.ProtoReflect.Descriptor instead.
func (*StudentSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *StudentSet) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type SaveStudentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The student to create or update. Set id to create; omit id to update.
	Student       *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStudentRequest) Reset() {
	*x = SaveStudentRequest{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStudentRequest) ProtoMessage() {}

func (x *SaveStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStudentRequest.ProtoReflect.Descriptor instead.
func (*SaveStudentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *SaveStudentRequest) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *ListStudentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStudentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStudentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListStudentsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_student_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_student_student_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_student_student_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_student_student_proto_rawDesc = "" +
	"\n" +
	"*v1/course_scheduling/student/student.proto\x12\x14v1.course_scheduling\x1a!v1/course_scheduling/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x02\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\fstudent_type\x18\x03 \x01(\x0e2!.v1.course_scheduling.StudentTypeR\vstudentType\x12;\n" +
	"\acontact\x18\x04 \x01(\v2!.v1.course_scheduling.ContactInfoR\acontact\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.v1.course_scheduling.StudentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\n" +
	"StudentSet\x129\n" +
	"\bstudents\x18\x01 \x03(\v2\x1d.v1.course_scheduling.StudentR\bstudents\"R\n" +
	"\x12SaveStudentRequest\x12<\n" +
	"\astudent\x18\x01 \x01(\v2\x1d.v1.course_scheduling.StudentB\x03\xe0A\x02R\astudent\"(\n" +
	"\x11GetStudentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"y\n" +
	"\x13ListStudentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"+\n" +
	"\x14DeleteStudentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\x84\x01\n" +
	"\rStudentStatus\x12\x1e\n" +
	"\x1aSTUDENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STUDENT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16STUDENT_STATUS_BLOCKED\x10\x02\x12\x1c\n" +
	"\x18STUDENT_STATUS_CANCELLED\x10\x03*a\n" +
	"\vStudentType\x12\x1c\n" +
	"\x18STUDENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STUDENT_TYPE_EXTERNAL\x10\x01\x12\x19\n" +
	"\x15STUDENT_TYPE_INTERNAL\x10\x022\xd4\x03\n" +
	"\x0eStudentService\x12n\n" +
	"\vSaveStudent\x12(.v1.course_scheduling.SaveStudentRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\astudent\"\f/v1/students\x12n\n" +
	"\rDeleteStudent\x12*.v1.course_scheduling.DeleteStudentRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/students/{id}\x12o\n" +
	"\n" +
	"GetStudent\x12'.v1.course_scheduling.GetStudentRequest\x1a\x1d.v1.course_scheduling.Student\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/students/{id}\x12q\n" +
	"\fListStudents\x12).v1.course_scheduling.ListStudentsRequest\x1a .v1.course_scheduling.StudentSet\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/studentsBh\n" +
	"%io.grpc.examples.course_scheduling.v1B\fStudentProtoP\x01Z/cqrs/api/v1/course_scheduling/student;studentv1b\x06proto3"

var (
	file_v1_course_scheduling_student_student_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_student_student_proto_rawDescData []byte
)

func file_v1_course_scheduling_student_student_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_student_student_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_student_student_proto_rawDesc), len(file_v1_course_scheduling_student_student_proto_rawDesc)))
	})
	return file_v1_course_scheduling_student_student_proto_rawDescData
}

var file_v1_course_scheduling_student_student_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_course_scheduling_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_course_scheduling_student_student_proto_goTypes = []any{
	(StudentStatus)(0),                    // 0: v1.course_scheduling.StudentStatus
	(StudentType)(0),                      // 1: v1.course_scheduling.StudentType
	(*Student)(nil),                       // 2: v1.course_scheduling.Student
	(*StudentSet)(nil),                    // 3: v1.course_scheduling.StudentSet
	(*SaveStudentRequest)(nil),            // 4: v1.course_scheduling.SaveStudentRequest
	(*GetStudentRequest)(nil),             // 5: v1.course_scheduling.GetStudentRequest
	(*ListStudentsRequest)(nil),           // 6: v1.course_scheduling.ListStudentsRequest
	(*DeleteStudentRequest)(nil),          // 7: v1.course_scheduling.DeleteStudentRequest
	(*course_scheduling.ContactInfo)(nil), // 8: v1.course_scheduling.ContactInfo
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
}
var file_v1_course_scheduling_student_student_proto_depIdxs = []int32{
	1,  // 0: v1.course_scheduling.Student.student_type:type_name -> v1.course_scheduling.StudentType
	8,  // 1: v1.course_scheduling.Student.contact:type_name -> v1.course_scheduling.ContactInfo
	0,  // 2: v1.course_scheduling.Student.status:type_name -> v1.course_scheduling.StudentStatus
	9,  // 3: v1.course_scheduling.Student.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: v1.course_scheduling.Student.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: v1.course_scheduling.StudentSet.students:type_name -> v1.course_scheduling.Student
	2,  // 6: v1.course_scheduling.SaveStudentRequest.student:type_name -> v1.course_scheduling.Student
	4,  // 7: v1.course_scheduling.StudentService.SaveStudent:input_type -> v1.course_scheduling.SaveStudentRequest
	7,  // 8: v1.course_scheduling.StudentService.DeleteStudent:input_type -> v1.course_scheduling.DeleteStudentRequest
	5,  // 9: v1.course_scheduling.StudentService.GetStudent:input_type -> v1.course_scheduling.GetStudentRequest
	6,  // 10: v1.course_scheduling.StudentService.ListStudents:input_type -> v1.course_scheduling.ListStudentsRequest
	10, // 11: v1.course_scheduling.StudentService.SaveStudent:output_type -> google.protobuf.Empty
	10, // 12: v1.course_scheduling.StudentService.DeleteStudent:output_type -> google.protobuf.Empty
	2,  // 13: v1.course_scheduling.StudentService.GetStudent:output_type -> v1.course_scheduling.Student
	3,  // 14: v1.course_scheduling.StudentService.ListStudents:output_type -> v1.course_scheduling.StudentSet
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_student_student_proto_init() }
func file_v1_course_scheduling_student_student_proto_init() {
	if File_v1_course_scheduling_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_student_student_proto_rawDesc), len(file_v1_course_scheduling_student_student_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_student_student_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_student_student_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_student_student_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_student_student_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_student_student_proto = out.File
	file_v1_course_scheduling_student_student_proto_goTypes = nil
	file_v1_course_scheduling_student_student_proto_depIdxs = nil
}
