// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/teacher/teacher.proto

package teacherv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationTeacherServiceDeleteTeacher = "/v1.course_scheduling.TeacherService/DeleteTeacher"
const OperationTeacherServiceGetTeacher = "/v1.course_scheduling.TeacherService/GetTeacher"
const OperationTeacherServiceListTeachers = "/v1.course_scheduling.TeacherService/ListTeachers"
const OperationTeacherServiceSaveTeacher = "/v1.course_scheduling.TeacherService/SaveTeacher"

type TeacherServiceHTTPServer interface {
	// DeleteTeacher DeleteTeacher hard-deletes a teacher by ID.
	DeleteTeacher(context.Context, *DeleteTeacherRequest) (*emptypb.Empty, error)
	// GetTeacher GetTeacher returns a single teacher by ID.
	GetTeacher(context.Context, *GetTeacherRequest) (*Teacher, error)
	// ListTeachers ListTeachers returns a page of teachers.
	ListTeachers(context.Context, *ListTeachersRequest) (*TeacherSet, error)
	// SaveTeacher SaveTeacher creates or updates a teacher.
	SaveTeacher(context.Context, *SaveTeacherRequest) (*Teacher, error)
}

func RegisterTeacherServiceHTTPServer(s *http.Server, srv TeacherServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/teachers", _TeacherService_SaveTeacher0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/teachers/{id}", _TeacherService_DeleteTeacher0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/teachers/{id}", _TeacherService_GetTeacher0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/teachers", _TeacherService_ListTeachers0_HTTP_Handler(srv))
}

func _TeacherService_SaveTeacher0_HTTP_Handler(srv TeacherServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveTeacherRequest
		if err := ctx.Bind(&in.Teacher); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTeacherServiceSaveTeacher)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveTeacher(ctx, req.(*SaveTeacherRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Teacher)
		return ctx.Result(200, reply)
	}
}

func _TeacherService_DeleteTeacher0_HTTP_Handler(srv TeacherServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTeacherRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTeacherServiceDeleteTeacher)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTeacher(ctx, req.(*DeleteTeacherRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TeacherService_GetTeacher0_HTTP_Handler(srv TeacherServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTeacherRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTeacherServiceGetTeacher)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTeacher(ctx, req.(*GetTeacherRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Teacher)
		return ctx.Result(200, reply)
	}
}

func _TeacherService_ListTeachers0_HTTP_Handler(srv TeacherServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTeachersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTeacherServiceListTeachers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTeachers(ctx, req.(*ListTeachersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TeacherSet)
		return ctx.Result(200, reply)
	}
}

type TeacherServiceHTTPClient interface {
	// DeleteTeacher DeleteTeacher hard-deletes a teacher by ID.
	DeleteTeacher(ctx context.Context, req *DeleteTeacherRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetTeacher GetTeacher returns a single teacher by ID.
	GetTeacher(ctx context.Context, req *GetTeacherRequest, opts ...http.CallOption) (rsp *Teacher, err error)
	// ListTeachers ListTeachers returns a page of teachers.
	ListTeachers(ctx context.Context, req *ListTeachersRequest, opts ...http.CallOption) (rsp *TeacherSet, err error)
	// SaveTeacher SaveTeacher creates or updates a teacher.
	SaveTeacher(ctx context.Context, req *SaveTeacherRequest, opts ...http.CallOption) (rsp *Teacher, err error)
}

type TeacherServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTeacherServiceHTTPClient(client *http.Client) TeacherServiceHTTPClient {
	return &TeacherServiceHTTPClientImpl{client}
}

// DeleteTeacher DeleteTeacher hard-deletes a teacher by ID.
func (c *TeacherServiceHTTPClientImpl) DeleteTeacher(ctx context.Context, in *DeleteTeacherRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/teachers/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTeacherServiceDeleteTeacher),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTeacher GetTeacher returns a single teacher by ID.
func (c *TeacherServiceHTTPClientImpl) GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...http.CallOption) (*Teacher, error) {
	var out Teacher
	pattern := "/v1/teachers/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTeacherServiceGetTeacher),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTeachers ListTeachers returns a page of teachers.
func (c *TeacherServiceHTTPClientImpl) ListTeachers(ctx context.Context, in *ListTeachersRequest, opts ...http.CallOption) (*TeacherSet, error) {
	var out TeacherSet
	pattern := "/v1/teachers"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTeacherServiceListTeachers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveTeacher SaveTeacher creates or updates a teacher.
func (c *TeacherServiceHTTPClientImpl) SaveTeacher(ctx context.Context, in *SaveTeacherRequest, opts ...http.CallOption) (*Teacher, error) {
	var out Teacher
	pattern := "/v1/teachers"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("teacher"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTeacherServiceSaveTeacher),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Teacher, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
