// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/teacher/teacher.proto

package teacherv1

import (
	course_scheduling "cqrs/api/v1/course_scheduling"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TeacherStatus represents the lifecycle state of a teacher.
type TeacherStatus int32

const (
	TeacherStatus_TEACHER_STATUS_UNSPECIFIED TeacherStatus = 0
	TeacherStatus_TEACHER_STATUS_ACTIVE      TeacherStatus = 1
	TeacherStatus_TEACHER_STATUS_ON_LEAVE    TeacherStatus = 2
	TeacherStatus_TEACHER_STATUS_TERMINATED  TeacherStatus = 3
)

// Enum value maps for TeacherStatus.
var (
	TeacherStatus_name = map[int32]string{
		0: "TEACHER_STATUS_UNSPECIFIED",
		1: "TEACHER_STATUS_ACTIVE",
		2: "TEACHER_STATUS_ON_LEAVE",
		3: "TEACHER_STATUS_TERMINATED",
	}
	TeacherStatus_value = map[string]int32{
		"TEACHER_STATUS_UNSPECIFIED": 0,
		"TEACHER_STATUS_ACTIVE":      1,
		"TEACHER_STATUS_ON_LEAVE":    2,
		"TEACHER_STATUS_TERMINATED":  3,
	}
)

func (x TeacherStatus) Enum() *TeacherStatus {
	p := new(TeacherStatus)
	*p = x
	return p
}

func (x TeacherStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeacherStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_teacher_teacher_proto_enumTypes[0].Descriptor()
}

func (TeacherStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_teacher_teacher_proto_enumTypes[0]
}

func (x TeacherStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeacherStatus.Descriptor instead.
func (TeacherStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{0}
}

// Teacher represents an instructor in the scheduling system.
type Teacher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Linked student-system ID (for when the teacher also enrolls as a student).
	StudentId int64 `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// Teacher's full name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Professional title (e.g. "Senior Trainer", "Gold Instructor").
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Contact information.
	Contact *course_scheduling.ContactInfo `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	// Lifecycle status.
	Status TeacherStatus `protobuf:"varint,6,opt,name=status,proto3,enum=v1.course_scheduling.TeacherStatus" json:"status,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *Teacher) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Teacher) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Teacher) GetContact() *course_scheduling.ContactInfo {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Teacher) GetStatus() TeacherStatus {
	if x != nil {
		return x.Status
	}
	return TeacherStatus_TEACHER_STATUS_UNSPECIFIED
}

func (x *Teacher) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Teacher) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TeacherSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*Teacher             `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherSet) Reset() {
	*x = TeacherSet{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherSet) ProtoMessage() {}

func (x *TeacherSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherSet.ProtoReflect.Descriptor instead.
func (*TeacherSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *TeacherSet) GetTeachers() []*Teacher {
	if x != nil {
		return x.Teachers
	}
	return nil
}

type SaveTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teacher       *Teacher               `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTeacherRequest) Reset() {
	*x = SaveTeacherRequest{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTeacherRequest) ProtoMessage() {}

func (x *SaveTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTeacherRequest.ProtoReflect.Descriptor instead.
func (*SaveTeacherRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *SaveTeacherRequest) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type GetTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherRequest) Reset() {
	*x = GetTeacherRequest{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherRequest) ProtoMessage() {}

func (x *GetTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersRequest) Reset() {
	*x = ListTeachersRequest{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersRequest) ProtoMessage() {}

func (x *ListTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *ListTeachersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTeachersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTeachersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTeachersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_teacher_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_teacher_teacher_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_teacher_teacher_proto_rawDesc = "" +
	"\n" +
	"*v1/course_scheduling/teacher/teacher.proto\x12\x14v1.course_scheduling\x1a!v1/course_scheduling/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x02\n" +
	"\aTeacher\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12;\n" +
	"\acontact\x18\x05 \x01(\v2!.v1.course_scheduling.ContactInfoR\acontact\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.v1.course_scheduling.TeacherStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\n" +
	"TeacherSet\x129\n" +
	"\bteachers\x18\x01 \x03(\v2\x1d.v1.course_scheduling.TeacherR\bteachers\"R\n" +
	"\x12SaveTeacherRequest\x12<\n" +
	"\ateacher\x18\x01 \x01(\v2\x1d.v1.course_scheduling.TeacherB\x03\xe0A\x02R\ateacher\"(\n" +
	"\x11GetTeacherRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"y\n" +
	"\x13ListTeachersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"+\n" +
	"\x14DeleteTeacherRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\x86\x01\n" +
	"\rTeacherStatus\x12\x1e\n" +
	"\x1aTEACHER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TEACHER_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17TEACHER_STATUS_ON_LEAVE\x10\x02\x12\x1d\n" +
	"\x19TEACHER_STATUS_TERMINATED\x10\x032\xd4\x03\n" +
	"\x0eTeacherService\x12n\n" +
	"\vSaveTeacher\x12(.v1.course_scheduling.SaveTeacherRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\ateacher\"\f/v1/teachers\x12n\n" +
	"\rDeleteTeacher\x12*.v1.course_scheduling.DeleteTeacherRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/teachers/{id}\x12o\n" +
	"\n" +
	"GetTeacher\x12'.v1.course_scheduling.GetTeacherRequest\x1a\x1d.v1.course_scheduling.Teacher\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/teachers/{id}\x12q\n" +
	"\fListTeachers\x12).v1.course_scheduling.ListTeachersRequest\x1a .v1.course_scheduling.TeacherSet\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/teachersBh\n" +
	"%io.grpc.examples.course_scheduling.v1B\fTeacherProtoP\x01Z/cqrs/api/v1/course_scheduling/teacher;teacherv1b\x06proto3"

var (
	file_v1_course_scheduling_teacher_teacher_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_teacher_teacher_proto_rawDescData []byte
)

func file_v1_course_scheduling_teacher_teacher_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_teacher_teacher_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_teacher_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_teacher_teacher_proto_rawDesc), len(file_v1_course_scheduling_teacher_teacher_proto_rawDesc)))
	})
	return file_v1_course_scheduling_teacher_teacher_proto_rawDescData
}

var file_v1_course_scheduling_teacher_teacher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_teacher_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_course_scheduling_teacher_teacher_proto_goTypes = []any{
	(TeacherStatus)(0),                    // 0: v1.course_scheduling.TeacherStatus
	(*Teacher)(nil),                       // 1: v1.course_scheduling.Teacher
	(*TeacherSet)(nil),                    // 2: v1.course_scheduling.TeacherSet
	(*SaveTeacherRequest)(nil),            // 3: v1.course_scheduling.SaveTeacherRequest
	(*GetTeacherRequest)(nil),             // 4: v1.course_scheduling.GetTeacherRequest
	(*ListTeachersRequest)(nil),           // 5: v1.course_scheduling.ListTeachersRequest
	(*DeleteTeacherRequest)(nil),          // 6: v1.course_scheduling.DeleteTeacherRequest
	(*course_scheduling.ContactInfo)(nil), // 7: v1.course_scheduling.ContactInfo
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 9: google.protobuf.Empty
}
var file_v1_course_scheduling_teacher_teacher_proto_depIdxs = []int32{
	7,  // 0: v1.course_scheduling.Teacher.contact:type_name -> v1.course_scheduling.ContactInfo
	0,  // 1: v1.course_scheduling.Teacher.status:type_name -> v1.course_scheduling.TeacherStatus
	8,  // 2: v1.course_scheduling.Teacher.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: v1.course_scheduling.Teacher.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: v1.course_scheduling.TeacherSet.teachers:type_name -> v1.course_scheduling.Teacher
	1,  // 5: v1.course_scheduling.SaveTeacherRequest.teacher:type_name -> v1.course_scheduling.Teacher
	3,  // 6: v1.course_scheduling.TeacherService.SaveTeacher:input_type -> v1.course_scheduling.SaveTeacherRequest
	6,  // 7: v1.course_scheduling.TeacherService.DeleteTeacher:input_type -> v1.course_scheduling.DeleteTeacherRequest
	4,  // 8: v1.course_scheduling.TeacherService.GetTeacher:input_type -> v1.course_scheduling.GetTeacherRequest
	5,  // 9: v1.course_scheduling.TeacherService.ListTeachers:input_type -> v1.course_scheduling.ListTeachersRequest
	9,  // 10: v1.course_scheduling.TeacherService.SaveTeacher:output_type -> google.protobuf.Empty
	9,  // 11: v1.course_scheduling.TeacherService.DeleteTeacher:output_type -> google.protobuf.Empty
	1,  // 12: v1.course_scheduling.TeacherService.GetTeacher:output_type -> v1.course_scheduling.Teacher
	2,  // 13: v1.course_scheduling.TeacherService.ListTeachers:output_type -> v1.course_scheduling.TeacherSet
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_teacher_teacher_proto_init() }
func file_v1_course_scheduling_teacher_teacher_proto_init() {
	if File_v1_course_scheduling_teacher_teacher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_teacher_teacher_proto_rawDesc), len(file_v1_course_scheduling_teacher_teacher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_teacher_teacher_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_teacher_teacher_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_teacher_teacher_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_teacher_teacher_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_teacher_teacher_proto = out.File
	file_v1_course_scheduling_teacher_teacher_proto_goTypes = nil
	file_v1_course_scheduling_teacher_teacher_proto_depIdxs = nil
}
