// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/common.proto

package courseschedulingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContactInfo holds phone and email for a student or teacher.
type ContactInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Chinese mobile phone number (e.g. "13800138000").
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	// Optional email address.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_v1_course_scheduling_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_common_proto_rawDescGZIP(), []int{0}
}

func (x *ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_v1_course_scheduling_common_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_common_proto_rawDesc = "" +
	"\n" +
	"!v1/course_scheduling/common.proto\x12\x14v1.course_scheduling\"9\n" +
	"\vContactInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05emailBh\n" +
	"%io.grpc.examples.course_scheduling.v1B\vCommonProtoP\x01Z0cqrs/api/v1/course_scheduling;courseschedulingv1b\x06proto3"

var (
	file_v1_course_scheduling_common_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_common_proto_rawDescData []byte
)

func file_v1_course_scheduling_common_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_common_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_common_proto_rawDesc), len(file_v1_course_scheduling_common_proto_rawDesc)))
	})
	return file_v1_course_scheduling_common_proto_rawDescData
}

var file_v1_course_scheduling_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_course_scheduling_common_proto_goTypes = []any{
	(*ContactInfo)(nil), // 0: v1.course_scheduling.ContactInfo
}
var file_v1_course_scheduling_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_common_proto_init() }
func file_v1_course_scheduling_common_proto_init() {
	if File_v1_course_scheduling_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_common_proto_rawDesc), len(file_v1_course_scheduling_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_course_scheduling_common_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_common_proto_depIdxs,
		MessageInfos:      file_v1_course_scheduling_common_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_common_proto = out.File
	file_v1_course_scheduling_common_proto_goTypes = nil
	file_v1_course_scheduling_common_proto_depIdxs = nil
}
