// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/error_reason.proto

package courseschedulingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason enumerates domain-specific error codes for the course scheduling
// bounded context. Values start at 1; 0 is reserved as the default/unspecified.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// --- Not-found errors ---
	ErrorReason_STUDENT_NOT_FOUND            ErrorReason = 1
	ErrorReason_TEACHER_NOT_FOUND            ErrorReason = 2
	ErrorReason_CLASSROOM_NOT_FOUND          ErrorReason = 3
	ErrorReason_COURSE_NOT_FOUND             ErrorReason = 4
	ErrorReason_COURSE_SLOT_NOT_FOUND        ErrorReason = 5
	ErrorReason_COURSE_SLOT_CHANGE_NOT_FOUND ErrorReason = 6
	ErrorReason_ENROLLMENT_NOT_FOUND         ErrorReason = 7
	ErrorReason_ABSENCE_NOT_FOUND            ErrorReason = 8
	ErrorReason_MAKEUP_NOT_FOUND             ErrorReason = 9
	ErrorReason_QUALIFICATION_NOT_FOUND      ErrorReason = 10
	// --- Conflict / business-rule errors ---
	ErrorReason_SLOT_CONFLICT       ErrorReason = 20
	ErrorReason_ENROLLMENT_CONFLICT ErrorReason = 21
	ErrorReason_MAKEUP_CONFLICT     ErrorReason = 22
	ErrorReason_TEACHER_UNQUALIFIED ErrorReason = 23
	ErrorReason_COURSE_NOT_FINISHED ErrorReason = 24
	// --- Validation errors ---
	ErrorReason_INVALID_ARGUMENT ErrorReason = 30
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "STUDENT_NOT_FOUND",
		2:  "TEACHER_NOT_FOUND",
		3:  "CLASSROOM_NOT_FOUND",
		4:  "COURSE_NOT_FOUND",
		5:  "COURSE_SLOT_NOT_FOUND",
		6:  "COURSE_SLOT_CHANGE_NOT_FOUND",
		7:  "ENROLLMENT_NOT_FOUND",
		8:  "ABSENCE_NOT_FOUND",
		9:  "MAKEUP_NOT_FOUND",
		10: "QUALIFICATION_NOT_FOUND",
		20: "SLOT_CONFLICT",
		21: "ENROLLMENT_CONFLICT",
		22: "MAKEUP_CONFLICT",
		23: "TEACHER_UNQUALIFIED",
		24: "COURSE_NOT_FINISHED",
		30: "INVALID_ARGUMENT",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":     0,
		"STUDENT_NOT_FOUND":            1,
		"TEACHER_NOT_FOUND":            2,
		"CLASSROOM_NOT_FOUND":          3,
		"COURSE_NOT_FOUND":             4,
		"COURSE_SLOT_NOT_FOUND":        5,
		"COURSE_SLOT_CHANGE_NOT_FOUND": 6,
		"ENROLLMENT_NOT_FOUND":         7,
		"ABSENCE_NOT_FOUND":            8,
		"MAKEUP_NOT_FOUND":             9,
		"QUALIFICATION_NOT_FOUND":      10,
		"SLOT_CONFLICT":                20,
		"ENROLLMENT_CONFLICT":          21,
		"MAKEUP_CONFLICT":              22,
		"TEACHER_UNQUALIFIED":          23,
		"COURSE_NOT_FINISHED":          24,
		"INVALID_ARGUMENT":             30,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_v1_course_scheduling_error_reason_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_error_reason_proto_rawDesc = "" +
	"\n" +
	"'v1/course_scheduling/error_reason.proto\x12\x14v1.course_scheduling*\xb2\x03\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STUDENT_NOT_FOUND\x10\x01\x12\x15\n" +
	"\x11TEACHER_NOT_FOUND\x10\x02\x12\x17\n" +
	"\x13CLASSROOM_NOT_FOUND\x10\x03\x12\x14\n" +
	"\x10COURSE_NOT_FOUND\x10\x04\x12\x19\n" +
	"\x15COURSE_SLOT_NOT_FOUND\x10\x05\x12 \n" +
	"\x1cCOURSE_SLOT_CHANGE_NOT_FOUND\x10\x06\x12\x18\n" +
	"\x14ENROLLMENT_NOT_FOUND\x10\a\x12\x15\n" +
	"\x11ABSENCE_NOT_FOUND\x10\b\x12\x14\n" +
	"\x10MAKEUP_NOT_FOUND\x10\t\x12\x1b\n" +
	"\x17QUALIFICATION_NOT_FOUND\x10\n" +
	"\x12\x11\n" +
	"\rSLOT_CONFLICT\x10\x14\x12\x17\n" +
	"\x13ENROLLMENT_CONFLICT\x10\x15\x12\x13\n" +
	"\x0fMAKEUP_CONFLICT\x10\x16\x12\x17\n" +
	"\x13TEACHER_UNQUALIFIED\x10\x17\x12\x17\n" +
	"\x13COURSE_NOT_FINISHED\x10\x18\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x1eBw\n" +
	"%io.grpc.examples.course_scheduling.v1B\x1aCourseSchedulingErrorProtoP\x01Z0cqrs/api/v1/course_scheduling;courseschedulingv1b\x06proto3"

var (
	file_v1_course_scheduling_error_reason_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_error_reason_proto_rawDescData []byte
)

func file_v1_course_scheduling_error_reason_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_error_reason_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_error_reason_proto_rawDesc), len(file_v1_course_scheduling_error_reason_proto_rawDesc)))
	})
	return file_v1_course_scheduling_error_reason_proto_rawDescData
}

var file_v1_course_scheduling_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: v1.course_scheduling.ErrorReason
}
var file_v1_course_scheduling_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_error_reason_proto_init() }
func file_v1_course_scheduling_error_reason_proto_init() {
	if File_v1_course_scheduling_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_error_reason_proto_rawDesc), len(file_v1_course_scheduling_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_course_scheduling_error_reason_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_error_reason_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_error_reason_proto_enumTypes,
	}.Build()
	File_v1_course_scheduling_error_reason_proto = out.File
	file_v1_course_scheduling_error_reason_proto_goTypes = nil
	file_v1_course_scheduling_error_reason_proto_depIdxs = nil
}
