// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cqrs/internal/conf"
	"cqrs/internal/core/course_scheduling/ports"
	"cqrs/internal/core/course_scheduling/service"
	"cqrs/internal/server"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
// 目前只 wire course_scheduling 一个上下文。product / commerce 的 ProviderSet
// 先不挂进来：它们自己的 provider 还没补齐，挂进来会让整个应用没法生成。
func wireApp(confServer *conf.Server, data *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	teacherService := service.NewTeacherService()
	studentService := service.NewStudentService()
	courseService := service.NewCourseService()
	httpServer := ports.NewHTTPServer(confServer, teacherService, studentService, courseService)
	grpcServer := ports.NewGRPCServer(confServer, teacherService, studentService, courseService)
	v := ports.NewServers(httpServer, grpcServer)
	servers := server.NewServers(v)
	app := newApp(logger, servers)
	return app, func() {
	}, nil
}
