// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cqrs/internal/conf"
	"cqrs/internal/core/product/adapters/memory"
	"cqrs/internal/core/product/adapters/memory/command"
	command2 "cqrs/internal/core/product/app/command"
	ports2 "cqrs/internal/core/product/ports"
	service2 "cqrs/internal/core/product/service"
	"cqrs/internal/core/teaching/ports"
	"cqrs/internal/core/teaching/service"
	"cqrs/internal/server"
	memory2 "cqrs/internal/support/commerce/adapters/memory"
	command3 "cqrs/internal/support/commerce/adapters/memory/command"
	command4 "cqrs/internal/support/commerce/app/command"
	ports3 "cqrs/internal/support/commerce/ports"
	service3 "cqrs/internal/support/commerce/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	teacherService := service.NewTeacherService()
	studentService := service.NewStudentService()
	courseService := service.NewCourseService()
	httpServer := ports.NewHTTPServer(confServer, teacherService, studentService, courseService)
	grpcServer := ports.NewGRPCServer(confServer, teacherService, studentService, courseService)
	v := ports.NewServers(httpServer, grpcServer)
	memoryData, cleanup, err := memory.NewData(data)
	if err != nil {
		return nil, nil, err
	}
	productRepo := command.NewProductRepo(memoryData)
	productUsecase := command2.NewProductUsecase(productRepo)
	productService := service2.NewProductService(productUsecase)
	portsHTTPServer := ports2.NewHTTPServer(confServer, productService)
	portsGRPCServer := ports2.NewGRPCServer(confServer, productService)
	v2 := ports2.NewServers(portsHTTPServer, portsGRPCServer)
	data2, cleanup2, err := memory2.NewData(data)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	paymentRepo := command3.NewPaymentRepo(data2)
	paymentUsecase := command4.NewPaymentUsecase(paymentRepo)
	paymentService := service3.NewPaymentService(paymentUsecase)
	discountRepo := command3.NewDiscountRepo(data2)
	discountUsecase := command4.NewDiscountUsecase(discountRepo)
	discountService := service3.NewDiscountService(discountUsecase)
	httpServer2 := ports3.NewHTTPServer(confServer, paymentService, discountService)
	grpcServer2 := ports3.NewGRPCServer(confServer, paymentService, discountService)
	v3 := ports3.NewServers(httpServer2, grpcServer2)
	servers := server.NewServers(v, v2, v3)
	app := newApp(logger, servers)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
