// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/course_scheduling/course_slot/course_slot.proto

package courseslotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseSlotService_AssignClassroomToCourseSlot_FullMethodName = "/v1.course_scheduling.CourseSlotService/AssignClassroomToCourseSlot"
	CourseSlotService_AssignCourseToCourseSlot_FullMethodName    = "/v1.course_scheduling.CourseSlotService/AssignCourseToCourseSlot"
	CourseSlotService_AssignTeacherToCourseSlot_FullMethodName   = "/v1.course_scheduling.CourseSlotService/AssignTeacherToCourseSlot"
	CourseSlotService_DeleteCourseSlot_FullMethodName            = "/v1.course_scheduling.CourseSlotService/DeleteCourseSlot"
	CourseSlotService_GetCourseSlot_FullMethodName               = "/v1.course_scheduling.CourseSlotService/GetCourseSlot"
	CourseSlotService_ListCourseSlots_FullMethodName             = "/v1.course_scheduling.CourseSlotService/ListCourseSlots"
	CourseSlotService_ListCourseSlotsByCourseID_FullMethodName   = "/v1.course_scheduling.CourseSlotService/ListCourseSlotsByCourseID"
)

// CourseSlotServiceClient is the client API for CourseSlotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CourseSlotService owns the course slot aggregate.
type CourseSlotServiceClient interface {
	// AssignClassroomToCourseSlot assigns a classroom to one or more slots.
	AssignClassroomToCourseSlot(ctx context.Context, in *AssignClassroomToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AssignCourseToCourseSlot assigns a course to one or more slots.
	AssignCourseToCourseSlot(ctx context.Context, in *AssignCourseToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AssignTeacherToCourseSlot assigns a teacher to one or more slots.
	AssignTeacherToCourseSlot(ctx context.Context, in *AssignTeacherToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteCourseSlot hard-deletes a course slot by ID.
	DeleteCourseSlot(ctx context.Context, in *DeleteCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetCourseSlot returns a single course slot by ID.
	GetCourseSlot(ctx context.Context, in *GetCourseSlotRequest, opts ...grpc.CallOption) (*CourseSlot, error)
	// ListCourseSlots returns a page of course slots.
	ListCourseSlots(ctx context.Context, in *ListCourseSlotsRequest, opts ...grpc.CallOption) (*CourseSlotSet, error)
	// ListCourseSlotsByCourseID returns all slots belonging to a course.
	ListCourseSlotsByCourseID(ctx context.Context, in *ListCourseSlotsByCourseIDRequest, opts ...grpc.CallOption) (*CourseSlotSet, error)
}

type courseSlotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseSlotServiceClient(cc grpc.ClientConnInterface) CourseSlotServiceClient {
	return &courseSlotServiceClient{cc}
}

func (c *courseSlotServiceClient) AssignClassroomToCourseSlot(ctx context.Context, in *AssignClassroomToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourseSlotService_AssignClassroomToCourseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) AssignCourseToCourseSlot(ctx context.Context, in *AssignCourseToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourseSlotService_AssignCourseToCourseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) AssignTeacherToCourseSlot(ctx context.Context, in *AssignTeacherToCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourseSlotService_AssignTeacherToCourseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) DeleteCourseSlot(ctx context.Context, in *DeleteCourseSlotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourseSlotService_DeleteCourseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) GetCourseSlot(ctx context.Context, in *GetCourseSlotRequest, opts ...grpc.CallOption) (*CourseSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseSlot)
	err := c.cc.Invoke(ctx, CourseSlotService_GetCourseSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) ListCourseSlots(ctx context.Context, in *ListCourseSlotsRequest, opts ...grpc.CallOption) (*CourseSlotSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseSlotSet)
	err := c.cc.Invoke(ctx, CourseSlotService_ListCourseSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseSlotServiceClient) ListCourseSlotsByCourseID(ctx context.Context, in *ListCourseSlotsByCourseIDRequest, opts ...grpc.CallOption) (*CourseSlotSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseSlotSet)
	err := c.cc.Invoke(ctx, CourseSlotService_ListCourseSlotsByCourseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseSlotServiceServer is the server API for CourseSlotService service.
// All implementations must embed UnimplementedCourseSlotServiceServer
// for forward compatibility.
//
// CourseSlotService owns the course slot aggregate.
type CourseSlotServiceServer interface {
	// AssignClassroomToCourseSlot assigns a classroom to one or more slots.
	AssignClassroomToCourseSlot(context.Context, *AssignClassroomToCourseSlotRequest) (*emptypb.Empty, error)
	// AssignCourseToCourseSlot assigns a course to one or more slots.
	AssignCourseToCourseSlot(context.Context, *AssignCourseToCourseSlotRequest) (*emptypb.Empty, error)
	// AssignTeacherToCourseSlot assigns a teacher to one or more slots.
	AssignTeacherToCourseSlot(context.Context, *AssignTeacherToCourseSlotRequest) (*emptypb.Empty, error)
	// DeleteCourseSlot hard-deletes a course slot by ID.
	DeleteCourseSlot(context.Context, *DeleteCourseSlotRequest) (*emptypb.Empty, error)
	// GetCourseSlot returns a single course slot by ID.
	GetCourseSlot(context.Context, *GetCourseSlotRequest) (*CourseSlot, error)
	// ListCourseSlots returns a page of course slots.
	ListCourseSlots(context.Context, *ListCourseSlotsRequest) (*CourseSlotSet, error)
	// ListCourseSlotsByCourseID returns all slots belonging to a course.
	ListCourseSlotsByCourseID(context.Context, *ListCourseSlotsByCourseIDRequest) (*CourseSlotSet, error)
	mustEmbedUnimplementedCourseSlotServiceServer()
}

// UnimplementedCourseSlotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseSlotServiceServer struct{}

func (UnimplementedCourseSlotServiceServer) AssignClassroomToCourseSlot(context.Context, *AssignClassroomToCourseSlotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignClassroomToCourseSlot not implemented")
}
func (UnimplementedCourseSlotServiceServer) AssignCourseToCourseSlot(context.Context, *AssignCourseToCourseSlotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCourseToCourseSlot not implemented")
}
func (UnimplementedCourseSlotServiceServer) AssignTeacherToCourseSlot(context.Context, *AssignTeacherToCourseSlotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTeacherToCourseSlot not implemented")
}
func (UnimplementedCourseSlotServiceServer) DeleteCourseSlot(context.Context, *DeleteCourseSlotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCourseSlot not implemented")
}
func (UnimplementedCourseSlotServiceServer) GetCourseSlot(context.Context, *GetCourseSlotRequest) (*CourseSlot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseSlot not implemented")
}
func (UnimplementedCourseSlotServiceServer) ListCourseSlots(context.Context, *ListCourseSlotsRequest) (*CourseSlotSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourseSlots not implemented")
}
func (UnimplementedCourseSlotServiceServer) ListCourseSlotsByCourseID(context.Context, *ListCourseSlotsByCourseIDRequest) (*CourseSlotSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourseSlotsByCourseID not implemented")
}
func (UnimplementedCourseSlotServiceServer) mustEmbedUnimplementedCourseSlotServiceServer() {}
func (UnimplementedCourseSlotServiceServer) testEmbeddedByValue()                           {}

// UnsafeCourseSlotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseSlotServiceServer will
// result in compilation errors.
type UnsafeCourseSlotServiceServer interface {
	mustEmbedUnimplementedCourseSlotServiceServer()
}

func RegisterCourseSlotServiceServer(s grpc.ServiceRegistrar, srv CourseSlotServiceServer) {
	// If the following call panics, it indicates UnimplementedCourseSlotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseSlotService_ServiceDesc, srv)
}

func _CourseSlotService_AssignClassroomToCourseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignClassroomToCourseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).AssignClassroomToCourseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_AssignClassroomToCourseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).AssignClassroomToCourseSlot(ctx, req.(*AssignClassroomToCourseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_AssignCourseToCourseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCourseToCourseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).AssignCourseToCourseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_AssignCourseToCourseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).AssignCourseToCourseSlot(ctx, req.(*AssignCourseToCourseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_AssignTeacherToCourseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTeacherToCourseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).AssignTeacherToCourseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_AssignTeacherToCourseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).AssignTeacherToCourseSlot(ctx, req.(*AssignTeacherToCourseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_DeleteCourseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).DeleteCourseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_DeleteCourseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).DeleteCourseSlot(ctx, req.(*DeleteCourseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_GetCourseSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).GetCourseSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_GetCourseSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).GetCourseSlot(ctx, req.(*GetCourseSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_ListCourseSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCourseSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).ListCourseSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_ListCourseSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).ListCourseSlots(ctx, req.(*ListCourseSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseSlotService_ListCourseSlotsByCourseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCourseSlotsByCourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseSlotServiceServer).ListCourseSlotsByCourseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseSlotService_ListCourseSlotsByCourseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseSlotServiceServer).ListCourseSlotsByCourseID(ctx, req.(*ListCourseSlotsByCourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseSlotService_ServiceDesc is the grpc.ServiceDesc for CourseSlotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseSlotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.course_scheduling.CourseSlotService",
	HandlerType: (*CourseSlotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignClassroomToCourseSlot",
			Handler:    _CourseSlotService_AssignClassroomToCourseSlot_Handler,
		},
		{
			MethodName: "AssignCourseToCourseSlot",
			Handler:    _CourseSlotService_AssignCourseToCourseSlot_Handler,
		},
		{
			MethodName: "AssignTeacherToCourseSlot",
			Handler:    _CourseSlotService_AssignTeacherToCourseSlot_Handler,
		},
		{
			MethodName: "DeleteCourseSlot",
			Handler:    _CourseSlotService_DeleteCourseSlot_Handler,
		},
		{
			MethodName: "GetCourseSlot",
			Handler:    _CourseSlotService_GetCourseSlot_Handler,
		},
		{
			MethodName: "ListCourseSlots",
			Handler:    _CourseSlotService_ListCourseSlots_Handler,
		},
		{
			MethodName: "ListCourseSlotsByCourseID",
			Handler:    _CourseSlotService_ListCourseSlotsByCourseID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/course_scheduling/course_slot/course_slot.proto",
}
