// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/course_slot/course_slot.proto

package courseslotv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCourseSlotServiceAssignClassroomToCourseSlot = "/v1.course_scheduling.CourseSlotService/AssignClassroomToCourseSlot"
const OperationCourseSlotServiceAssignCourseToCourseSlot = "/v1.course_scheduling.CourseSlotService/AssignCourseToCourseSlot"
const OperationCourseSlotServiceAssignTeacherToCourseSlot = "/v1.course_scheduling.CourseSlotService/AssignTeacherToCourseSlot"
const OperationCourseSlotServiceDeleteCourseSlot = "/v1.course_scheduling.CourseSlotService/DeleteCourseSlot"
const OperationCourseSlotServiceGetCourseSlot = "/v1.course_scheduling.CourseSlotService/GetCourseSlot"
const OperationCourseSlotServiceListCourseSlots = "/v1.course_scheduling.CourseSlotService/ListCourseSlots"
const OperationCourseSlotServiceListCourseSlotsByCourseID = "/v1.course_scheduling.CourseSlotService/ListCourseSlotsByCourseID"

type CourseSlotServiceHTTPServer interface {
	// AssignClassroomToCourseSlot AssignClassroomToCourseSlot assigns a classroom to one or more slots.
	AssignClassroomToCourseSlot(context.Context, *AssignClassroomToCourseSlotRequest) (*emptypb.Empty, error)
	// AssignCourseToCourseSlot AssignCourseToCourseSlot assigns a course to one or more slots.
	AssignCourseToCourseSlot(context.Context, *AssignCourseToCourseSlotRequest) (*emptypb.Empty, error)
	// AssignTeacherToCourseSlot AssignTeacherToCourseSlot assigns a teacher to one or more slots.
	AssignTeacherToCourseSlot(context.Context, *AssignTeacherToCourseSlotRequest) (*emptypb.Empty, error)
	// DeleteCourseSlot DeleteCourseSlot hard-deletes a course slot by ID.
	DeleteCourseSlot(context.Context, *DeleteCourseSlotRequest) (*emptypb.Empty, error)
	// GetCourseSlot GetCourseSlot returns a single course slot by ID.
	GetCourseSlot(context.Context, *GetCourseSlotRequest) (*CourseSlot, error)
	// ListCourseSlots ListCourseSlots returns a page of course slots.
	ListCourseSlots(context.Context, *ListCourseSlotsRequest) (*CourseSlotSet, error)
	// ListCourseSlotsByCourseID ListCourseSlotsByCourseID returns all slots belonging to a course.
	ListCourseSlotsByCourseID(context.Context, *ListCourseSlotsByCourseIDRequest) (*CourseSlotSet, error)
}

func RegisterCourseSlotServiceHTTPServer(s *http.Server, srv CourseSlotServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/course-slots/assign-classroom", _CourseSlotService_AssignClassroomToCourseSlot0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/course-slots/assign-course", _CourseSlotService_AssignCourseToCourseSlot0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/course-slots/assign-teacher", _CourseSlotService_AssignTeacherToCourseSlot0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/course-slots/{id}", _CourseSlotService_DeleteCourseSlot0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/course-slots/{id}", _CourseSlotService_GetCourseSlot0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/course-slots", _CourseSlotService_ListCourseSlots0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/{course_id}/slots", _CourseSlotService_ListCourseSlotsByCourseID0_HTTP_Handler(srv))
}

func _CourseSlotService_AssignClassroomToCourseSlot0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignClassroomToCourseSlotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceAssignClassroomToCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignClassroomToCourseSlot(ctx, req.(*AssignClassroomToCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_AssignCourseToCourseSlot0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignCourseToCourseSlotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceAssignCourseToCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignCourseToCourseSlot(ctx, req.(*AssignCourseToCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_AssignTeacherToCourseSlot0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignTeacherToCourseSlotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceAssignTeacherToCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignTeacherToCourseSlot(ctx, req.(*AssignTeacherToCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_DeleteCourseSlot0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCourseSlotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceDeleteCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCourseSlot(ctx, req.(*DeleteCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_GetCourseSlot0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourseSlotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceGetCourseSlot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourseSlot(ctx, req.(*GetCourseSlotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlot)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_ListCourseSlots0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCourseSlotsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceListCourseSlots)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourseSlots(ctx, req.(*ListCourseSlotsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotSet)
		return ctx.Result(200, reply)
	}
}

func _CourseSlotService_ListCourseSlotsByCourseID0_HTTP_Handler(srv CourseSlotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCourseSlotsByCourseIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourseSlotServiceListCourseSlotsByCourseID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCourseSlotsByCourseID(ctx, req.(*ListCourseSlotsByCourseIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseSlotSet)
		return ctx.Result(200, reply)
	}
}

type CourseSlotServiceHTTPClient interface {
	// AssignClassroomToCourseSlot AssignClassroomToCourseSlot assigns a classroom to one or more slots.
	AssignClassroomToCourseSlot(ctx context.Context, req *AssignClassroomToCourseSlotRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// AssignCourseToCourseSlot AssignCourseToCourseSlot assigns a course to one or more slots.
	AssignCourseToCourseSlot(ctx context.Context, req *AssignCourseToCourseSlotRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// AssignTeacherToCourseSlot AssignTeacherToCourseSlot assigns a teacher to one or more slots.
	AssignTeacherToCourseSlot(ctx context.Context, req *AssignTeacherToCourseSlotRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// DeleteCourseSlot DeleteCourseSlot hard-deletes a course slot by ID.
	DeleteCourseSlot(ctx context.Context, req *DeleteCourseSlotRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetCourseSlot GetCourseSlot returns a single course slot by ID.
	GetCourseSlot(ctx context.Context, req *GetCourseSlotRequest, opts ...http.CallOption) (rsp *CourseSlot, err error)
	// ListCourseSlots ListCourseSlots returns a page of course slots.
	ListCourseSlots(ctx context.Context, req *ListCourseSlotsRequest, opts ...http.CallOption) (rsp *CourseSlotSet, err error)
	// ListCourseSlotsByCourseID ListCourseSlotsByCourseID returns all slots belonging to a course.
	ListCourseSlotsByCourseID(ctx context.Context, req *ListCourseSlotsByCourseIDRequest, opts ...http.CallOption) (rsp *CourseSlotSet, err error)
}

type CourseSlotServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCourseSlotServiceHTTPClient(client *http.Client) CourseSlotServiceHTTPClient {
	return &CourseSlotServiceHTTPClientImpl{client}
}

// AssignClassroomToCourseSlot AssignClassroomToCourseSlot assigns a classroom to one or more slots.
func (c *CourseSlotServiceHTTPClientImpl) AssignClassroomToCourseSlot(ctx context.Context, in *AssignClassroomToCourseSlotRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/course-slots/assign-classroom"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCourseSlotServiceAssignClassroomToCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignCourseToCourseSlot AssignCourseToCourseSlot assigns a course to one or more slots.
func (c *CourseSlotServiceHTTPClientImpl) AssignCourseToCourseSlot(ctx context.Context, in *AssignCourseToCourseSlotRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/course-slots/assign-course"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCourseSlotServiceAssignCourseToCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignTeacherToCourseSlot AssignTeacherToCourseSlot assigns a teacher to one or more slots.
func (c *CourseSlotServiceHTTPClientImpl) AssignTeacherToCourseSlot(ctx context.Context, in *AssignTeacherToCourseSlotRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/course-slots/assign-teacher"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCourseSlotServiceAssignTeacherToCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCourseSlot DeleteCourseSlot hard-deletes a course slot by ID.
func (c *CourseSlotServiceHTTPClientImpl) DeleteCourseSlot(ctx context.Context, in *DeleteCourseSlotRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/course-slots/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotServiceDeleteCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourseSlot GetCourseSlot returns a single course slot by ID.
func (c *CourseSlotServiceHTTPClientImpl) GetCourseSlot(ctx context.Context, in *GetCourseSlotRequest, opts ...http.CallOption) (*CourseSlot, error) {
	var out CourseSlot
	pattern := "/v1/course-slots/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotServiceGetCourseSlot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCourseSlots ListCourseSlots returns a page of course slots.
func (c *CourseSlotServiceHTTPClientImpl) ListCourseSlots(ctx context.Context, in *ListCourseSlotsRequest, opts ...http.CallOption) (*CourseSlotSet, error) {
	var out CourseSlotSet
	pattern := "/v1/course-slots"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotServiceListCourseSlots),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCourseSlotsByCourseID ListCourseSlotsByCourseID returns all slots belonging to a course.
func (c *CourseSlotServiceHTTPClientImpl) ListCourseSlotsByCourseID(ctx context.Context, in *ListCourseSlotsByCourseIDRequest, opts ...http.CallOption) (*CourseSlotSet, error) {
	var out CourseSlotSet
	pattern := "/v1/courses/{course_id}/slots"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCourseSlotServiceListCourseSlotsByCourseID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
