// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/course_slot/course_slot.proto

package courseslotv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Weekday represents a day of the week.
type Weekday int32

const (
	Weekday_WEEKDAY_UNSPECIFIED Weekday = 0
	Weekday_WEEKDAY_SUNDAY      Weekday = 1
	Weekday_WEEKDAY_MONDAY      Weekday = 2
	Weekday_WEEKDAY_TUESDAY     Weekday = 3
	Weekday_WEEKDAY_WEDNESDAY   Weekday = 4
	Weekday_WEEKDAY_THURSDAY    Weekday = 5
	Weekday_WEEKDAY_FRIDAY      Weekday = 6
	Weekday_WEEKDAY_SATURDAY    Weekday = 7
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "WEEKDAY_UNSPECIFIED",
		1: "WEEKDAY_SUNDAY",
		2: "WEEKDAY_MONDAY",
		3: "WEEKDAY_TUESDAY",
		4: "WEEKDAY_WEDNESDAY",
		5: "WEEKDAY_THURSDAY",
		6: "WEEKDAY_FRIDAY",
		7: "WEEKDAY_SATURDAY",
	}
	Weekday_value = map[string]int32{
		"WEEKDAY_UNSPECIFIED": 0,
		"WEEKDAY_SUNDAY":      1,
		"WEEKDAY_MONDAY":      2,
		"WEEKDAY_TUESDAY":     3,
		"WEEKDAY_WEDNESDAY":   4,
		"WEEKDAY_THURSDAY":    5,
		"WEEKDAY_FRIDAY":      6,
		"WEEKDAY_SATURDAY":    7,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_course_slot_course_slot_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_course_slot_course_slot_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weekday.Descriptor instead.
func (Weekday) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{0}
}

// DayTime represents a time of day (hour and minute).
type DayTime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hour (0-23).
	Hour int32 `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	// Minute (0-59).
	Minute        int32 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayTime) Reset() {
	*x = DayTime{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayTime) ProtoMessage() {}

func (x *DayTime) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayTime.ProtoReflect.Descriptor instead.
func (*DayTime) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{0}
}

func (x *DayTime) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *DayTime) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

// DayTimeRange represents a time span within a single day.
type DayTimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time.
	Start *DayTime `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End time.
	End           *DayTime `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayTimeRange) Reset() {
	*x = DayTimeRange{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayTimeRange) ProtoMessage() {}

func (x *DayTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayTimeRange.ProtoReflect.Descriptor instead.
func (*DayTimeRange) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{1}
}

func (x *DayTimeRange) GetStart() *DayTime {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DayTimeRange) GetEnd() *DayTime {
	if x != nil {
		return x.End
	}
	return nil
}

// CourseSlot represents a weekly recurring time slot for a course.
type CourseSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The course this slot belongs to.
	CourseId string `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	// Day of the week.
	Weekday Weekday `protobuf:"varint,3,opt,name=weekday,proto3,enum=v1.course_scheduling.Weekday" json:"weekday,omitempty"`
	// Time range within the day.
	TimeRange *DayTimeRange `protobuf:"bytes,4,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Assigned teacher ID. -1 means unassigned.
	TeacherId int64 `protobuf:"varint,5,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	// Assigned classroom ID. Empty means unassigned.
	ClassroomId string `protobuf:"bytes,6,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	// Record creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSlot) Reset() {
	*x = CourseSlot{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSlot) ProtoMessage() {}

func (x *CourseSlot) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSlot.ProtoReflect.Descriptor instead.
func (*CourseSlot) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{2}
}

func (x *CourseSlot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseSlot) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseSlot) GetWeekday() Weekday {
	if x != nil {
		return x.Weekday
	}
	return Weekday_WEEKDAY_UNSPECIFIED
}

func (x *CourseSlot) GetTimeRange() *DayTimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *CourseSlot) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseSlot) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

func (x *CourseSlot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CourseSlot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CourseSlotSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseSlots   []*CourseSlot          `protobuf:"bytes,1,rep,name=course_slots,json=courseSlots,proto3" json:"course_slots,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSlotSet) Reset() {
	*x = CourseSlotSet{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSlotSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSlotSet) ProtoMessage() {}

func (x *CourseSlotSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSlotSet.ProtoReflect.Descriptor instead.
func (*CourseSlotSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{3}
}

func (x *CourseSlotSet) GetCourseSlots() []*CourseSlot {
	if x != nil {
		return x.CourseSlots
	}
	return nil
}

func (x *CourseSlotSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCourseSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseSlotRequest) Reset() {
	*x = GetCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseSlotRequest) ProtoMessage() {}

func (x *GetCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*GetCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseSlotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCourseSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSlotsRequest) Reset() {
	*x = ListCourseSlotsRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSlotsRequest) ProtoMessage() {}

func (x *ListCourseSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListCourseSlotsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{5}
}

func (x *ListCourseSlotsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCourseSlotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCourseSlotsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCourseSlotsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListCourseSlotsByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSlotsByCourseIDRequest) Reset() {
	*x = ListCourseSlotsByCourseIDRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSlotsByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSlotsByCourseIDRequest) ProtoMessage() {}

func (x *ListCourseSlotsByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSlotsByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*ListCourseSlotsByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{6}
}

func (x *ListCourseSlotsByCourseIDRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type AssignClassroomToCourseSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One or more slot IDs to assign.
	SlotIds []string `protobuf:"bytes,1,rep,name=slot_ids,json=slotIds,proto3" json:"slot_ids,omitempty"`
	// The classroom to assign.
	ClassroomId   string `protobuf:"bytes,2,opt,name=classroom_id,json=classroomId,proto3" json:"classroom_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignClassroomToCourseSlotRequest) Reset() {
	*x = AssignClassroomToCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignClassroomToCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignClassroomToCourseSlotRequest) ProtoMessage() {}

func (x *AssignClassroomToCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignClassroomToCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*AssignClassroomToCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{7}
}

func (x *AssignClassroomToCourseSlotRequest) GetSlotIds() []string {
	if x != nil {
		return x.SlotIds
	}
	return nil
}

func (x *AssignClassroomToCourseSlotRequest) GetClassroomId() string {
	if x != nil {
		return x.ClassroomId
	}
	return ""
}

type AssignCourseToCourseSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One or more slot IDs to assign.
	SlotIds []string `protobuf:"bytes,1,rep,name=slot_ids,json=slotIds,proto3" json:"slot_ids,omitempty"`
	// The course to assign.
	CourseId      string `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCourseToCourseSlotRequest) Reset() {
	*x = AssignCourseToCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCourseToCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCourseToCourseSlotRequest) ProtoMessage() {}

func (x *AssignCourseToCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCourseToCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*AssignCourseToCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{8}
}

func (x *AssignCourseToCourseSlotRequest) GetSlotIds() []string {
	if x != nil {
		return x.SlotIds
	}
	return nil
}

func (x *AssignCourseToCourseSlotRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type AssignTeacherToCourseSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One or more slot IDs to assign.
	SlotIds []string `protobuf:"bytes,1,rep,name=slot_ids,json=slotIds,proto3" json:"slot_ids,omitempty"`
	// The teacher to assign.
	TeacherId     int64 `protobuf:"varint,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTeacherToCourseSlotRequest) Reset() {
	*x = AssignTeacherToCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTeacherToCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTeacherToCourseSlotRequest) ProtoMessage() {}

func (x *AssignTeacherToCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTeacherToCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*AssignTeacherToCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{9}
}

func (x *AssignTeacherToCourseSlotRequest) GetSlotIds() []string {
	if x != nil {
		return x.SlotIds
	}
	return nil
}

func (x *AssignTeacherToCourseSlotRequest) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

type DeleteCourseSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseSlotRequest) Reset() {
	*x = DeleteCourseSlotRequest{}
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseSlotRequest) ProtoMessage() {}

func (x *DeleteCourseSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseSlotRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCourseSlotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_course_scheduling_course_slot_course_slot_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_course_slot_course_slot_proto_rawDesc = "" +
	"\n" +
	"2v1/course_scheduling/course_slot/course_slot.proto\x12\x14v1.course_scheduling\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\aDayTime\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\x05R\x06minute\"t\n" +
	"\fDayTimeRange\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1d.v1.course_scheduling.DayTimeR\x05start\x12/\n" +
	"\x03end\x18\x02 \x01(\v2\x1d.v1.course_scheduling.DayTimeR\x03end\"\xed\x02\n" +
	"\n" +
	"CourseSlot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x127\n" +
	"\aweekday\x18\x03 \x01(\x0e2\x1d.v1.course_scheduling.WeekdayR\aweekday\x12A\n" +
	"\n" +
	"time_range\x18\x04 \x01(\v2\".v1.course_scheduling.DayTimeRangeR\ttimeRange\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x05 \x01(\x03R\tteacherId\x12!\n" +
	"\fclassroom_id\x18\x06 \x01(\tR\vclassroomId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\rCourseSlotSet\x12C\n" +
	"\fcourse_slots\x18\x01 \x03(\v2 .v1.course_scheduling.CourseSlotR\vcourseSlots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x14GetCourseSlotRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x87\x01\n" +
	"\x16ListCourseSlotsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"D\n" +
	" ListCourseSlotsByCourseIDRequest\x12 \n" +
	"\tcourse_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bcourseId\"l\n" +
	"\"AssignClassroomToCourseSlotRequest\x12\x1e\n" +
	"\bslot_ids\x18\x01 \x03(\tB\x03\xe0A\x02R\aslotIds\x12&\n" +
	"\fclassroom_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vclassroomId\"c\n" +
	"\x1fAssignCourseToCourseSlotRequest\x12\x1e\n" +
	"\bslot_ids\x18\x01 \x03(\tB\x03\xe0A\x02R\aslotIds\x12 \n" +
	"\tcourse_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bcourseId\"f\n" +
	" AssignTeacherToCourseSlotRequest\x12\x1e\n" +
	"\bslot_ids\x18\x01 \x03(\tB\x03\xe0A\x02R\aslotIds\x12\"\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\x03B\x03\xe0A\x02R\tteacherId\".\n" +
	"\x17DeleteCourseSlotRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id*\xb6\x01\n" +
	"\aWeekday\x12\x17\n" +
	"\x13WEEKDAY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eWEEKDAY_SUNDAY\x10\x01\x12\x12\n" +
	"\x0eWEEKDAY_MONDAY\x10\x02\x12\x13\n" +
	"\x0fWEEKDAY_TUESDAY\x10\x03\x12\x15\n" +
	"\x11WEEKDAY_WEDNESDAY\x10\x04\x12\x14\n" +
	"\x10WEEKDAY_THURSDAY\x10\x05\x12\x12\n" +
	"\x0eWEEKDAY_FRIDAY\x10\x06\x12\x14\n" +
	"\x10WEEKDAY_SATURDAY\x10\a2\xfe\a\n" +
	"\x11CourseSlotService\x12\x9d\x01\n" +
	"\x1bAssignClassroomToCourseSlot\x128.v1.course_scheduling.AssignClassroomToCourseSlotRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/course-slots/assign-classroom\x12\x94\x01\n" +
	"\x18AssignCourseToCourseSlot\x125.v1.course_scheduling.AssignCourseToCourseSlotRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/course-slots/assign-course\x12\x97\x01\n" +
	"\x19AssignTeacherToCourseSlot\x126.v1.course_scheduling.AssignTeacherToCourseSlotRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/course-slots/assign-teacher\x12x\n" +
	"\x10DeleteCourseSlot\x12-.v1.course_scheduling.DeleteCourseSlotRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/course-slots/{id}\x12|\n" +
	"\rGetCourseSlot\x12*.v1.course_scheduling.GetCourseSlotRequest\x1a .v1.course_scheduling.CourseSlot\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/course-slots/{id}\x12~\n" +
	"\x0fListCourseSlots\x12,.v1.course_scheduling.ListCourseSlotsRequest\x1a#.v1.course_scheduling.CourseSlotSet\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/course-slots\x12\x9f\x01\n" +
	"\x19ListCourseSlotsByCourseID\x126.v1.course_scheduling.ListCourseSlotsByCourseIDRequest\x1a#.v1.course_scheduling.CourseSlotSet\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/courses/{course_id}/slotsBr\n" +
	"%io.grpc.examples.course_scheduling.v1B\x0fCourseSlotProtoP\x01Z6cqrs/api/v1/course_scheduling/course_slot;courseslotv1b\x06proto3"

var (
	file_v1_course_scheduling_course_slot_course_slot_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_course_slot_course_slot_proto_rawDescData []byte
)

func file_v1_course_scheduling_course_slot_course_slot_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_course_slot_course_slot_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_course_slot_course_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_slot_course_slot_proto_rawDesc), len(file_v1_course_scheduling_course_slot_course_slot_proto_rawDesc)))
	})
	return file_v1_course_scheduling_course_slot_course_slot_proto_rawDescData
}

var file_v1_course_scheduling_course_slot_course_slot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_course_scheduling_course_slot_course_slot_proto_goTypes = []any{
	(Weekday)(0),                               // 0: v1.course_scheduling.Weekday
	(*DayTime)(nil),                            // 1: v1.course_scheduling.DayTime
	(*DayTimeRange)(nil),                       // 2: v1.course_scheduling.DayTimeRange
	(*CourseSlot)(nil),                         // 3: v1.course_scheduling.CourseSlot
	(*CourseSlotSet)(nil),                      // 4: v1.course_scheduling.CourseSlotSet
	(*GetCourseSlotRequest)(nil),               // 5: v1.course_scheduling.GetCourseSlotRequest
	(*ListCourseSlotsRequest)(nil),             // 6: v1.course_scheduling.ListCourseSlotsRequest
	(*ListCourseSlotsByCourseIDRequest)(nil),   // 7: v1.course_scheduling.ListCourseSlotsByCourseIDRequest
	(*AssignClassroomToCourseSlotRequest)(nil), // 8: v1.course_scheduling.AssignClassroomToCourseSlotRequest
	(*AssignCourseToCourseSlotRequest)(nil),    // 9: v1.course_scheduling.AssignCourseToCourseSlotRequest
	(*AssignTeacherToCourseSlotRequest)(nil),   // 10: v1.course_scheduling.AssignTeacherToCourseSlotRequest
	(*DeleteCourseSlotRequest)(nil),            // 11: v1.course_scheduling.DeleteCourseSlotRequest
	(*timestamppb.Timestamp)(nil),              // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                      // 13: google.protobuf.Empty
}
var file_v1_course_scheduling_course_slot_course_slot_proto_depIdxs = []int32{
	1,  // 0: v1.course_scheduling.DayTimeRange.start:type_name -> v1.course_scheduling.DayTime
	1,  // 1: v1.course_scheduling.DayTimeRange.end:type_name -> v1.course_scheduling.DayTime
	0,  // 2: v1.course_scheduling.CourseSlot.weekday:type_name -> v1.course_scheduling.Weekday
	2,  // 3: v1.course_scheduling.CourseSlot.time_range:type_name -> v1.course_scheduling.DayTimeRange
	12, // 4: v1.course_scheduling.CourseSlot.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: v1.course_scheduling.CourseSlot.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: v1.course_scheduling.CourseSlotSet.course_slots:type_name -> v1.course_scheduling.CourseSlot
	8,  // 7: v1.course_scheduling.CourseSlotService.AssignClassroomToCourseSlot:input_type -> v1.course_scheduling.AssignClassroomToCourseSlotRequest
	9,  // 8: v1.course_scheduling.CourseSlotService.AssignCourseToCourseSlot:input_type -> v1.course_scheduling.AssignCourseToCourseSlotRequest
	10, // 9: v1.course_scheduling.CourseSlotService.AssignTeacherToCourseSlot:input_type -> v1.course_scheduling.AssignTeacherToCourseSlotRequest
	11, // 10: v1.course_scheduling.CourseSlotService.DeleteCourseSlot:input_type -> v1.course_scheduling.DeleteCourseSlotRequest
	5,  // 11: v1.course_scheduling.CourseSlotService.GetCourseSlot:input_type -> v1.course_scheduling.GetCourseSlotRequest
	6,  // 12: v1.course_scheduling.CourseSlotService.ListCourseSlots:input_type -> v1.course_scheduling.ListCourseSlotsRequest
	7,  // 13: v1.course_scheduling.CourseSlotService.ListCourseSlotsByCourseID:input_type -> v1.course_scheduling.ListCourseSlotsByCourseIDRequest
	13, // 14: v1.course_scheduling.CourseSlotService.AssignClassroomToCourseSlot:output_type -> google.protobuf.Empty
	13, // 15: v1.course_scheduling.CourseSlotService.AssignCourseToCourseSlot:output_type -> google.protobuf.Empty
	13, // 16: v1.course_scheduling.CourseSlotService.AssignTeacherToCourseSlot:output_type -> google.protobuf.Empty
	13, // 17: v1.course_scheduling.CourseSlotService.DeleteCourseSlot:output_type -> google.protobuf.Empty
	3,  // 18: v1.course_scheduling.CourseSlotService.GetCourseSlot:output_type -> v1.course_scheduling.CourseSlot
	4,  // 19: v1.course_scheduling.CourseSlotService.ListCourseSlots:output_type -> v1.course_scheduling.CourseSlotSet
	4,  // 20: v1.course_scheduling.CourseSlotService.ListCourseSlotsByCourseID:output_type -> v1.course_scheduling.CourseSlotSet
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_course_slot_course_slot_proto_init() }
func file_v1_course_scheduling_course_slot_course_slot_proto_init() {
	if File_v1_course_scheduling_course_slot_course_slot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_course_slot_course_slot_proto_rawDesc), len(file_v1_course_scheduling_course_slot_course_slot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_course_slot_course_slot_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_course_slot_course_slot_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_course_slot_course_slot_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_course_slot_course_slot_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_course_slot_course_slot_proto = out.File
	file_v1_course_scheduling_course_slot_course_slot_proto_goTypes = nil
	file_v1_course_scheduling_course_slot_course_slot_proto_depIdxs = nil
}
