// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: v1/course_scheduling/enrollment/enrollment.proto

package enrollmentv1

import (
	context "context"
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationEnrollmentServiceDeleteEnrollment = "/v1.course_scheduling.EnrollmentService/DeleteEnrollment"
const OperationEnrollmentServiceEnrollStudent = "/v1.course_scheduling.EnrollmentService/EnrollStudent"
const OperationEnrollmentServiceGetEnrollment = "/v1.course_scheduling.EnrollmentService/GetEnrollment"
const OperationEnrollmentServiceListEnrolledCoursesByStudentID = "/v1.course_scheduling.EnrollmentService/ListEnrolledCoursesByStudentID"
const OperationEnrollmentServiceListEnrolledStudentsByCourseID = "/v1.course_scheduling.EnrollmentService/ListEnrolledStudentsByCourseID"
const OperationEnrollmentServiceListEnrollments = "/v1.course_scheduling.EnrollmentService/ListEnrollments"

type EnrollmentServiceHTTPServer interface {
	// DeleteEnrollment DeleteEnrollment hard-deletes an enrollment record by ID.
	DeleteEnrollment(context.Context, *DeleteEnrollmentRequest) (*emptypb.Empty, error)
	// EnrollStudent EnrollStudent enrolls a student in a course.
	EnrollStudent(context.Context, *EnrollStudentRequest) (*CourseEnrollment, error)
	// GetEnrollment GetEnrollment returns a single enrollment record by ID.
	GetEnrollment(context.Context, *GetEnrollmentRequest) (*CourseEnrollment, error)
	// ListEnrolledCoursesByStudentID ListEnrolledCoursesByStudentID returns all courses a student is enrolled in.
	ListEnrolledCoursesByStudentID(context.Context, *ListEnrolledCoursesByStudentIDRequest) (*course.CourseSet, error)
	// ListEnrolledStudentsByCourseID ListEnrolledStudentsByCourseID returns all students enrolled in a course.
	ListEnrolledStudentsByCourseID(context.Context, *ListEnrolledStudentsByCourseIDRequest) (*student.StudentSet, error)
	// ListEnrollments ListEnrollments returns a page of enrollment records.
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*CourseEnrollmentSet, error)
}

func RegisterEnrollmentServiceHTTPServer(s *http.Server, srv EnrollmentServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/enrollments", _EnrollmentService_EnrollStudent0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/enrollments/{id}", _EnrollmentService_DeleteEnrollment0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/enrollments/{id}", _EnrollmentService_GetEnrollment0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/enrollments", _EnrollmentService_ListEnrollments0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/students/{student_id}/courses", _EnrollmentService_ListEnrolledCoursesByStudentID0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/courses/{course_id}/students", _EnrollmentService_ListEnrolledStudentsByCourseID0_HTTP_Handler(srv))
}

func _EnrollmentService_EnrollStudent0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnrollStudentRequest
		if err := ctx.Bind(&in.Enrollment); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceEnrollStudent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnrollStudent(ctx, req.(*EnrollStudentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseEnrollment)
		return ctx.Result(200, reply)
	}
}

func _EnrollmentService_DeleteEnrollment0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEnrollmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceDeleteEnrollment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEnrollment(ctx, req.(*DeleteEnrollmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _EnrollmentService_GetEnrollment0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEnrollmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceGetEnrollment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEnrollment(ctx, req.(*GetEnrollmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseEnrollment)
		return ctx.Result(200, reply)
	}
}

func _EnrollmentService_ListEnrollments0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEnrollmentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceListEnrollments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CourseEnrollmentSet)
		return ctx.Result(200, reply)
	}
}

func _EnrollmentService_ListEnrolledCoursesByStudentID0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEnrolledCoursesByStudentIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceListEnrolledCoursesByStudentID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnrolledCoursesByStudentID(ctx, req.(*ListEnrolledCoursesByStudentIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*course.CourseSet)
		return ctx.Result(200, reply)
	}
}

func _EnrollmentService_ListEnrolledStudentsByCourseID0_HTTP_Handler(srv EnrollmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEnrolledStudentsByCourseIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnrollmentServiceListEnrolledStudentsByCourseID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnrolledStudentsByCourseID(ctx, req.(*ListEnrolledStudentsByCourseIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*student.StudentSet)
		return ctx.Result(200, reply)
	}
}

type EnrollmentServiceHTTPClient interface {
	// DeleteEnrollment DeleteEnrollment hard-deletes an enrollment record by ID.
	DeleteEnrollment(ctx context.Context, req *DeleteEnrollmentRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// EnrollStudent EnrollStudent enrolls a student in a course.
	EnrollStudent(ctx context.Context, req *EnrollStudentRequest, opts ...http.CallOption) (rsp *CourseEnrollment, err error)
	// GetEnrollment GetEnrollment returns a single enrollment record by ID.
	GetEnrollment(ctx context.Context, req *GetEnrollmentRequest, opts ...http.CallOption) (rsp *CourseEnrollment, err error)
	// ListEnrolledCoursesByStudentID ListEnrolledCoursesByStudentID returns all courses a student is enrolled in.
	ListEnrolledCoursesByStudentID(ctx context.Context, req *ListEnrolledCoursesByStudentIDRequest, opts ...http.CallOption) (rsp *course.CourseSet, err error)
	// ListEnrolledStudentsByCourseID ListEnrolledStudentsByCourseID returns all students enrolled in a course.
	ListEnrolledStudentsByCourseID(ctx context.Context, req *ListEnrolledStudentsByCourseIDRequest, opts ...http.CallOption) (rsp *student.StudentSet, err error)
	// ListEnrollments ListEnrollments returns a page of enrollment records.
	ListEnrollments(ctx context.Context, req *ListEnrollmentsRequest, opts ...http.CallOption) (rsp *CourseEnrollmentSet, err error)
}

type EnrollmentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEnrollmentServiceHTTPClient(client *http.Client) EnrollmentServiceHTTPClient {
	return &EnrollmentServiceHTTPClientImpl{client}
}

// DeleteEnrollment DeleteEnrollment hard-deletes an enrollment record by ID.
func (c *EnrollmentServiceHTTPClientImpl) DeleteEnrollment(ctx context.Context, in *DeleteEnrollmentRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/enrollments/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEnrollmentServiceDeleteEnrollment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EnrollStudent EnrollStudent enrolls a student in a course.
func (c *EnrollmentServiceHTTPClientImpl) EnrollStudent(ctx context.Context, in *EnrollStudentRequest, opts ...http.CallOption) (*CourseEnrollment, error) {
	var out CourseEnrollment
	pattern := "/v1/enrollments"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("enrollment"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationEnrollmentServiceEnrollStudent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Enrollment, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEnrollment GetEnrollment returns a single enrollment record by ID.
func (c *EnrollmentServiceHTTPClientImpl) GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...http.CallOption) (*CourseEnrollment, error) {
	var out CourseEnrollment
	pattern := "/v1/enrollments/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEnrollmentServiceGetEnrollment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEnrolledCoursesByStudentID ListEnrolledCoursesByStudentID returns all courses a student is enrolled in.
func (c *EnrollmentServiceHTTPClientImpl) ListEnrolledCoursesByStudentID(ctx context.Context, in *ListEnrolledCoursesByStudentIDRequest, opts ...http.CallOption) (*course.CourseSet, error) {
	var out course.CourseSet
	pattern := "/v1/students/{student_id}/courses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEnrollmentServiceListEnrolledCoursesByStudentID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEnrolledStudentsByCourseID ListEnrolledStudentsByCourseID returns all students enrolled in a course.
func (c *EnrollmentServiceHTTPClientImpl) ListEnrolledStudentsByCourseID(ctx context.Context, in *ListEnrolledStudentsByCourseIDRequest, opts ...http.CallOption) (*student.StudentSet, error) {
	var out student.StudentSet
	pattern := "/v1/courses/{course_id}/students"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEnrollmentServiceListEnrolledStudentsByCourseID),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEnrollments ListEnrollments returns a page of enrollment records.
func (c *EnrollmentServiceHTTPClientImpl) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...http.CallOption) (*CourseEnrollmentSet, error) {
	var out CourseEnrollmentSet
	pattern := "/v1/enrollments"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationEnrollmentServiceListEnrollments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
