// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/course_scheduling/enrollment/enrollment.proto

package enrollmentv1

import (
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrollmentStatus represents the state of a course enrollment.
type EnrollmentStatus int32

const (
	EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED EnrollmentStatus = 0
	EnrollmentStatus_ENROLLMENT_STATUS_ENROLLED    EnrollmentStatus = 1
	EnrollmentStatus_ENROLLMENT_STATUS_COMPLETED   EnrollmentStatus = 2
	EnrollmentStatus_ENROLLMENT_STATUS_DROPPED     EnrollmentStatus = 3
)

// Enum value maps for EnrollmentStatus.
var (
	EnrollmentStatus_name = map[int32]string{
		0: "ENROLLMENT_STATUS_UNSPECIFIED",
		1: "ENROLLMENT_STATUS_ENROLLED",
		2: "ENROLLMENT_STATUS_COMPLETED",
		3: "ENROLLMENT_STATUS_DROPPED",
	}
	EnrollmentStatus_value = map[string]int32{
		"ENROLLMENT_STATUS_UNSPECIFIED": 0,
		"ENROLLMENT_STATUS_ENROLLED":    1,
		"ENROLLMENT_STATUS_COMPLETED":   2,
		"ENROLLMENT_STATUS_DROPPED":     3,
	}
)

func (x EnrollmentStatus) Enum() *EnrollmentStatus {
	p := new(EnrollmentStatus)
	*p = x
	return p
}

func (x EnrollmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_course_scheduling_enrollment_enrollment_proto_enumTypes[0].Descriptor()
}

func (EnrollmentStatus) Type() protoreflect.EnumType {
	return &file_v1_course_scheduling_enrollment_enrollment_proto_enumTypes[0]
}

func (x EnrollmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentStatus.Descriptor instead.
func (EnrollmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{0}
}

// CourseEnrollment represents a student's enrollment in a course.
type CourseEnrollment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System-assigned ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The enrolled student ID.
	StudentId int64 `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// The course ID.
	CourseId string `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	// Enrollment status.
	Status EnrollmentStatus `protobuf:"varint,4,opt,name=status,proto3,enum=v1.course_scheduling.EnrollmentStatus" json:"status,omitempty"`
	// Time of enrollment.
	EnrolledAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	// Time of completion (if completed).
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Time of drop (if dropped).
	DroppedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	// Last modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseEnrollment) Reset() {
	*x = CourseEnrollment{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseEnrollment) ProtoMessage() {}

func (x *CourseEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseEnrollment.ProtoReflect.Descriptor instead.
func (*CourseEnrollment) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *CourseEnrollment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseEnrollment) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CourseEnrollment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseEnrollment) GetStatus() EnrollmentStatus {
	if x != nil {
		return x.Status
	}
	return EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED
}

func (x *CourseEnrollment) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

func (x *CourseEnrollment) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CourseEnrollment) GetDroppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DroppedAt
	}
	return nil
}

func (x *CourseEnrollment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CourseEnrollmentSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*CourseEnrollment    `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseEnrollmentSet) Reset() {
	*x = CourseEnrollmentSet{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseEnrollmentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseEnrollmentSet) ProtoMessage() {}

func (x *CourseEnrollmentSet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseEnrollmentSet.ProtoReflect.Descriptor instead.
func (*CourseEnrollmentSet) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *CourseEnrollmentSet) GetEnrollments() []*CourseEnrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

type EnrollStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *CourseEnrollment      `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollStudentRequest) Reset() {
	*x = EnrollStudentRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollStudentRequest) ProtoMessage() {}

func (x *EnrollStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollStudentRequest.ProtoReflect.Descriptor instead.
func (*EnrollStudentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollStudentRequest) GetEnrollment() *CourseEnrollment {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

type GetEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentRequest) Reset() {
	*x = GetEnrollmentRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentRequest) ProtoMessage() {}

func (x *GetEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnrollmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsRequest) Reset() {
	*x = ListEnrollmentsRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsRequest) ProtoMessage() {}

func (x *ListEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *ListEnrollmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEnrollmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEnrollmentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListEnrolledCoursesByStudentIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrolledCoursesByStudentIDRequest) Reset() {
	*x = ListEnrolledCoursesByStudentIDRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrolledCoursesByStudentIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrolledCoursesByStudentIDRequest) ProtoMessage() {}

func (x *ListEnrolledCoursesByStudentIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrolledCoursesByStudentIDRequest.ProtoReflect.Descriptor instead.
func (*ListEnrolledCoursesByStudentIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *ListEnrolledCoursesByStudentIDRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type ListEnrolledStudentsByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrolledStudentsByCourseIDRequest) Reset() {
	*x = ListEnrolledStudentsByCourseIDRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrolledStudentsByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrolledStudentsByCourseIDRequest) ProtoMessage() {}

func (x *ListEnrolledStudentsByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrolledStudentsByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*ListEnrolledStudentsByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{6}
}

func (x *ListEnrolledStudentsByCourseIDRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DeleteEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnrollmentRequest) Reset() {
	*x = DeleteEnrollmentRequest{}
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnrollmentRequest) ProtoMessage() {}

func (x *DeleteEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEnrollmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_course_scheduling_enrollment_enrollment_proto protoreflect.FileDescriptor

const file_v1_course_scheduling_enrollment_enrollment_proto_rawDesc = "" +
	"\n" +
	"0v1/course_scheduling/enrollment/enrollment.proto\x12\x14v1.course_scheduling\x1a(v1/course_scheduling/course/course.proto\x1a*v1/course_scheduling/student/student.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n" +
	"\x10CourseEnrollment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.v1.course_scheduling.EnrollmentStatusR\x06status\x12;\n" +
	"\venrolled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"dropped_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdroppedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"_\n" +
	"\x13CourseEnrollmentSet\x12H\n" +
	"\venrollments\x18\x01 \x03(\v2&.v1.course_scheduling.CourseEnrollmentR\venrollments\"c\n" +
	"\x14EnrollStudentRequest\x12K\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2&.v1.course_scheduling.CourseEnrollmentB\x03\xe0A\x02R\n" +
	"enrollment\"+\n" +
	"\x14GetEnrollmentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"|\n" +
	"\x16ListEnrollmentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"K\n" +
	"%ListEnrolledCoursesByStudentIDRequest\x12\"\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\tstudentId\"I\n" +
	"%ListEnrolledStudentsByCourseIDRequest\x12 \n" +
	"\tcourse_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bcourseId\".\n" +
	"\x17DeleteEnrollmentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id*\x95\x01\n" +
	"\x10EnrollmentStatus\x12!\n" +
	"\x1dENROLLMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aENROLLMENT_STATUS_ENROLLED\x10\x01\x12\x1f\n" +
	"\x1bENROLLMENT_STATUS_COMPLETED\x10\x02\x12\x1d\n" +
	"\x19ENROLLMENT_STATUS_DROPPED\x10\x032\xe8\x06\n" +
	"\x11EnrollmentService\x12x\n" +
	"\rEnrollStudent\x12*.v1.course_scheduling.EnrollStudentRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\n" +
	"enrollment\"\x0f/v1/enrollments\x12w\n" +
	"\x10DeleteEnrollment\x12-.v1.course_scheduling.DeleteEnrollmentRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/enrollments/{id}\x12\x81\x01\n" +
	"\rGetEnrollment\x12*.v1.course_scheduling.GetEnrollmentRequest\x1a&.v1.course_scheduling.CourseEnrollment\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/enrollments/{id}\x12\x83\x01\n" +
	"\x0fListEnrollments\x12,.v1.course_scheduling.ListEnrollmentsRequest\x1a).v1.course_scheduling.CourseEnrollmentSet\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/enrollments\x12\xa9\x01\n" +
	"\x1eListEnrolledCoursesByStudentID\x12;.v1.course_scheduling.ListEnrolledCoursesByStudentIDRequest\x1a\x1f.v1.course_scheduling.CourseSet\")\x82\xd3\xe4\x93\x02#\x12!/v1/students/{student_id}/courses\x12\xa9\x01\n" +
	"\x1eListEnrolledStudentsByCourseID\x12;.v1.course_scheduling.ListEnrolledStudentsByCourseIDRequest\x1a .v1.course_scheduling.StudentSet\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/courses/{course_id}/studentsBq\n" +
	"%io.grpc.examples.course_scheduling.v1B\x0fEnrollmentProtoP\x01Z5cqrs/api/v1/course_scheduling/enrollment;enrollmentv1b\x06proto3"

var (
	file_v1_course_scheduling_enrollment_enrollment_proto_rawDescOnce sync.Once
	file_v1_course_scheduling_enrollment_enrollment_proto_rawDescData []byte
)

func file_v1_course_scheduling_enrollment_enrollment_proto_rawDescGZIP() []byte {
	file_v1_course_scheduling_enrollment_enrollment_proto_rawDescOnce.Do(func() {
		file_v1_course_scheduling_enrollment_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_enrollment_enrollment_proto_rawDesc), len(file_v1_course_scheduling_enrollment_enrollment_proto_rawDesc)))
	})
	return file_v1_course_scheduling_enrollment_enrollment_proto_rawDescData
}

var file_v1_course_scheduling_enrollment_enrollment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_course_scheduling_enrollment_enrollment_proto_goTypes = []any{
	(EnrollmentStatus)(0),                         // 0: v1.course_scheduling.EnrollmentStatus
	(*CourseEnrollment)(nil),                      // 1: v1.course_scheduling.CourseEnrollment
	(*CourseEnrollmentSet)(nil),                   // 2: v1.course_scheduling.CourseEnrollmentSet
	(*EnrollStudentRequest)(nil),                  // 3: v1.course_scheduling.EnrollStudentRequest
	(*GetEnrollmentRequest)(nil),                  // 4: v1.course_scheduling.GetEnrollmentRequest
	(*ListEnrollmentsRequest)(nil),                // 5: v1.course_scheduling.ListEnrollmentsRequest
	(*ListEnrolledCoursesByStudentIDRequest)(nil), // 6: v1.course_scheduling.ListEnrolledCoursesByStudentIDRequest
	(*ListEnrolledStudentsByCourseIDRequest)(nil), // 7: v1.course_scheduling.ListEnrolledStudentsByCourseIDRequest
	(*DeleteEnrollmentRequest)(nil),               // 8: v1.course_scheduling.DeleteEnrollmentRequest
	(*timestamppb.Timestamp)(nil),                 // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                         // 10: google.protobuf.Empty
	(*course.CourseSet)(nil),                      // 11: v1.course_scheduling.CourseSet
	(*student.StudentSet)(nil),                    // 12: v1.course_scheduling.StudentSet
}
var file_v1_course_scheduling_enrollment_enrollment_proto_depIdxs = []int32{
	0,  // 0: v1.course_scheduling.CourseEnrollment.status:type_name -> v1.course_scheduling.EnrollmentStatus
	9,  // 1: v1.course_scheduling.CourseEnrollment.enrolled_at:type_name -> google.protobuf.Timestamp
	9,  // 2: v1.course_scheduling.CourseEnrollment.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 3: v1.course_scheduling.CourseEnrollment.dropped_at:type_name -> google.protobuf.Timestamp
	9,  // 4: v1.course_scheduling.CourseEnrollment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: v1.course_scheduling.CourseEnrollmentSet.enrollments:type_name -> v1.course_scheduling.CourseEnrollment
	1,  // 6: v1.course_scheduling.EnrollStudentRequest.enrollment:type_name -> v1.course_scheduling.CourseEnrollment
	3,  // 7: v1.course_scheduling.EnrollmentService.EnrollStudent:input_type -> v1.course_scheduling.EnrollStudentRequest
	8,  // 8: v1.course_scheduling.EnrollmentService.DeleteEnrollment:input_type -> v1.course_scheduling.DeleteEnrollmentRequest
	4,  // 9: v1.course_scheduling.EnrollmentService.GetEnrollment:input_type -> v1.course_scheduling.GetEnrollmentRequest
	5,  // 10: v1.course_scheduling.EnrollmentService.ListEnrollments:input_type -> v1.course_scheduling.ListEnrollmentsRequest
	6,  // 11: v1.course_scheduling.EnrollmentService.ListEnrolledCoursesByStudentID:input_type -> v1.course_scheduling.ListEnrolledCoursesByStudentIDRequest
	7,  // 12: v1.course_scheduling.EnrollmentService.ListEnrolledStudentsByCourseID:input_type -> v1.course_scheduling.ListEnrolledStudentsByCourseIDRequest
	10, // 13: v1.course_scheduling.EnrollmentService.EnrollStudent:output_type -> google.protobuf.Empty
	10, // 14: v1.course_scheduling.EnrollmentService.DeleteEnrollment:output_type -> google.protobuf.Empty
	1,  // 15: v1.course_scheduling.EnrollmentService.GetEnrollment:output_type -> v1.course_scheduling.CourseEnrollment
	2,  // 16: v1.course_scheduling.EnrollmentService.ListEnrollments:output_type -> v1.course_scheduling.CourseEnrollmentSet
	11, // 17: v1.course_scheduling.EnrollmentService.ListEnrolledCoursesByStudentID:output_type -> v1.course_scheduling.CourseSet
	12, // 18: v1.course_scheduling.EnrollmentService.ListEnrolledStudentsByCourseID:output_type -> v1.course_scheduling.StudentSet
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_course_scheduling_enrollment_enrollment_proto_init() }
func file_v1_course_scheduling_enrollment_enrollment_proto_init() {
	if File_v1_course_scheduling_enrollment_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_scheduling_enrollment_enrollment_proto_rawDesc), len(file_v1_course_scheduling_enrollment_enrollment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_scheduling_enrollment_enrollment_proto_goTypes,
		DependencyIndexes: file_v1_course_scheduling_enrollment_enrollment_proto_depIdxs,
		EnumInfos:         file_v1_course_scheduling_enrollment_enrollment_proto_enumTypes,
		MessageInfos:      file_v1_course_scheduling_enrollment_enrollment_proto_msgTypes,
	}.Build()
	File_v1_course_scheduling_enrollment_enrollment_proto = out.File
	file_v1_course_scheduling_enrollment_enrollment_proto_goTypes = nil
	file_v1_course_scheduling_enrollment_enrollment_proto_depIdxs = nil
}
