// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/course_scheduling/enrollment/enrollment.proto

package enrollmentv1

import (
	context "context"
	course "cqrs/api/v1/course_scheduling/course"
	student "cqrs/api/v1/course_scheduling/student"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_EnrollStudent_FullMethodName                  = "/v1.course_scheduling.EnrollmentService/EnrollStudent"
	EnrollmentService_DeleteEnrollment_FullMethodName               = "/v1.course_scheduling.EnrollmentService/DeleteEnrollment"
	EnrollmentService_GetEnrollment_FullMethodName                  = "/v1.course_scheduling.EnrollmentService/GetEnrollment"
	EnrollmentService_ListEnrollments_FullMethodName                = "/v1.course_scheduling.EnrollmentService/ListEnrollments"
	EnrollmentService_ListEnrolledCoursesByStudentID_FullMethodName = "/v1.course_scheduling.EnrollmentService/ListEnrolledCoursesByStudentID"
	EnrollmentService_ListEnrolledStudentsByCourseID_FullMethodName = "/v1.course_scheduling.EnrollmentService/ListEnrolledStudentsByCourseID"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnrollmentService owns the enrollment aggregate.
//
// The two cross-aggregate listings stay here rather than moving to Course or
// Student: they are enrollment questions ("which rows link X and Y") whose
// answers happen to be courses or students.
type EnrollmentServiceClient interface {
	// EnrollStudent enrolls a student in a course.
	EnrollStudent(ctx context.Context, in *EnrollStudentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteEnrollment hard-deletes an enrollment record by ID.
	DeleteEnrollment(ctx context.Context, in *DeleteEnrollmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetEnrollment returns a single enrollment record by ID.
	GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*CourseEnrollment, error)
	// ListEnrollments returns a page of enrollment records.
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*CourseEnrollmentSet, error)
	// ListEnrolledCoursesByStudentID returns all courses a student is enrolled in.
	ListEnrolledCoursesByStudentID(ctx context.Context, in *ListEnrolledCoursesByStudentIDRequest, opts ...grpc.CallOption) (*course.CourseSet, error)
	// ListEnrolledStudentsByCourseID returns all students enrolled in a course.
	ListEnrolledStudentsByCourseID(ctx context.Context, in *ListEnrolledStudentsByCourseIDRequest, opts ...grpc.CallOption) (*student.StudentSet, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) EnrollStudent(ctx context.Context, in *EnrollStudentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EnrollmentService_EnrollStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) DeleteEnrollment(ctx context.Context, in *DeleteEnrollmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EnrollmentService_DeleteEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*CourseEnrollment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseEnrollment)
	err := c.cc.Invoke(ctx, EnrollmentService_GetEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*CourseEnrollmentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseEnrollmentSet)
	err := c.cc.Invoke(ctx, EnrollmentService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) ListEnrolledCoursesByStudentID(ctx context.Context, in *ListEnrolledCoursesByStudentIDRequest, opts ...grpc.CallOption) (*course.CourseSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(course.CourseSet)
	err := c.cc.Invoke(ctx, EnrollmentService_ListEnrolledCoursesByStudentID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) ListEnrolledStudentsByCourseID(ctx context.Context, in *ListEnrolledStudentsByCourseIDRequest, opts ...grpc.CallOption) (*student.StudentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(student.StudentSet)
	err := c.cc.Invoke(ctx, EnrollmentService_ListEnrolledStudentsByCourseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
//
// EnrollmentService owns the enrollment aggregate.
//
// The two cross-aggregate listings stay here rather than moving to Course or
// Student: they are enrollment questions ("which rows link X and Y") whose
// answers happen to be courses or students.
type EnrollmentServiceServer interface {
	// EnrollStudent enrolls a student in a course.
	EnrollStudent(context.Context, *EnrollStudentRequest) (*emptypb.Empty, error)
	// DeleteEnrollment hard-deletes an enrollment record by ID.
	DeleteEnrollment(context.Context, *DeleteEnrollmentRequest) (*emptypb.Empty, error)
	// GetEnrollment returns a single enrollment record by ID.
	GetEnrollment(context.Context, *GetEnrollmentRequest) (*CourseEnrollment, error)
	// ListEnrollments returns a page of enrollment records.
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*CourseEnrollmentSet, error)
	// ListEnrolledCoursesByStudentID returns all courses a student is enrolled in.
	ListEnrolledCoursesByStudentID(context.Context, *ListEnrolledCoursesByStudentIDRequest) (*course.CourseSet, error)
	// ListEnrolledStudentsByCourseID returns all students enrolled in a course.
	ListEnrolledStudentsByCourseID(context.Context, *ListEnrolledStudentsByCourseIDRequest) (*student.StudentSet, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) EnrollStudent(context.Context, *EnrollStudentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollStudent not implemented")
}
func (UnimplementedEnrollmentServiceServer) DeleteEnrollment(context.Context, *DeleteEnrollmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnrollment not implemented")
}
func (UnimplementedEnrollmentServiceServer) GetEnrollment(context.Context, *GetEnrollmentRequest) (*CourseEnrollment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnrollment not implemented")
}
func (UnimplementedEnrollmentServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*CourseEnrollmentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedEnrollmentServiceServer) ListEnrolledCoursesByStudentID(context.Context, *ListEnrolledCoursesByStudentIDRequest) (*course.CourseSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnrolledCoursesByStudentID not implemented")
}
func (UnimplementedEnrollmentServiceServer) ListEnrolledStudentsByCourseID(context.Context, *ListEnrolledStudentsByCourseIDRequest) (*student.StudentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnrolledStudentsByCourseID not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_EnrollStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).EnrollStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_EnrollStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).EnrollStudent(ctx, req.(*EnrollStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_DeleteEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).DeleteEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_DeleteEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).DeleteEnrollment(ctx, req.(*DeleteEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_GetEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).GetEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_GetEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).GetEnrollment(ctx, req.(*GetEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_ListEnrolledCoursesByStudentID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrolledCoursesByStudentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).ListEnrolledCoursesByStudentID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_ListEnrolledCoursesByStudentID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).ListEnrolledCoursesByStudentID(ctx, req.(*ListEnrolledCoursesByStudentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_ListEnrolledStudentsByCourseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrolledStudentsByCourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).ListEnrolledStudentsByCourseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_ListEnrolledStudentsByCourseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).ListEnrolledStudentsByCourseID(ctx, req.(*ListEnrolledStudentsByCourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.course_scheduling.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollStudent",
			Handler:    _EnrollmentService_EnrollStudent_Handler,
		},
		{
			MethodName: "DeleteEnrollment",
			Handler:    _EnrollmentService_DeleteEnrollment_Handler,
		},
		{
			MethodName: "GetEnrollment",
			Handler:    _EnrollmentService_GetEnrollment_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _EnrollmentService_ListEnrollments_Handler,
		},
		{
			MethodName: "ListEnrolledCoursesByStudentID",
			Handler:    _EnrollmentService_ListEnrolledCoursesByStudentID_Handler,
		},
		{
			MethodName: "ListEnrolledStudentsByCourseID",
			Handler:    _EnrollmentService_ListEnrolledStudentsByCourseID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/course_scheduling/enrollment/enrollment.proto",
}
